'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ExamEditor} from '../learning/exam';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;error?:string};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[editing,setEditing]=useState<R|'new'|null>(null),[title,setTitle]=useState(''),[orgId,setOrg]=useState('none'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<string|null>(null);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/learning-exams',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]);const [d,h]=await Promise.all([a.json() as Promise<Data>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok||!b.ok)throw Error(d.error??h.error);setData(d);setCore(h.state);}catch(e){setData(null);setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function send(command:Record<string,unknown>){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/learning-exams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setEditing(null);}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const seed=editing&&editing!=='new'?{questions:editing.payload.questions!.map(q=>({...q,correct:q.correct!})),passingScore:editing.payload.passingScore!,maxAttempts:editing.payload.maxAttempts!}:undefined;
 return <main className="main-content mx-auto max-w-5xl"><Link href="/learning-plans">返回学习计划配置</Link> · <Link href="/learning-exam-tasks">独立考试任务</Link><div className="page-head mt-5"><h1>独立试卷</h1><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-4 text-slate-600">管理单选试卷及不可变版本。定版后可到独立考试任务中派发。当前仅支持等权单选题；多题型、题库导入及计划总成绩仍在建设中。</p>{error&&<p role="alert">{error}</p>}{data&&<Button disabled={busy} onClick={()=>{setEditing('new');setTitle('');setOrg('none');}}>新建试卷</Button>}
 {editing&&<section className="panel mt-4 space-y-4"><label className="field">试卷名称<Input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label className="field">所属组织<Select value={orgId} disabled={editing!=='new'} onValueChange={setOrg}><SelectTrigger aria-label="试卷所属组织"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{core?.orgs.filter(o=>o.status==='启用').map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></label><ExamEditor key={editing==='new'?'new':editing.id+editing.updatedAt} courseId="standalone" standalone initial={seed} busy={busy} send={async c=>{if(!title.trim()||orgId==='none'){setError('请填写试卷名称并选择所属组织');return;}await send({action:editing==='new'?'create':'edit',...(editing==='new'?{}:{id:editing.id}),title,orgId,questions:c.questions,passingScore:c.passingScore,maxAttempts:c.maxAttempts});}}/><Button variant="outline" disabled={busy} onClick={()=>setEditing(null)}>取消编辑</Button></section>}
 <section className="mt-5 space-y-4">{data?.records.map(r=><article key={r.id} className="panel"><h2>{r.payload.title} · v{r.payload.version}</h2><p>{r.status==='sealed'?'已定版':r.status==='draft'?'草稿':'已归档'} · {r.payload.questions?.length}道单选题 · 及格线{r.payload.passingScore} · 最多{r.payload.maxAttempts}次</p><div className="mt-3 flex gap-2">{r.status==='draft'&&<><Button disabled={busy} variant="outline" onClick={()=>{setEditing(r);setTitle(r.payload.title!);setOrg(r.payload.orgId!);}}>编辑试卷</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{r.status==='sealed'&&<Button disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>创建后续版本</Button>}{r.status!=='archived'&&<Button disabled={busy} variant="outline" onClick={()=>send({action:'archive',id:r.id})}>归档</Button>}<Button variant="ghost" onClick={()=>setHistory(history===r.id?null:r.id)}>历史</Button></div>{history===r.id&&<ProcessHistory id={r.id} updatedAt={r.updatedAt}/>}</article>)}</section></main>;
}
