'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {PerformanceTemplateSnapshot as T} from '@/lib/hris/performance-templates';
import type {State} from '@/lib/hris/model';
type Form={id?:string;title:string;orgId:string;description:string;prompts:T['prompts']};
const select='w-full rounded border bg-white p-2',status:Record<string,string>={draft:'草稿',sealed:'已定版',archived:'已归档'};
export default function Workspace(){const [data,setData]=useState<{records:R[];revision:number}|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Form|null>(null),[archive,setArchive]=useState<R|null>(null),[reason,setReason]=useState(''),[detail,setDetail]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/performance-templates',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),d=await r.json() as {records:R[];revision:number;error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok||!h.ok)throw Error(d.error??c.error??'加载失败');setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}useEffect(()=>{void load();},[]);
 function open(r?:R){setError('');setForm({id:r?.id,title:r?.payload.title??'',orgId:r?.payload.orgId??'',description:r?.payload.description??'',prompts:r?.payload.performancePrompts?.map(p=>({...p}))??[]});}
 async function send(command:unknown){if(!data||busy)return;setError('');setBusy(true);try{const r=await fetch('/api/performance-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??'保存失败');setForm(null);setArchive(null);setNotice('模板版本已保存，既有活动继续使用原快照。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-5xl space-y-5"><Link href="/performance" className="text-link">返回绩效管理</Link><div className="page-head"><div><h1>绩效文本模板</h1><p className="text-sm text-slate-500 mt-2">复用单维目标加权流程，配置自评与管理评价文本项；不会变更评分算法或新增审批角色。</p></div><Button onClick={()=>open()}>新建模板草稿</Button></div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel space-y-3">{data?.records.slice().reverse().map(r=><article key={r.id} className="border rounded p-4 space-y-2"><h2>{r.payload.title} · V{r.payload.version} · {status[r.status]}</h2><p>{core?.orgs.find(o=>o.id===r.payload.orgId)?.name} · 文本项{r.payload.performancePrompts?.length??0}个</p><p>{r.payload.description}</p><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setDetail(r)}>模板内容与历史</Button>{r.status==='draft'&&<><Button variant="outline" disabled={busy} onClick={()=>open(r)}>编辑</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{r.status==='sealed'&&!data.records.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||x.status==='sealed'&&(x.payload.version??0)>(r.payload.version??0)))&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>创建修订草稿</Button>}{r.status!=='archived'&&<Button variant="ghost" disabled={busy} onClick={()=>{setReason('');setArchive(r);}}>归档版本</Button>}</div></article>)}{data&&!data.records.length&&<p>暂无模板，原有无模板绩效周期仍可使用。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>模板草稿</DialogTitle><DialogDescription>文本项按阶段分别填写，每项最多1000字；定版后通过修订新版本调整，最多10项。</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();void send({...form,action:form.id?'edit':'create'});}}><fieldset disabled={busy} className="space-y-4">{error&&<p role="alert">{error}</p>}<label className="field">模板名称<Input required maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field">所属组织<select required disabled={!!form.id} className={select} value={form.orgId} onChange={e=>setForm({...form,orgId:e.target.value})}><option value="">请选择</option>{core?.orgs.filter(o=>o.status==='启用').map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label className="field">描述<textarea maxLength={200} className={select} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{form.prompts.map((p,i)=><div className="rounded border p-3 space-y-2" key={p.id}><label className="field">文本项标题<Input required maxLength={100} value={p.title} onChange={e=>setForm({...form,prompts:form.prompts.map((x,n)=>n===i?{...x,title:e.target.value}:x)})}/></label><label className="field">填写阶段<select className={select} value={p.stage} onChange={e=>setForm({...form,prompts:form.prompts.map((x,n)=>n===i?{...x,stage:e.target.value as 'selfReview'|'evaluation'}:x)})}><option value="selfReview">员工自评</option><option value="evaluation">独立管理评价</option></select></label><label><input type="checkbox" checked={p.required} onChange={e=>setForm({...form,prompts:form.prompts.map((x,n)=>n===i?{...x,required:e.target.checked}:x)})}/> 必填</label><Button type="button" variant="ghost" onClick={()=>setForm({...form,prompts:form.prompts.filter((_,n)=>n!==i)})}>删除文本项</Button></div>)}<Button type="button" variant="outline" disabled={form.prompts.length>=10} onClick={()=>setForm({...form,prompts:[...form.prompts,{id:'p'+crypto.randomUUID().replaceAll('-',''),title:'',stage:'selfReview',required:true}]})}>增加文本项</Button><div><Button>保存草稿</Button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!archive} onOpenChange={v=>!v&&!busy&&setArchive(null)}><DialogContent><DialogHeader><DialogTitle>归档模板版本</DialogTitle><DialogDescription>停止新活动选择此版本，既有活动的模板和历史答案继续保留。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(archive)void send({action:'archive',id:archive.id,reason});}}><label className="field">归档依据<textarea className={select} required minLength={5} maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy}>保存归档</Button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{detail?.payload.title} · V{detail?.payload.version}</DialogTitle><DialogDescription>{detail?.payload.description||'单维目标流程文本模板'}</DialogDescription></DialogHeader>{detail?.payload.performancePrompts?.map(p=><p key={p.id}>{p.stage==='selfReview'?'自评':'管理评价'} · {p.title} · {p.required?'必填':'选填'}</p>)}{detail&&<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/>}</DialogContent></Dialog></main>;
}
