import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,core,grant,hris,get,send,act,expect,request} from './support/foundation-scenario.mjs';
const plans=await import('../app/api/learning-plans/route.ts'),assign=await import('../app/api/learning-assignments/route.ts'),exams=await import('../app/api/learning-exams/route.ts'),tasks=await import('../app/api/learning-exam-tasks/route.ts'),updates=await import('../app/api/learning-content-update/route.ts');
async function cmd(api,command,status=200){const d=await expect(await api.GET());return expect(await api.POST(request('/api/test',{revision:d.revision,command})),status);}
async function update(command,action='preview',status=200,revision){const d=await get();return expect(await updates.POST(request('/api/learning-content-update',{revision:revision??d.revision,action,command,evidence:'合成计划内容版本更新核对'})),status);}
async function fixture(t){const f=await setup();t.after(()=>f.sqlite.close());const course=await send({action:'course',code:'UPDATE',title:'原课程',description:'内容更新追溯',content:'完成合成业务实践后由独立人员核验，保留原始完成证据。'});await send({action:'publishCourse',id:course.id});const config={mode:'relative',durationDays:30,allowOverdue:false,orderedStages:false,progressSync:false},definition=await cmd(plans,{action:'create',title:'内容更新合成计划',orgId:f.org.id,courseIds:[course.id],config});await cmd(plans,{action:'seal',id:definition.id});await cmd(assign,{action:'assign',definitionId:definition.id,employeeId:f.e.id});let rows=(await get()).records;const instance=rows.find(r=>r.kind==='learningAssignment'),enrollment=rows.find(r=>r.kind==='enrollment');const exam=await cmd(exams,{action:'create',title:'新增独立考试',orgId:f.org.id,questions:[{prompt:'合成业务应如何处理',options:['独立核验','自行审批'],correct:0}],passingScore:80,maxAttempts:2});await cmd(exams,{action:'seal',id:exam.id});const next=await cmd(plans,{action:'revise',id:definition.id});await cmd(plans,{action:'edit',id:next.id,title:'追加考试的计划',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],config});await cmd(plans,{action:'grading',id:next.id,rule:{mode:'allHighest',attempts:'all',decimals:2}});await cmd(plans,{action:'seal',id:next.id});return {...f,course,config,definition,instance,enrollment,exam,next,command:{assignmentId:instance.id,definitionId:next.id}};}
test('content update preview is read-only; application retains evidence, rejects stale/duplicate writes, rolls back atomically and completes added exam',async t=>{
 const f=await fixture(t);act('employee');await send({action:'submitLearning',id:f.enrollment.id,evidence:'合成原课程实践成果已完成'});act('hr');await send({action:'verifyLearning',id:f.enrollment.id,accepted:true,evidence:'独立核验原课程成果符合要求'});
 const before=await get(),original=before.records.find(r=>r.id===f.enrollment.id),events=f.sqlite.prepare('SELECT count(*) AS n FROM hris_development_events').get().n;
 const p=await update(f.command);assert.equal(p.preview.canApply,true);assert.equal(p.preview.retained.length,1);assert.equal(p.preview.added.length,1);assert.equal(p.preview.beforeProgress.complete,true);assert.equal(p.preview.afterProgress.complete,false);assert.equal((await get()).revision,before.revision);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM hris_development_events').get().n,events);assert.ok(!('projected' in p.preview));
 await update(f.command,'apply',409,before.revision-1);
 f.sqlite.exec("CREATE TRIGGER content_update_fail BEFORE INSERT ON hris_development_events BEGIN SELECT RAISE(ABORT,'synthetic content update audit failure'); END");await update(f.command,'apply',503);f.sqlite.exec('DROP TRIGGER content_update_fail');assert.equal((await get()).revision,before.revision);assert.equal((await get()).records.length,before.records.length);
 const applied=await update(f.command,'apply');assert.equal(applied.ids.length,2);let rows=(await get()).records,current=rows.find(r=>r.id===f.instance.id),task=rows.find(r=>r.kind==='learningExamTask');assert.equal(current.referenceId,f.next.id);assert.equal(current.payload.contentUpdateFromId,f.definition.id);assert.deepEqual(rows.find(r=>r.id===f.enrollment.id),original);assert.equal(current.payload.start,f.instance.payload.start);assert.equal(current.payload.due,f.instance.payload.due);assert.equal(rows.filter(r=>r.kind==='learningCredit').length,0);await update(f.command,'apply',400);await cmd(assign,{action:'assign',definitionId:f.definition.id,employeeId:f.e.id},400);
 act('employee');await cmd(tasks,{action:'submit',id:task.id,answers:[0]});act('hr');await cmd(assign,{action:'closeAssignment',id:f.instance.id});assert.equal((await get()).records.find(r=>r.id===f.instance.id).status,'completed');
 const history=f.sqlite.prepare('SELECT snapshot FROM hris_development_events WHERE record_id=?').all(f.instance.id).map(x=>JSON.parse(x.snapshot));assert.ok(history.some(r=>r.referenceId===f.definition.id));assert.ok(history.some(r=>r.referenceId===f.next.id));
});
test('content update rejects scope leaks and preserves completed/cancelled/version-conflicting instances',async t=>{
 const f=await fixture(t);act('employee');await expect(await updates.POST(request('/api/learning-content-update',{revision:(await get()).revision,action:'preview',command:f.command})),403);act('manager');await expect(await updates.POST(request('/api/learning-content-update',{revision:(await get()).revision,action:'preview',command:f.command})),403);act('hr');
 await cmd(assign,{action:'cancelAssignment',id:f.instance.id,evidence:'合成暂停实例更新'});assert.equal((await update(f.command)).preview.canApply,false);await update(f.command,'apply',400);await cmd(assign,{action:'restoreAssignment',id:f.instance.id,evidence:'合成恢复原任务后检查'});
 await cmd(assign,{action:'assign',definitionId:f.next.id,employeeId:f.e.id});assert.ok((await update(f.command)).preview.blockers.some(s=>s.includes('已有目标版本')));await update(f.command,'apply',400);
 const {previewLearningContentUpdate}=await import('../lib/hris/learning-content-update.ts');const {developmentContext}=await import('../lib/hris/development-repository.ts');const ctx=await developmentContext(['learningAssignment','learningDefinition','enrollment','course','learningExamDefinition','learningExamTask'],['admin','hr']);const base=ctx.records.filter(r=>!(r.kind==='learningAssignment'&&r.id!==f.instance.id));
 for(const [changed,text] of [[{...f.instance,status:'completed'},'已结项'],[{...f.instance,payload:{...f.instance.payload,due:'2020-01-01'}},'已到期']])assert.ok(previewLearningContentUpdate(base.map(r=>r.id===changed.id?changed:r),ctx.state,ctx.member,f.command).blockers.some(s=>s.includes(text)));
 const target=base.find(r=>r.id===f.next.id);const removed={...target,payload:{...target.payload,courseIds:[],learningRequirements:target.payload.learningRequirements.filter(r=>r.kind==='exam')}};assert.ok(previewLearningContentUpdate(base.map(r=>r.id===removed.id?removed:r),ctx.state,ctx.member,f.command).blockers.some(s=>s.includes('移除')));
 const other={...target,payload:{...target.payload,orgId:f.otherOrg.id}};assert.throws(()=>previewLearningContentUpdate(base.map(r=>r.id===other.id?other:r),ctx.state,ctx.member,f.command),/管理权限/);
 const exited={...ctx.state,employees:ctx.state.employees.map(e=>e.id===f.e.id?{...e,status:'离职'}:e)};assert.equal(previewLearningContentUpdate(base,exited,ctx.member,f.command).canApply,false);
});


test('content update binds new course and homework with an independent reviewer and keeps all original deadlines',async t=>{
 const f=await fixture(t);act('owner');await core({action:'employee',code:'U-REVIEW',name:'合成内容更新批阅人',orgId:f.org.id,job:'批阅人',level:'',joined:'2026-01-01',email:''});const reviewer=(await expect(await hris.GET())).state.employees.find(e=>e.code==='U-REVIEW');await grant('updateReviewer','employee',reviewer.id);
 const homework=await import('../app/api/learning-homework/route.ts'),description='使用合成资料完成业务实践并说明判断依据，本任务必须由独立批阅人核验。';
 const hw=(await cmd(homework,{action:'create',title:'内容更新新增作业',orgId:f.org.id,content:description,maxSubmissions:2})).ids[0];await cmd(homework,{action:'seal',id:hw});const course=await send({action:'course',code:'UPDATE-NEW',title:'内容更新新增课程',description:'追加课程要求',content:description});await send({action:'publishCourse',id:course.id});
 const next=await cmd(plans,{action:'revise',id:f.next.id});await cmd(plans,{action:'edit',id:next.id,title:'追加三类内容',orgId:f.org.id,courseIds:[f.course.id,course.id],examIds:[f.exam.id],homeworkIds:[hw],config:f.config});await cmd(plans,{action:'seal',id:next.id});const command={assignmentId:f.instance.id,definitionId:next.id};
 assert.equal((await update(command)).preview.canApply,false);await update({...command,homeworkReviewers:{[hw]:f.e.id}},'apply',400);const valid={...command,homeworkReviewers:{[hw]:reviewer.id}};assert.equal((await update(valid)).preview.canApply,true);const applied=await update(valid,'apply');assert.equal(applied.ids.length,4);
 let rows=(await get()).records,newTasks=rows.filter(r=>r.payload.learningAssignmentId===f.instance.id);assert.equal(newTasks.length,4);assert.ok(newTasks.every(r=>r.payload.due===f.instance.payload.due));const hwTask=newTasks.find(r=>r.kind==='homeworkTask');assert.equal(hwTask.payload.reviewerEmployeeId,reviewer.id);assert.equal(newTasks.find(r=>r.referenceId===course.id).status,'active');
 act('employee');await cmd(homework,{action:'submit',id:hwTask.id,content:description});let submission=(await expect(await homework.GET())).records.find(r=>r.kind==='homeworkSubmission');act('updateReviewer');await cmd(homework,{action:'review',id:hwTask.id,submissionId:submission.id,accepted:true,score:88,evidence:'独立核验新增作业符合要求'});act('hr');await cmd(assign,{action:'closeAssignment',id:f.instance.id},400);assert.equal((await get()).records.find(r=>r.id===hwTask.id).status,'completed');
});
