import './support/runtime.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
const {learningGrade}=await import('../lib/hris/learning-grades.ts');
test('plan grading distinguishes two averages, retains zero, and never borrows other-instance attempts or replaces missing scores',()=>{
 const assignment={id:'plan',employeeId:'e',status:'active',payload:{courseIds:[],examIds:['a','b'],gradeRule:{mode:'allAttemptsAverage',attempts:'all',decimals:2}}};
 const tasks=['a','b'].map(id=>({id:'task-'+id,kind:'learningExamTask',employeeId:'e',referenceId:id,payload:{learningAssignmentId:'plan',learningRequirementId:'exam:'+id}}));
 const attempt=(id,exam,score,passed)=>({id,kind:'learningExamAttempt',employeeId:'e',referenceId:'task-'+exam,payload:{examId:exam,score,passed}});
 const records=[...tasks,attempt('a1','a',0,false),attempt('a2','a',80,true),attempt('b1','b',60,false)];
 assert.equal(learningGrade(assignment,records).score,46.67);
 const rule=mode=>({...assignment,payload:{...assignment.payload,gradeRule:{...assignment.payload.gradeRule,mode}}});
 assert.equal(learningGrade(rule('eachExamHighestAverage'),records).score,70);
 assert.equal(learningGrade(rule('allHighest'),records).score,80);
 assert.equal(learningGrade({...assignment,payload:{...assignment.payload,gradeRule:{mode:'specifiedExamHighest',examId:'b',attempts:'all',decimals:0}}},records).score,60);
 assert.equal(learningGrade({...assignment,payload:{...assignment.payload,gradeRule:{mode:'allHighest',attempts:'passed',decimals:2}}},records).state,'pending');
 assert.equal(learningGrade(assignment,records.filter(r=>r.id!=='b1')).score,null);
 assert.equal(learningGrade(assignment,records.map(r=>r.id==='b1'?{...r,referenceId:'other-task'}:r)).score,null);
 assert.equal(learningGrade(assignment,records.map(r=>r.id==='b1'?{...r,employeeId:'other'}:r)).score,null);
 const single={...assignment,payload:{...assignment.payload,examIds:['a']}};assert.equal(learningGrade(single,[tasks[0],records[2]]).score,0);
 assert.equal(learningGrade({...assignment,status:'completed'},records).state,'final');assert.equal(learningGrade(assignment,records).state,'provisional');
 assert.equal(learningGrade({...assignment,payload:{...assignment.payload,gradeRule:{mode:'none'}}},records).state,'not_configured');
});
