import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {database,act,request} from './support/runtime.mjs';
const access=await import('../app/api/access/route.ts'),hris=await import('../app/api/hris/route.ts'),members=await import('../app/api/members/route.ts'),dev=await import('../app/api/development/route.ts'),files=await import('../app/api/attachments/route.ts');
async function expect(r,status=200){assert.equal(r.status,status,await r.clone().text());return r.json();}
async function get(){return expect(await dev.GET());}
async function send(command,status=200,revision){const d=await get();return expect(await dev.POST(request('/api/development',{revision:revision??d.revision,command})),status);}
async function core(command){const d=await expect(await hris.GET());return expect(await hris.POST(request('/api/hris',{revision:d.revision,command})));}
async function grant(id,role,employeeId,orgScope=[],existing=false){act('owner');const d=await expect(await members.GET());await expect(await members.POST(request('/api/members',{revision:d.revision,email:id+'@example.com',name:id,role,employeeId,orgScope,viewEmail:false,viewLevel:false,active:true})));act(id);if(!existing)await expect(await access.POST(request('/api/access',{action:'activate'})));act('owner');}
async function setup(){const {db,sqlite}=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));globalThis.p2env.DB=db;act('owner');await expect(await access.POST(request('/api/access',{action:'setup',name:'人才学习测试企业'})));await core({action:'org',name:'研发',parentId:'',city:'上海',leader:'',status:'启用'});await core({action:'org',name:'财务',parentId:'',city:'北京',leader:'',status:'启用'});let state=(await expect(await hris.GET())).state;const org=state.orgs[0],otherOrg=state.orgs[1];await core({action:'position',code:'DEV',name:'工程师',orgId:org.id,family:'技术',responsibilities:'开发验证',status:'启用'});for(const [code,orgId]of[['A',org.id],['B',otherOrg.id]])await core({action:'employee',code,name:'合成员工'+code,orgId,job:'工程师',level:'',joined:'2026-01-01',email:''});state=(await expect(await hris.GET())).state;const e=state.employees.find(e=>e.code==='A'),other=state.employees.find(e=>e.code==='B');await grant('employee','employee',e.id);await grant('manager','manager',null,[org.id]);await grant('hr','hr',null,[org.id]);await grant('approver','approver',null,[org.id]);return {db,sqlite,e,other,org,otherOrg,position:state.positions[0]};}
const anchors=['能在指导下完成基础任务','能够独立处理常规工作任务','能够独立解决复杂业务问题','能够指导团队完善工作方法','能够建立组织级标准并推广'];
const due='2099-12-31';
test('P3：标准版本、绩效更正、盘点快照、跨组织与本人评价隔离',async()=>{
 const {sqlite,e,other,position}=await setup();const s1=await send({action:'standard',code:'C1',name:'问题解决',anchors});const s2=await send({action:'standard',code:'C1',name:'问题解决新版',anchors:anchors.map(a=>a+'，并提供证据')});let d=await get();assert.equal(d.records.find(r=>r.id===s1.id).payload.version,1);assert.equal(d.records.find(r=>r.id===s2.id).payload.version,2);
 await send({action:'requirement',positionId:position.id,standardId:s1.id,target:3});await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:2,evidence:'独立完成两次常规任务，并提交复盘',assessedOn:'2026-01-01'});
 const perf=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'历史考核文件编号 PERF-001',originalRating:'B',band:2,reason:'依据已批准的历史档位对照表'});
 await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'重复来源记录',originalRating:'A',band:3,reason:'重复导入不得覆盖'},400);
 const review=await send({action:'review',employeeId:e.id,period:'2026-H1',performanceId:perf.id,potential:null,evidence:'潜力评估尚未完成，需要补充访谈'});await send({action:'publishReview',id:review.id});await send({action:'publishReview',id:review.id},400);
 const corrected=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'复核签字文件编号 PERF-002',originalRating:'A',band:3,reason:'原文件导入错误，经复核更正',supersedes:perf.id});d=await get();assert.equal(d.records.find(r=>r.id===review.id).payload.performanceSnapshot.band,2);assert.equal(d.records.find(r=>r.id===corrected.id).payload.band,3);assert.equal(d.records.find(r=>r.id===review.id).payload.potential,null);
 act('hr');await send({action:'assessment',employeeId:other.id,standardId:s1.id,rating:3,evidence:'越权评估不得保存',assessedOn:'2026-01-01'},403);
 act('employee');d=await get();assert.ok(d.records.some(r=>r.kind==='assessment'));assert.ok(!d.records.some(r=>['performance','review','succession'].includes(r.kind)));await send({action:'standard',code:'hack',name:'越权标准',anchors},403);
 act('approver');assert.ok(!(await get()).records.some(r=>['performance','assessment','review'].includes(r.kind)));await expect(await dev.GET(request('/api/development?id='+review.id)),403);
 act('owner');await grant('employee','manager',e.id,[position.orgId],true);act('employee');await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:5,evidence:'经理不能评价本人正式能力',assessedOn:'2026-01-01'},403);
 sqlite.close();
});
test('P3：发展计划—课程—学习成果—独立核验闭环与重复处理保护',async()=>{
 const {sqlite,e,position}=await setup();const standard=await send({action:'standard',code:'C1',name:'质量改进',anchors});const plan=await send({action:'plan',employeeId:e.id,standardId:standard.id,target:3,title:'质量实践提升',actionPlan:'完成案例学习和实践改进，由经理核验成果',due});const course=await send({action:'course',code:'L1',title:'质量案例实践',description:'通过真实案例理解问题根因分析方法',content:'学习五个完整案例，记录根因分析，并提交一个实际改善方案供经理核验。',standardId:standard.id});
 act('employee');assert.ok(!(await get()).records.some(r=>r.id===course.id));await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due},403);act('owner');await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due});await send({action:'enroll',employeeId:e.id,courseId:course.id,due},400);
 const succession=await send({action:'succession',employeeId:e.id,positionId:position.id,readiness:'one_year',evidence:'具备基础专业能力，尚需承担团队项目'});assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).job,'工程师');await send({action:'closeSuccession',id:succession.id,reason:'岗位计划调整，保留提名历史'});
 act('employee');await send({action:'submitPlan',id:plan.id,evidence:'已完成案例分析和改进方案文档'});await send({action:'submitPlan',id:plan.id,evidence:'重复提交不应再次写入'},400);await send({action:'submitLearning',id:enrollment.id,evidence:'完成五个案例并提供实践报告编号001'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'本人不能核验本人提交'},403);
 act('manager');await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'先检查关联学习是否完成'},400);await send({action:'verifyLearning',id:enrollment.id,accepted:false,evidence:'缺少实践结果，请补充改进前后对比'});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'已补充改进前后数据和经理访谈记录'});act('manager');await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实实践材料，达到课程完成要求'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'重复核验不应再次通过'},400);await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'完成全部学习任务及发展行动验收'});let d=await get();assert.equal(d.records.find(r=>r.id===plan.id).status,'completed');assert.equal(d.records.find(r=>r.id===enrollment.id).payload.verifiedBy,'manager');const process=await expect(await dev.GET(request('/api/development?id='+enrollment.id)));assert.equal(process.items.length,5);assert.ok(process.items.some(x=>x.snapshot.payload.evidence==='完成五个案例并提供实践报告编号001'));assert.ok(process.items.some(x=>x.snapshot.payload.verification==='缺少实践结果，请补充改进前后对比'));
 act('owner');const rev=(await get()).revision;await send({action:'standard',code:'C2',name:'新能力',anchors});await send({action:'standard',code:'C3',name:'过期修改',anchors},409,rev);assert.ok(!(await get()).records.some(r=>r.payload.code==='C3'));
 const before=sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision;sqlite.exec("CREATE TRIGGER fail_development_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await send({action:'standard',code:'C4',name:'审计失败回滚',anchors},503);assert.equal(sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision,before);assert.ok(!(await get()).records.some(r=>r.payload.code==='C4'));sqlite.close();
});
function mockBucket(){const objects=new Map();globalThis.p2env.BUCKET={put:async(k,b)=>{objects.set(k,new Uint8Array(b));},get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async k=>{objects.delete(k);}};return objects;}
async function upload(employeeId,body='%PDF-test',revision,extra={}){revision??=(await get()).revision;return files.POST(new Request('https://hris.example/api/attachments?'+new URLSearchParams({employeeId,revision:String(revision),name:'材料.pdf',...extra}),{method:'POST',headers:{Origin:'https://hris.example','Content-Type':'application/pdf'},body}));}
test('P3 附件：受权下载、类型与大小验证、并发清理、删除及数据库失败回滚',async()=>{
 const {sqlite,e,other}=await setup(),objects=mockBucket();const f=await expect(await upload(e.id,'%PDF-test',undefined,{visibility:'employee'}));assert.equal(objects.size,1);let list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(list.items.length,1);assert.equal(list.items[0].objectKey,undefined);
 act('employee');let response=await files.GET(request('/api/attachments?id='+f.id));assert.equal(response.status,200);assert.equal(await response.text(),'%PDF-test');assert.equal(response.headers.get('x-content-type-options'),'nosniff');await expect(await files.GET(request('/api/attachments?employeeId='+other.id)),403);await expect(await upload(e.id),403);
 act('owner');await expect(await upload(e.id,'not a pdf'),415);await expect(await upload(e.id,'%PDF-test',undefined,{name:'../file.pdf'}),400);await expect(await upload(e.id,new Uint8Array(10*1024*1024+1)),413);assert.equal(objects.size,1);
 const before=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_file_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await expect(await upload(e.id),503);assert.equal(objects.size,1);assert.equal((await get()).revision,before);sqlite.exec('DROP TRIGGER fail_file_audit');
 const originalPut=globalThis.p2env.BUCKET.put;globalThis.p2env.BUCKET.put=async(k,b)=>{await originalPut(k,b);sqlite.exec('UPDATE hris_workspaces SET revision=revision+1');};await expect(await upload(e.id),409);assert.equal(objects.size,1);globalThis.p2env.BUCKET.put=originalPut;
 list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));await expect(await files.DELETE(request('/api/attachments',{id:f.id,revision:list.revision})));assert.equal(objects.size,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),404);assert.equal(sqlite.prepare('SELECT count(*) n FROM hris_attachments WHERE deleted_at IS NOT NULL').get().n,1);sqlite.close();
});

test('P3 附件默认保密：员工和审批人不能列出或下载未开放的人事附件',async()=>{
 const {sqlite,e}=await setup();mockBucket();const f=await expect(await upload(e.id));act('employee');const listing=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(listing.items.length,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),403);act('approver');await expect(await files.GET(request('/api/attachments?id='+f.id)),403);sqlite.close();
});
test('P3 考试：答案服务端保密、次数限制、自动评分及成果提交门槛',async()=>{
 const {sqlite,e}=await setup();const course=await send({action:'course',code:'QUIZ',title:'实践考核课程',description:'通过课程练习验证知识理解与应用',content:'阅读完整案例并回答课程测验，完成后提交实践证据，由经理复核学习效果。'});const exam=await send({action:'exam',courseId:course.id,questions:[{prompt:'遇到数据错误时应当如何处理？',options:['记录事实并按流程修正','直接删除全部数据'],correct:0},{prompt:'完成学习后应当提交什么材料？',options:['无需任何记录','真实实践成果和证据'],correct:1}],passingScore:100,maxAttempts:2});await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,due});
 act('employee');let d=await get();const visibleExam=d.records.find(r=>r.id===exam.id);assert.ok(visibleExam);assert.ok(visibleExam.payload.questions.every(q=>!('correct'in q)));const history=await expect(await dev.GET(request('/api/development?id='+exam.id)));assert.ok(history.items[0].snapshot.payload.questions.every(q=>!('correct'in q)));
 await send({action:'submitLearning',id:enrollment.id,evidence:'未通过考试不允许提交成果'},400);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0]},400);const failed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[1,0]});d=await get();assert.equal(d.records.find(r=>r.id===failed.id).payload.score,0);assert.equal(d.records.find(r=>r.id===failed.id).payload.passed,false);
 const passed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]});assert.equal((await get()).records.find(r=>r.id===passed.id).payload.score,100);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},400);await send({action:'submitLearning',id:enrollment.id,evidence:'已通过考试并完成实际案例复盘'});
 act('manager');const managerExam=(await get()).records.find(r=>r.id===exam.id);assert.ok(managerExam.payload.questions.every(q=>!('correct'in q)));await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},403);await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实考试与实践成果，确认完成学习'});assert.equal((await get()).records.find(r=>r.id===enrollment.id).status,'completed');sqlite.close();
});
test('P3 能力差距：同版本比较，缺失与版本不匹配均为未评定',async()=>{
 const {sqlite,e,position}=await setup();await core({action:'employee',...e,positionId:position.id});const first=await send({action:'standard',code:'GAP',name:'实践能力',anchors});await send({action:'requirement',positionId:position.id,standardId:first.id,target:4});let report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].rating,null);assert.equal(report.items[0].gap,null);await send({action:'assessment',employeeId:e.id,standardId:first.id,rating:3,evidence:'已经独立完成复杂案例并有证据',assessedOn:'2026-01-01'});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].gap,1);const next=await send({action:'standard',code:'GAP',name:'实践能力新版',anchors});await send({action:'requirement',positionId:position.id,standardId:next.id,target:5});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,1);assert.equal(report.items[0].standardVersion,2);assert.equal(report.items[0].gap,null);act('approver');report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,0);sqlite.close();
});
test('P3 项目化：盘点范围与期间、人才池隔离、培训报名及未结项保护',async()=>{
 const {sqlite,e,other,org}=await setup();const project=await send({action:'project',name:'年度人才盘点',orgId:org.id,period:'2026-H1',start:'2026-01-01',end:'2026-12-31'});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:null,evidence:'项目未启动不能录入盘点'},400);await send({action:'startProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:other.id,period:'2026-H1',potential:null,evidence:'跨项目组织人员不得纳入盘点'},400);const review=await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:2,evidence:'依据访谈和项目成果形成潜力评定'});await send({action:'closeProject',id:project.id},400);await send({action:'publishReview',id:review.id});await send({action:'closeProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:3,evidence:'结束后不得继续加入记录'},400);
 const pool=await send({action:'pool',name:'技术后备池',orgId:org.id,criteria:'依据技术实践、发展意愿与目标岗位要求入池'});await send({action:'poolMember',poolId:pool.id,employeeId:other.id,evidence:'其他组织不能擅自加入人才池'},400);const membership=await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'具备专业基础并愿意承担复杂项目'});await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'重复加入不能新增重复记录'},400);act('employee');assert.ok(!(await get()).records.some(r=>['project','review','pool','poolMember'].includes(r.kind)));act('owner');await send({action:'removePoolMember',id:membership.id,reason:'发展方向调整，经复核退出人才池'});
 const course=await send({action:'course',code:'TRAIN',title:'培训项目课程',description:'通过培训课程学习规范的实践方法',content:'阅读案例正文，完成培训项目规定的实际任务，并提交可供核实的学习成果。'});await send({action:'publishCourse',id:course.id});const training=await send({action:'training',name:'技术人才训练营',orgId:org.id,period:'2099',start:'2099-01-01',end:due,instructor:'企业内部讲师',courseIds:[course.id]});act('employee');assert.ok(!(await get()).records.some(r=>r.id===training.id));act('owner');await send({action:'publishTraining',id:training.id});act('employee');assert.ok((await get()).records.some(r=>r.id===training.id));const enrollment=await send({action:'enroll',trainingId:training.id,employeeId:e.id,courseId:course.id,due});act('manager');await send({action:'closeTraining',id:training.id},400);await send({action:'cancelEnrollment',id:enrollment.id,reason:'员工工作安排变化，经确认取消本次培训'});await send({action:'closeTraining',id:training.id});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'取消后的任务不能再提交学习成果'},400);sqlite.close();
});
