import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {database,act,request} from './support/runtime.mjs';
const access=await import('../app/api/access/route.ts'),hris=await import('../app/api/hris/route.ts'),members=await import('../app/api/members/route.ts'),dev=await import('../app/api/development/route.ts'),files=await import('../app/api/attachments/route.ts');
async function expect(r,status=200){assert.equal(r.status,status,await r.clone().text());return r.json();}
async function get(){return expect(await dev.GET());}
async function send(command,status=200,revision){const d=await get();return expect(await dev.POST(request('/api/development',{revision:revision??d.revision,command})),status);}
async function core(command){const d=await expect(await hris.GET());return expect(await hris.POST(request('/api/hris',{revision:d.revision,command})));}
async function grant(id,role,employeeId,orgScope=[],existing=false){act('owner');const d=await expect(await members.GET());await expect(await members.POST(request('/api/members',{revision:d.revision,email:id+'@example.com',name:id,role,employeeId,orgScope,viewEmail:false,viewLevel:false,active:true})));act(id);if(!existing)await expect(await access.POST(request('/api/access',{action:'activate'})));act('owner');}
async function setup(){const {db,sqlite}=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));globalThis.p2env.DB=db;act('owner');await expect(await access.POST(request('/api/access',{action:'setup',name:'人才学习测试企业'})));await core({action:'org',name:'研发',parentId:'',city:'上海',leader:'',status:'启用'});await core({action:'org',name:'财务',parentId:'',city:'北京',leader:'',status:'启用'});let state=(await expect(await hris.GET())).state;const org=state.orgs[0],otherOrg=state.orgs[1];await core({action:'position',code:'DEV',name:'工程师',orgId:org.id,family:'技术',responsibilities:'开发验证',status:'启用'});for(const [code,orgId]of[['A',org.id],['B',otherOrg.id]])await core({action:'employee',code,name:'合成员工'+code,orgId,job:'工程师',level:'',joined:'2026-01-01',email:''});state=(await expect(await hris.GET())).state;const e=state.employees.find(e=>e.code==='A'),other=state.employees.find(e=>e.code==='B');await grant('employee','employee',e.id);await grant('manager','manager',null,[org.id]);await grant('hr','hr',null,[org.id]);await grant('approver','approver',null,[org.id]);return {db,sqlite,e,other,org,otherOrg,position:state.positions[0]};}
const anchors=['能在指导下完成基础任务','能够独立处理常规工作任务','能够独立解决复杂业务问题','能够指导团队完善工作方法','能够建立组织级标准并推广'];
const due='2099-12-31';
test('P3：标准版本、绩效更正、盘点快照、跨组织与本人评价隔离',async()=>{
 const {sqlite,e,other,position}=await setup();const s1=await send({action:'standard',code:'C1',name:'问题解决',anchors});const s2=await send({action:'standard',code:'C1',name:'问题解决新版',anchors:anchors.map(a=>a+'，并提供证据')});let d=await get();assert.equal(d.records.find(r=>r.id===s1.id).payload.version,1);assert.equal(d.records.find(r=>r.id===s2.id).payload.version,2);
 await send({action:'requirement',positionId:position.id,standardId:s1.id,target:3});await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:2,evidence:'独立完成两次常规任务，并提交复盘',assessedOn:'2026-01-01'});
 const perf=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'历史考核文件编号 PERF-001',originalRating:'B',band:2,reason:'依据已批准的历史档位对照表'});
 await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'重复来源记录',originalRating:'A',band:3,reason:'重复导入不得覆盖'},400);
 const review=await send({action:'review',employeeId:e.id,period:'2026-H1',performanceId:perf.id,potential:null,evidence:'潜力评估尚未完成，需要补充访谈'});await send({action:'publishReview',id:review.id});await send({action:'publishReview',id:review.id},400);
 const corrected=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'复核签字文件编号 PERF-002',originalRating:'A',band:3,reason:'原文件导入错误，经复核更正',supersedes:perf.id});d=await get();assert.equal(d.records.find(r=>r.id===review.id).payload.performanceSnapshot.band,2);assert.equal(d.records.find(r=>r.id===corrected.id).payload.band,3);assert.equal(d.records.find(r=>r.id===review.id).payload.potential,null);
 act('hr');await send({action:'assessment',employeeId:other.id,standardId:s1.id,rating:3,evidence:'越权评估不得保存',assessedOn:'2026-01-01'},403);
 act('employee');d=await get();assert.ok(d.records.some(r=>r.kind==='assessment'));assert.ok(!d.records.some(r=>['performance','review','succession'].includes(r.kind)));await send({action:'standard',code:'hack',name:'越权标准',anchors},403);
 act('approver');assert.ok(!(await get()).records.some(r=>['performance','assessment','review'].includes(r.kind)));await expect(await dev.GET(request('/api/development?id='+review.id)),403);
 act('owner');await grant('employee','manager',e.id,[position.orgId],true);act('employee');await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:5,evidence:'经理不能评价本人正式能力',assessedOn:'2026-01-01'},403);
 sqlite.close();
});
test('P3：发展计划—课程—学习成果—独立核验闭环与重复处理保护',async()=>{
 const {sqlite,e,position}=await setup();const standard=await send({action:'standard',code:'C1',name:'质量改进',anchors});const plan=await send({action:'plan',employeeId:e.id,standardId:standard.id,target:3,title:'质量实践提升',actionPlan:'完成案例学习和实践改进，由经理核验成果',due});const course=await send({action:'course',code:'L1',title:'质量案例实践',description:'通过真实案例理解问题根因分析方法',content:'学习五个完整案例，记录根因分析，并提交一个实际改善方案供经理核验。',standardId:standard.id});
 act('employee');assert.ok(!(await get()).records.some(r=>r.id===course.id));await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due},403);act('owner');await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due});await send({action:'enroll',employeeId:e.id,courseId:course.id,due},400);
 const succession=await send({action:'succession',employeeId:e.id,positionId:position.id,readiness:'one_year',evidence:'具备基础专业能力，尚需承担团队项目'});assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).job,'工程师');await send({action:'closeSuccession',id:succession.id,reason:'岗位计划调整，保留提名历史'});
 act('employee');await send({action:'submitPlan',id:plan.id,evidence:'已完成案例分析和改进方案文档'});await send({action:'submitPlan',id:plan.id,evidence:'重复提交不应再次写入'},400);await send({action:'submitLearning',id:enrollment.id,evidence:'完成五个案例并提供实践报告编号001'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'本人不能核验本人提交'},403);
 act('manager');await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'先检查关联学习是否完成'},400);await send({action:'verifyLearning',id:enrollment.id,accepted:false,evidence:'缺少实践结果，请补充改进前后对比'});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'已补充改进前后数据和经理访谈记录'});act('manager');await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实实践材料，达到课程完成要求'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'重复核验不应再次通过'},400);await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'完成全部学习任务及发展行动验收'});let d=await get();assert.equal(d.records.find(r=>r.id===plan.id).status,'completed');assert.equal(d.records.find(r=>r.id===enrollment.id).payload.verifiedBy,'manager');const process=await expect(await dev.GET(request('/api/development?id='+enrollment.id)));assert.equal(process.items.length,5);assert.ok(process.items.some(x=>x.snapshot.payload.evidence==='完成五个案例并提供实践报告编号001'));assert.ok(process.items.some(x=>x.snapshot.payload.verification==='缺少实践结果，请补充改进前后对比'));
 act('owner');const rev=(await get()).revision;await send({action:'standard',code:'C2',name:'新能力',anchors});await send({action:'standard',code:'C3',name:'过期修改',anchors},409,rev);assert.ok(!(await get()).records.some(r=>r.payload.code==='C3'));
 const before=sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision;sqlite.exec("CREATE TRIGGER fail_development_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await send({action:'standard',code:'C4',name:'审计失败回滚',anchors},503);assert.equal(sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision,before);assert.ok(!(await get()).records.some(r=>r.payload.code==='C4'));sqlite.close();
});
function mockBucket(){const objects=new Map();globalThis.p2env.BUCKET={put:async(k,b)=>{objects.set(k,new Uint8Array(b));},get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async k=>{objects.delete(k);}};return objects;}
async function upload(employeeId,body='%PDF-test',revision,extra={}){revision??=(await get()).revision;return files.POST(new Request('https://hris.example/api/attachments?'+new URLSearchParams({employeeId,revision:String(revision),name:'材料.pdf',...extra}),{method:'POST',headers:{Origin:'https://hris.example','Content-Type':'application/pdf'},body}));}
test('P3 附件：受权下载、类型与大小验证、并发清理、删除及数据库失败回滚',async()=>{
 const {sqlite,e,other}=await setup(),objects=mockBucket();const f=await expect(await upload(e.id,'%PDF-test',undefined,{visibility:'employee'}));assert.equal(objects.size,1);let list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(list.items.length,1);assert.equal(list.items[0].objectKey,undefined);
 act('employee');let response=await files.GET(request('/api/attachments?id='+f.id));assert.equal(response.status,200);assert.equal(await response.text(),'%PDF-test');assert.equal(response.headers.get('x-content-type-options'),'nosniff');await expect(await files.GET(request('/api/attachments?employeeId='+other.id)),403);await expect(await upload(e.id),403);
 act('owner');await expect(await upload(e.id,'not a pdf'),415);await expect(await upload(e.id,'%PDF-test',undefined,{name:'../file.pdf'}),400);await expect(await upload(e.id,new Uint8Array(10*1024*1024+1)),413);assert.equal(objects.size,1);
 const before=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_file_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await expect(await upload(e.id),503);assert.equal(objects.size,1);assert.equal((await get()).revision,before);sqlite.exec('DROP TRIGGER fail_file_audit');
 const originalPut=globalThis.p2env.BUCKET.put;globalThis.p2env.BUCKET.put=async(k,b)=>{await originalPut(k,b);sqlite.exec('UPDATE hris_workspaces SET revision=revision+1');};await expect(await upload(e.id),409);assert.equal(objects.size,1);globalThis.p2env.BUCKET.put=originalPut;
 list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));await expect(await files.DELETE(request('/api/attachments',{id:f.id,revision:list.revision})));assert.equal(objects.size,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),404);assert.equal(sqlite.prepare('SELECT count(*) n FROM hris_attachments WHERE deleted_at IS NOT NULL').get().n,1);sqlite.close();
});

test('P3 附件默认保密：员工和审批人不能列出或下载未开放的人事附件',async()=>{
 const {sqlite,e}=await setup();mockBucket();const f=await expect(await upload(e.id));act('employee');const listing=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(listing.items.length,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),403);act('approver');await expect(await files.GET(request('/api/attachments?id='+f.id)),403);sqlite.close();
});
test('P3 考试：答案服务端保密、次数限制、自动评分及成果提交门槛',async()=>{
 const {sqlite,e}=await setup();const course=await send({action:'course',code:'QUIZ',title:'实践考核课程',description:'通过课程练习验证知识理解与应用',content:'阅读完整案例并回答课程测验，完成后提交实践证据，由经理复核学习效果。'});const exam=await send({action:'exam',courseId:course.id,questions:[{prompt:'遇到数据错误时应当如何处理？',options:['记录事实并按流程修正','直接删除全部数据'],correct:0},{prompt:'完成学习后应当提交什么材料？',options:['无需任何记录','真实实践成果和证据'],correct:1}],passingScore:100,maxAttempts:2});await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,due});
 act('employee');let d=await get();const visibleExam=d.records.find(r=>r.id===exam.id);assert.ok(visibleExam);assert.ok(visibleExam.payload.questions.every(q=>!('correct'in q)));const history=await expect(await dev.GET(request('/api/development?id='+exam.id)));assert.ok(history.items[0].snapshot.payload.questions.every(q=>!('correct'in q)));
 await send({action:'submitLearning',id:enrollment.id,evidence:'未通过考试不允许提交成果'},400);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0]},400);const failed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[1,0]});d=await get();assert.equal(d.records.find(r=>r.id===failed.id).payload.score,0);assert.equal(d.records.find(r=>r.id===failed.id).payload.passed,false);
 const passed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]});assert.equal((await get()).records.find(r=>r.id===passed.id).payload.score,100);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},400);await send({action:'submitLearning',id:enrollment.id,evidence:'已通过考试并完成实际案例复盘'});
 act('manager');const managerExam=(await get()).records.find(r=>r.id===exam.id);assert.ok(managerExam.payload.questions.every(q=>!('correct'in q)));await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},403);await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实考试与实践成果，确认完成学习'});assert.equal((await get()).records.find(r=>r.id===enrollment.id).status,'completed');sqlite.close();
});
test('P3 能力差距：同版本比较，缺失与版本不匹配均为未评定',async()=>{
 const {sqlite,e,position}=await setup();await core({action:'employee',...e,positionId:position.id});const first=await send({action:'standard',code:'GAP',name:'实践能力',anchors});await send({action:'requirement',positionId:position.id,standardId:first.id,target:4});let report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].rating,null);assert.equal(report.items[0].gap,null);await send({action:'assessment',employeeId:e.id,standardId:first.id,rating:3,evidence:'已经独立完成复杂案例并有证据',assessedOn:'2026-01-01'});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].gap,1);const next=await send({action:'standard',code:'GAP',name:'实践能力新版',anchors});await send({action:'requirement',positionId:position.id,standardId:next.id,target:5});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,1);assert.equal(report.items[0].standardVersion,2);assert.equal(report.items[0].gap,null);act('approver');report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,0);sqlite.close();
});
test('P3 项目化：盘点范围与期间、人才池隔离、培训报名及未结项保护',async()=>{
 const {sqlite,e,other,org}=await setup();const project=await send({action:'project',name:'年度人才盘点',orgId:org.id,period:'2026-H1',start:'2026-01-01',end:'2026-12-31'});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:null,evidence:'项目未启动不能录入盘点'},400);await send({action:'startProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:other.id,period:'2026-H1',potential:null,evidence:'跨项目组织人员不得纳入盘点'},400);const review=await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:2,evidence:'依据访谈和项目成果形成潜力评定'});await send({action:'closeProject',id:project.id},400);await send({action:'publishReview',id:review.id});await send({action:'closeProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:3,evidence:'结束后不得继续加入记录'},400);
 const pool=await send({action:'pool',name:'技术后备池',orgId:org.id,criteria:'依据技术实践、发展意愿与目标岗位要求入池'});await send({action:'poolMember',poolId:pool.id,employeeId:other.id,evidence:'其他组织不能擅自加入人才池'},400);const membership=await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'具备专业基础并愿意承担复杂项目'});await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'重复加入不能新增重复记录'},400);act('employee');assert.ok(!(await get()).records.some(r=>['project','review','pool','poolMember'].includes(r.kind)));act('owner');await send({action:'removePoolMember',id:membership.id,reason:'发展方向调整，经复核退出人才池'});
 const course=await send({action:'course',code:'TRAIN',title:'培训项目课程',description:'通过培训课程学习规范的实践方法',content:'阅读案例正文，完成培训项目规定的实际任务，并提交可供核实的学习成果。'});await send({action:'publishCourse',id:course.id});const training=await send({action:'training',name:'技术人才训练营',orgId:org.id,period:'2099',start:'2099-01-01',end:due,instructor:'企业内部讲师',courseIds:[course.id]});act('employee');assert.ok(!(await get()).records.some(r=>r.id===training.id));act('owner');await send({action:'publishTraining',id:training.id});act('employee');assert.ok((await get()).records.some(r=>r.id===training.id));const enrollment=await send({action:'enroll',trainingId:training.id,employeeId:e.id,courseId:course.id,due});act('manager');await send({action:'closeTraining',id:training.id},400);await send({action:'cancelEnrollment',id:enrollment.id,reason:'员工工作安排变化，经确认取消本次培训'});await send({action:'closeTraining',id:training.id});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'取消后的任务不能再提交学习成果'},400);sqlite.close();
});
const performance=await import('../app/api/performance/route.ts');
async function perf(command,status=200){const d=await get();return expect(await performance.POST(request('/api/performance',{revision:d.revision,command})),status);}
test('P3 正式绩效：目标确认、自评、独立评价、发布、盘点使用与结项',async()=>{
 const {sqlite,e,other,org}=await setup();const cy=await perf({action:'cycle',name:'2026上半年绩效',orgId:org.id,period:'2026-H1',start:'2026-01-01',end:'2026-06-30',lowCut:60,highCut:80,lowLabel:'待改进',midLabel:'达成',highLabel:'优秀'});act('employee');assert.ok(!(await expect(await performance.GET())).records.some(r=>r.id===cy.id));act('owner');await perf({action:'startCycle',id:cy.id});const goals=[{title:'交付质量',metric:'按验收标准完成项目且无严重缺陷',weight:60},{title:'团队协作',metric:'完成评审与知识分享并留存记录',weight:40}];await perf({action:'goals',employeeId:other.id,cycleId:cy.id,goals},400);
 act('employee');await perf({action:'goals',employeeId:e.id,cycleId:cy.id,goals:[{...goals[0],weight:90}]},400);const plan=await perf({action:'goals',employeeId:e.id,cycleId:cy.id,goals});await perf({action:'confirmGoals',id:plan.id},403);await perf({action:'selfReview',id:plan.id,evidence:'目标尚未确认不能提交自评'},400);act('manager');await perf({action:'confirmGoals',id:plan.id});act('employee');await perf({action:'goals',id:plan.id,employeeId:e.id,cycleId:cy.id,goals},400);await perf({action:'selfReview',id:plan.id,evidence:'交付项目均已完成验收，同时组织三次分享'});act('manager');await perf({action:'evaluate',id:plan.id,scores:[90,70],evidence:'验收结果和评审记录支持相应目标评分'});let d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===plan.id).payload.score,82);
 act('employee');d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===plan.id).payload.score,undefined);assert.equal(d.records.find(r=>r.id===plan.id).payload.evaluation,undefined);const hist=await expect(await dev.GET(request('/api/development?id='+plan.id)));assert.ok(hist.items.every(x=>x.snapshot.payload.score===undefined));await perf({action:'publishPerformance',id:plan.id,evidence:'员工不能自行发布绩效'},403);
 act('owner');await perf({action:'closeCycle',id:cy.id},400);const result=await perf({action:'publishPerformance',id:plan.id,evidence:'已核对目标、自评及管理评价，确认发布'});await perf({action:'publishPerformance',id:plan.id,evidence:'重复发布不得生成第二份结果'},400);await perf({action:'returnPerformance',id:plan.id,evidence:'发布后不能通过退回改写原始评价'},400);let records=(await get()).records;const final=records.find(r=>r.id===result.id);assert.equal(final.payload.score,82);assert.equal(final.payload.originalRating,'优秀');assert.equal(final.payload.band,3);assert.equal(final.payload.performanceSnapshot.plan.goals[0].weight,60);
 const review=await send({action:'review',employeeId:e.id,period:'2026-H1',performanceId:result.id,potential:2,evidence:'使用本系统已发布绩效结果开展人才盘点'});assert.equal((await get()).records.find(r=>r.id===review.id).payload.performanceSnapshot.originalRating,'优秀');await perf({action:'closeCycle',id:cy.id});act('employee');d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===result.id).payload.score,82);assert.ok(!d.records.some(r=>r.employeeId===other.id));sqlite.close();
});
const recruitment=await import('../app/api/recruitment/route.ts');
async function recruit(command,status=200){const d=await get();return expect(await recruitment.POST(request('/api/recruitment',{revision:d.revision,command})),status);}
test('P3 招聘入职：独立审批、录用依据、字段权限、人数上限与原子建档',async()=>{
 const {sqlite,e,position}=await setup();const req=await recruit({action:'requisition',positionId:position.id,title:'工程师增补',headcount:1,reason:'已确认项目需求，申请补充一名工程师'});await recruit({action:'approveRequisition',id:req.id},403);act('manager');await recruit({action:'approveRequisition',id:req.id});act('owner');const candidate=await recruit({action:'candidate',requisitionId:req.id,name:'合成候选人',email:'candidate-private@example.com',source:'候选人主动投递，来源编号 SYNTHETIC-001'});await recruit({action:'offer',id:candidate.id,joined:'2026-01-01',evidence:'没有面试依据不能直接录用'},400);act('manager');await recruit({action:'interview',candidateId:candidate.id,rating:4,recommendation:'advance',evidence:'岗位案例评估符合要求，建议推进录用'});let d=await expect(await recruitment.GET());assert.equal(d.records.find(r=>r.id===candidate.id).payload.email,undefined);const history=await expect(await dev.GET(request('/api/development?id='+candidate.id)));assert.ok(history.items.every(x=>x.snapshot.payload.email===undefined));act('owner');await recruit({action:'offer',id:candidate.id,joined:'2026-01-01',evidence:'岗位能力评估达标，按岗位条件发起录用'});await recruit({action:'approveOffer',id:candidate.id},403);await recruit({action:'hire',id:candidate.id,code:'NEW1'},400);act('manager');await recruit({action:'approveOffer',id:candidate.id});act('owner');await recruit({action:'acceptOffer',id:candidate.id,evidence:'已取得候选人书面接受确认，文档编号 ACCEPT-001'});await recruit({action:'closeRequisition',id:req.id,reason:'在途候选人未结束不能关闭需求'},400);
 const before=sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision;sqlite.exec("CREATE TRIGGER fail_hire_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await recruit({action:'hire',id:candidate.id,code:'NEW1'},503);assert.equal(sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision,before);assert.equal(sqlite.prepare("SELECT count(*) n FROM hris_employees WHERE code='NEW1'").get().n,0);assert.equal((await expect(await recruitment.GET())).records.find(r=>r.id===candidate.id).status,'accepted');sqlite.exec('DROP TRIGGER fail_hire_audit');
 await recruit({action:'hire',id:candidate.id,code:'NEW1'});let state=(await expect(await hris.GET())).state;const hired=state.employees.find(x=>x.code==='NEW1');assert.ok(hired);assert.equal(hired.positionId,position.id);assert.equal(hired.email,'candidate-private@example.com');assert.equal(sqlite.prepare('SELECT count(*) n FROM hris_employment_history WHERE employee_id=?').get(hired.id).n,1);assert.equal((await expect(await recruitment.GET())).records.find(r=>r.id===candidate.id).payload.hiredEmployeeId,hired.id);await recruit({action:'hire',id:candidate.id,code:'NEW2'},400);assert.equal((await expect(await hris.GET())).state.employees.length,3);
 const extra=await recruit({action:'candidate',requisitionId:req.id,name:'另一合成候选人',email:'',source:'独立投递来源编号 SYNTHETIC-002'});act('manager');await recruit({action:'interview',candidateId:extra.id,rating:3,recommendation:'advance',evidence:'完成岗位案例评价并建议继续推进'});act('owner');await recruit({action:'offer',id:extra.id,joined:'2026-01-01',evidence:'申请录用，仍需检查需求剩余名额'});act('manager');await recruit({action:'approveOffer',id:extra.id});act('owner');await recruit({action:'acceptOffer',id:extra.id,evidence:'已记录第二名候选人的接受依据'});await recruit({action:'hire',id:extra.id,code:'EXTRA'},400);await recruit({action:'rejectCandidate',id:extra.id,reason:'招聘需求人数已满，经沟通结束流程'});await recruit({action:'closeRequisition',id:req.id,reason:'批准招聘人数已经全部完成入职'});act('employee');assert.equal((await expect(await recruitment.GET())).records.length,0);await expect(await dev.GET(request('/api/development?id='+candidate.id)),403);assert.ok(e.id!==hired.id);sqlite.close();
});
const attendance=await import('../app/api/attendance/route.ts');
async function attend(command,status=200){const d=await get();return expect(await attendance.POST(request('/api/attendance',{revision:d.revision,command})),status);}
test('P3 假勤：休息扣除、待批余额占用、撤回释放、独立审批及补卡保留原始记录',async()=>{
 const {sqlite,e,other}=await setup();const shift=await attend({action:'shift',employeeId:e.id,date:'2026-01-05',name:'标准白班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',breakStart:'2026-01-05T12:00:00+08:00',breakEnd:'2026-01-05T13:00:00+08:00'});await attend({action:'shift',employeeId:e.id,date:'2026-01-05',name:'重叠班次',startAt:'2026-01-05T10:00:00+08:00',endAt:'2026-01-05T19:00:00+08:00'},400);const type=await attend({action:'leaveType',code:'PAID2026',name:'企业批准带薪假',paid:true,requiresBalance:true});await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2026,minutes:480,source:'已审核假期台账来源编号 BALANCE-001'});act('employee');const leave=await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T14:00:00+08:00',reason:'已与团队协调安排个人事务请假'});let d=await expect(await attendance.GET());assert.equal(d.balances[0].reserved,240);assert.equal(d.balances[0].available,240);await attend({action:'decideLeave',id:leave.id,accepted:true,evidence:'本人不能审批自己的请假'},403);await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T13:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'重叠申请必须被拒绝避免重复占用'},400);await attend({action:'withdrawLeave',id:leave.id,reason:'工作安排调整，先撤回请假申请'});d=await expect(await attendance.GET());assert.equal(d.balances[0].available,480);const full=await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'重新提交全天请假，工作已经交接'});act('owner');await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2026,minutes:-1,source:'待批额度已经占满，不能再扣减余额'},400);act('manager');await attend({action:'decideLeave',id:full.id,accepted:true,evidence:'已核实工作交接和可用假期，批准'});d=await expect(await attendance.GET());assert.equal(d.report[0].plannedMinutes,480);assert.equal(d.report[0].approvedLeaveMinutes,480);assert.equal(d.report[0].uncoveredMinutes,0);assert.equal(d.report[0].status,'请假覆盖');await attend({action:'decideLeave',id:full.id,accepted:true,evidence:'重复审批不得重复扣减余额'},400);await attend({action:'cancelApprovedLeave',id:full.id,reason:'员工最终未休假，依据出勤记录取消批准'});d=await expect(await attendance.GET());assert.equal(d.balances[0].available,480);
 act('employee');const correction=await attend({action:'correction',shiftId:shift.id,inAt:'2026-01-05T09:00:00+08:00',outAt:'2026-01-05T18:00:00+08:00',evidence:'门禁和项目记录证明当天按时出勤'});await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'本人不能自审补卡'},403);act('manager');await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'已核对门禁与项目记录，确认补卡'});d=await expect(await attendance.GET());assert.equal(d.report[0].uncoveredMinutes,0);assert.equal(d.report[0].corrected,true);assert.equal(d.records.filter(r=>r.kind==='clock').length,0);assert.equal(d.report[0].status,'记录完整');await attend({action:'shift',employeeId:other.id,date:'2026-01-05',name:'越权排班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00'},403);act('employee');assert.ok((await expect(await attendance.GET())).records.every(r=>!r.employeeId||r.employeeId===e.id));sqlite.close();
});
test('P3 打卡：只接受本人及服务端时间、先上班后下班、防重复',async()=>{
 const {sqlite,e}=await setup();const now=Date.now(),startAt=new Date(now-3600000).toISOString(),endAt=new Date(now+3600000).toISOString();const shift=await attend({action:'shift',employeeId:e.id,date:startAt.slice(0,10),name:'打卡验证班次',startAt,endAt});await attend({action:'clock',shiftId:shift.id,punchKind:'in'},403);act('employee');await attend({action:'clock',shiftId:shift.id,punchKind:'out'},400);const entered=await attend({action:'clock',shiftId:shift.id,punchKind:'in',punchAt:'1999-01-01T00:00:00Z'});let d=await expect(await attendance.GET());const punch=d.records.find(r=>r.id===entered.id);assert.ok(Date.parse(punch.payload.punchAt)>=now);await attend({action:'clock',shiftId:shift.id,punchKind:'in'},400);await attend({action:'clock',shiftId:shift.id,punchKind:'out'});d=await expect(await attendance.GET());assert.equal(d.records.filter(r=>r.kind==='clock').length,2);sqlite.close();
});

const payroll=await import('../app/api/payroll/route.ts');
async function pay(command,status=200,revision){revision??=(await get()).revision;return expect(await payroll.POST(request('/api/payroll',{revision,command})),status);}
test('P3 薪酬：分级保密、整数金额、编制复核分离、退回重审、发布锁定及历史隔离',async()=>{
 const {sqlite,e,other,org}=await setup();await grant('reviewer','admin',null);const b=await pay({action:'batch',name:'九月工资',orgId:org.id,period:'2026-09',currency:'CNY',policyReference:'测试用已核定工资明细表，不代表企业正式制度'});
 const items=[{name:'固定工资',category:'earning',amountCents:100001,source:'已核定测试工资标准编号001'},{name:'个人扣款',category:'deduction',amountCents:101,source:'已核定测试扣款明细编号002'},{name:'企业承担',category:'employer',amountCents:222,source:'已核定测试企业承担明细003'}];
 await pay({action:'slip',batchId:b.id,employeeId:other.id,items},400);await pay({action:'slip',batchId:b.id,employeeId:e.id,items:[{...items[0],amountCents:0.1}]},400);const r=await pay({action:'slip',batchId:b.id,employeeId:e.id,items});assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===r.id).payload.netCents,99900);
 for(const user of ['hr','manager','employee','approver']){act(user);assert.equal((await expect(await payroll.GET())).records.length,0);assert.ok(!(await get()).records.some(x=>['payBatch','paySlip'].includes(x.kind)));await expect(await dev.GET(request('/api/development?id='+r.id)),403);await pay({action:'approve',id:b.id,evidence:'没有薪酬权限不能批准'},403);}
 act('owner');await pay({action:'submit',id:b.id,evidence:'已检查本期工资明细与核定依据'});await pay({action:'approve',id:b.id,evidence:'编制人不能自行批准本批次'},403);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items},400);
 act('reviewer');await pay({action:'return',id:b.id,evidence:'退回重新核实应发工资金额'});act('owner');await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items:[{...items[0],amountCents:100000},...items.slice(1)]});await pay({action:'publish',id:b.id,evidence:'退回之后不能跳过重新审核'},400);await pay({action:'submit',id:b.id,evidence:'已重新核定并提交工资明细'});act('reviewer');await pay({action:'approve',id:b.id,evidence:'逐项复核金额与来源，确认一致'});
 act('employee');assert.equal((await expect(await payroll.GET())).records.length,0);act('owner');await pay({action:'publish',id:b.id,evidence:'批准后向员工发布本人工资条'});await pay({action:'publish',id:b.id,evidence:'不能重复发布同一工资批次'},400);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items},400);await pay({action:'cancel',id:b.id,evidence:'不能取消已经发布的工资批次'},400);
 act('employee');const d=await expect(await payroll.GET());assert.equal(d.records.length,1);assert.equal(d.records[0].payload.netCents,99899);assert.equal(d.records[0].payload.payItems.length,2);assert.ok(d.records[0].payload.payItems.every(x=>!x.source));assert.equal(d.records[0].payload.contributors,undefined);await expect(await dev.GET(request('/api/development?id='+r.id)),403);assert.equal((await get()).records.find(x=>x.id===r.id).payload.netCents,99899);
 act('manager');assert.equal((await expect(await payroll.GET())).records.length,0);act('owner');const history=await expect(await dev.GET(request('/api/development?id='+r.id)));assert.ok(history.items.some(x=>x.snapshot.payload.netCents===99900));sqlite.close();
});
test('P3 薪酬：同期间防重复、本人受益与参与编制不得复核、审计失败原子回滚',async()=>{
 const {sqlite,e,org}=await setup();await grant('reviewer','admin',null);const b=await pay({action:'batch',name:'八月工资',orgId:org.id,period:'2026-08',currency:'CNY',policyReference:'仅用于验证的工资政策参考记录'});const items=[{name:'基本工资',category:'earning',amountCents:10000,source:'测试工资核定来源编号001'}];const r=await pay({action:'slip',batchId:b.id,employeeId:e.id,items});await pay({action:'slip',batchId:b.id,employeeId:e.id,items},400);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items:[...items,{name:'扣款',category:'deduction',amountCents:10001,source:'超过应发的测试扣款来源'}]},400);
 act('reviewer');await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items});act('owner');await pay({action:'submit',id:b.id,evidence:'所有明细已编制完毕等待复核'});act('reviewer');await pay({action:'approve',id:b.id,evidence:'参与编制者不得充当复核人'},403);
 await grant('employee','admin',e.id,[],true);act('employee');await pay({action:'approve',id:b.id,evidence:'本人受益也不得充当复核人'},403);await grant('third','admin',null);act('third');const revision=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_pay_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await pay({action:'approve',id:b.id,evidence:'审计故障不能部分提交审核'},503);assert.equal((await get()).revision,revision);assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===b.id).status,'submitted');sqlite.exec('DROP TRIGGER fail_pay_audit');await pay({action:'approve',id:b.id,evidence:'审计恢复后正常提交审核'});await pay({action:'publish',id:b.id,evidence:'过期版本不能发布工资条'},409,revision);assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===b.id).status,'approved');sqlite.close();
});
