import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {database,act,request} from './support/runtime.mjs';
const access=await import('../app/api/access/route.ts'),hris=await import('../app/api/hris/route.ts'),members=await import('../app/api/members/route.ts'),dev=await import('../app/api/development/route.ts'),files=await import('../app/api/attachments/route.ts');
async function expect(r,status=200){assert.equal(r.status,status,await r.clone().text());return r.json();}
async function get(){return expect(await dev.GET());}
async function send(command,status=200,revision){const d=await get();return expect(await dev.POST(request('/api/development',{revision:revision??d.revision,command})),status);}
async function core(command){const d=await expect(await hris.GET());return expect(await hris.POST(request('/api/hris',{revision:d.revision,command})));}
async function grant(id,role,employeeId,orgScope=[],existing=false){act('owner');const d=await expect(await members.GET());await expect(await members.POST(request('/api/members',{revision:d.revision,email:id+'@example.com',name:id,role,employeeId,orgScope,viewEmail:false,viewLevel:false,active:true})));act(id);if(!existing)await expect(await access.POST(request('/api/access',{action:'activate'})));act('owner');}
async function setup(){const {db,sqlite}=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));globalThis.p2env.DB=db;act('owner');await expect(await access.POST(request('/api/access',{action:'setup',name:'人才学习测试企业'})));await core({action:'org',name:'研发',parentId:'',city:'上海',leader:'',status:'启用'});await core({action:'org',name:'财务',parentId:'',city:'北京',leader:'',status:'启用'});let state=(await expect(await hris.GET())).state;const org=state.orgs[0],otherOrg=state.orgs[1];await core({action:'position',code:'DEV',name:'工程师',orgId:org.id,family:'技术',responsibilities:'开发验证',status:'启用'});for(const [code,orgId]of[['A',org.id],['B',otherOrg.id]])await core({action:'employee',code,name:'合成员工'+code,orgId,job:'工程师',level:'',joined:'2026-01-01',email:''});state=(await expect(await hris.GET())).state;const e=state.employees.find(e=>e.code==='A'),other=state.employees.find(e=>e.code==='B');await grant('employee','employee',e.id);await grant('manager','manager',null,[org.id]);await grant('hr','hr',null,[org.id]);await grant('approver','approver',null,[org.id]);return {db,sqlite,e,other,org,otherOrg,position:state.positions[0]};}
const anchors=['能在指导下完成基础任务','能够独立处理常规工作任务','能够独立解决复杂业务问题','能够指导团队完善工作方法','能够建立组织级标准并推广'];
const due='2099-12-31';
test('P3：标准版本、绩效更正、盘点快照、跨组织与本人评价隔离',async()=>{
 const {sqlite,e,other,position}=await setup();const s1=await send({action:'standard',code:'C1',name:'问题解决',anchors});const s2=await send({action:'standard',code:'C1',name:'问题解决新版',anchors:anchors.map(a=>a+'，并提供证据')});let d=await get();assert.equal(d.records.find(r=>r.id===s1.id).payload.version,1);assert.equal(d.records.find(r=>r.id===s2.id).payload.version,2);
 await send({action:'requirement',positionId:position.id,standardId:s1.id,target:3});await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:2,evidence:'独立完成两次常规任务，并提交复盘',assessedOn:'2026-01-01'});
 const perf=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'历史考核文件编号 PERF-001',originalRating:'B',band:2,reason:'依据已批准的历史档位对照表'});
 await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'重复来源记录',originalRating:'A',band:3,reason:'重复导入不得覆盖'},400);
 const review=await send({action:'review',employeeId:e.id,period:'2026-H1',performanceId:perf.id,potential:null,evidence:'潜力评估尚未完成，需要补充访谈'});await send({action:'publishReview',id:review.id});await send({action:'publishReview',id:review.id},400);
 const corrected=await send({action:'performance',employeeId:e.id,period:'2026-H1',source:'复核签字文件编号 PERF-002',originalRating:'A',band:3,reason:'原文件导入错误，经复核更正',supersedes:perf.id});d=await get();assert.equal(d.records.find(r=>r.id===review.id).payload.performanceSnapshot.band,2);assert.equal(d.records.find(r=>r.id===corrected.id).payload.band,3);assert.equal(d.records.find(r=>r.id===review.id).payload.potential,null);
 act('hr');await send({action:'assessment',employeeId:other.id,standardId:s1.id,rating:3,evidence:'越权评估不得保存',assessedOn:'2026-01-01'},403);
 act('employee');d=await get();assert.ok(d.records.some(r=>r.kind==='assessment'));assert.ok(!d.records.some(r=>['performance','review','succession'].includes(r.kind)));await send({action:'standard',code:'hack',name:'越权标准',anchors},403);
 act('approver');assert.ok(!(await get()).records.some(r=>['performance','assessment','review'].includes(r.kind)));await expect(await dev.GET(request('/api/development?id='+review.id)),403);
 act('owner');await grant('employee','manager',e.id,[position.orgId],true);act('employee');await send({action:'assessment',employeeId:e.id,standardId:s1.id,rating:5,evidence:'经理不能评价本人正式能力',assessedOn:'2026-01-01'},403);
 sqlite.close();
});
test('P3：发展计划—课程—学习成果—独立核验闭环与重复处理保护',async()=>{
 const {sqlite,e,position}=await setup();const standard=await send({action:'standard',code:'C1',name:'质量改进',anchors});const plan=await send({action:'plan',employeeId:e.id,standardId:standard.id,target:3,title:'质量实践提升',actionPlan:'完成案例学习和实践改进，由经理核验成果',due});const course=await send({action:'course',code:'L1',title:'质量案例实践',description:'通过真实案例理解问题根因分析方法',content:'学习五个完整案例，记录根因分析，并提交一个实际改善方案供经理核验。',standardId:standard.id});
 act('employee');assert.ok(!(await get()).records.some(r=>r.id===course.id));await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due},403);act('owner');await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,planId:plan.id,due});await send({action:'enroll',employeeId:e.id,courseId:course.id,due},400);
 const succession=await send({action:'succession',employeeId:e.id,positionId:position.id,readiness:'one_year',evidence:'具备基础专业能力，尚需承担团队项目'});assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).job,'工程师');await send({action:'closeSuccession',id:succession.id,reason:'岗位计划调整，保留提名历史'});
 act('employee');await send({action:'submitPlan',id:plan.id,evidence:'已完成案例分析和改进方案文档'});await send({action:'submitPlan',id:plan.id,evidence:'重复提交不应再次写入'},400);await send({action:'submitLearning',id:enrollment.id,evidence:'完成五个案例并提供实践报告编号001'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'本人不能核验本人提交'},403);
 act('manager');await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'先检查关联学习是否完成'},400);await send({action:'verifyLearning',id:enrollment.id,accepted:false,evidence:'缺少实践结果，请补充改进前后对比'});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'已补充改进前后数据和经理访谈记录'});act('manager');await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实实践材料，达到课程完成要求'});await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'重复核验不应再次通过'},400);await send({action:'verifyPlan',id:plan.id,accepted:true,evidence:'完成全部学习任务及发展行动验收'});let d=await get();assert.equal(d.records.find(r=>r.id===plan.id).status,'completed');assert.equal(d.records.find(r=>r.id===enrollment.id).payload.verifiedBy,'manager');const process=await expect(await dev.GET(request('/api/development?id='+enrollment.id)));assert.equal(process.items.length,5);assert.ok(process.items.some(x=>x.snapshot.payload.evidence==='完成五个案例并提供实践报告编号001'));assert.ok(process.items.some(x=>x.snapshot.payload.verification==='缺少实践结果，请补充改进前后对比'));
 act('owner');const rev=(await get()).revision;await send({action:'standard',code:'C2',name:'新能力',anchors});await send({action:'standard',code:'C3',name:'过期修改',anchors},409,rev);assert.ok(!(await get()).records.some(r=>r.payload.code==='C3'));
 const before=sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision;sqlite.exec("CREATE TRIGGER fail_development_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await send({action:'standard',code:'C4',name:'审计失败回滚',anchors},503);assert.equal(sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision,before);assert.ok(!(await get()).records.some(r=>r.payload.code==='C4'));sqlite.close();
});
function mockBucket(){const objects=new Map();globalThis.p2env.BUCKET={put:async(k,b)=>{objects.set(k,new Uint8Array(b));},get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async k=>{objects.delete(k);}};return objects;}
async function upload(employeeId,body='%PDF-test',revision,extra={}){revision??=(await get()).revision;return files.POST(new Request('https://hris.example/api/attachments?'+new URLSearchParams({employeeId,revision:String(revision),name:'材料.pdf',...extra}),{method:'POST',headers:{Origin:'https://hris.example','Content-Type':'application/pdf'},body}));}
test('P3 附件：受权下载、类型与大小验证、并发清理、删除及数据库失败回滚',async()=>{
 const {sqlite,e,other}=await setup(),objects=mockBucket();const f=await expect(await upload(e.id,'%PDF-test',undefined,{visibility:'employee'}));assert.equal(objects.size,1);let list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(list.items.length,1);assert.equal(list.items[0].objectKey,undefined);
 act('employee');let response=await files.GET(request('/api/attachments?id='+f.id));assert.equal(response.status,200);assert.equal(await response.text(),'%PDF-test');assert.equal(response.headers.get('x-content-type-options'),'nosniff');await expect(await files.GET(request('/api/attachments?employeeId='+other.id)),403);await expect(await upload(e.id),403);
 act('owner');await expect(await upload(e.id,'not a pdf'),415);await expect(await upload(e.id,'%PDF-test',undefined,{name:'../file.pdf'}),400);await expect(await upload(e.id,new Uint8Array(10*1024*1024+1)),413);assert.equal(objects.size,1);
 const before=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_file_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await expect(await upload(e.id),503);assert.equal(objects.size,1);assert.equal((await get()).revision,before);sqlite.exec('DROP TRIGGER fail_file_audit');
 const originalPut=globalThis.p2env.BUCKET.put;globalThis.p2env.BUCKET.put=async(k,b)=>{await originalPut(k,b);sqlite.exec('UPDATE hris_workspaces SET revision=revision+1');};await expect(await upload(e.id),409);assert.equal(objects.size,1);globalThis.p2env.BUCKET.put=originalPut;
 list=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));await expect(await files.DELETE(request('/api/attachments',{id:f.id,revision:list.revision})));assert.equal(objects.size,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),404);assert.equal(sqlite.prepare('SELECT count(*) n FROM hris_attachments WHERE deleted_at IS NOT NULL').get().n,1);sqlite.close();
});

test('P3 附件默认保密：员工和审批人不能列出或下载未开放的人事附件',async()=>{
 const {sqlite,e}=await setup();mockBucket();const f=await expect(await upload(e.id));act('employee');const listing=await expect(await files.GET(request('/api/attachments?employeeId='+e.id)));assert.equal(listing.items.length,0);await expect(await files.GET(request('/api/attachments?id='+f.id)),403);act('approver');await expect(await files.GET(request('/api/attachments?id='+f.id)),403);sqlite.close();
});
test('P3 考试：答案服务端保密、次数限制、自动评分及成果提交门槛',async()=>{
 const {sqlite,e}=await setup();const course=await send({action:'course',code:'QUIZ',title:'实践考核课程',description:'通过课程练习验证知识理解与应用',content:'阅读完整案例并回答课程测验，完成后提交实践证据，由经理复核学习效果。'});const exam=await send({action:'exam',courseId:course.id,questions:[{prompt:'遇到数据错误时应当如何处理？',options:['记录事实并按流程修正','直接删除全部数据'],correct:0},{prompt:'完成学习后应当提交什么材料？',options:['无需任何记录','真实实践成果和证据'],correct:1}],passingScore:100,maxAttempts:2});await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',employeeId:e.id,courseId:course.id,due});
 act('employee');let d=await get();const visibleExam=d.records.find(r=>r.id===exam.id);assert.ok(visibleExam);assert.ok(visibleExam.payload.questions.every(q=>!('correct'in q)));const history=await expect(await dev.GET(request('/api/development?id='+exam.id)));assert.ok(history.items[0].snapshot.payload.questions.every(q=>!('correct'in q)));
 await send({action:'submitLearning',id:enrollment.id,evidence:'未通过考试不允许提交成果'},400);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0]},400);const failed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[1,0]});d=await get();assert.equal(d.records.find(r=>r.id===failed.id).payload.score,0);assert.equal(d.records.find(r=>r.id===failed.id).payload.passed,false);
 const passed=await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]});assert.equal((await get()).records.find(r=>r.id===passed.id).payload.score,100);await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},400);await send({action:'submitLearning',id:enrollment.id,evidence:'已通过考试并完成实际案例复盘'});
 act('manager');const managerExam=(await get()).records.find(r=>r.id===exam.id);assert.ok(managerExam.payload.questions.every(q=>!('correct'in q)));await send({action:'attemptExam',enrollmentId:enrollment.id,answers:[0,1]},403);await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'核实考试与实践成果，确认完成学习'});assert.equal((await get()).records.find(r=>r.id===enrollment.id).status,'completed');sqlite.close();
});
test('P3 能力差距：同版本比较，缺失与版本不匹配均为未评定',async()=>{
 const {sqlite,e,position}=await setup();await core({action:'employee',...e,positionId:position.id});const first=await send({action:'standard',code:'GAP',name:'实践能力',anchors});await send({action:'requirement',positionId:position.id,standardId:first.id,target:4});let report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].rating,null);assert.equal(report.items[0].gap,null);await send({action:'assessment',employeeId:e.id,standardId:first.id,rating:3,evidence:'已经独立完成复杂案例并有证据',assessedOn:'2026-01-01'});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items[0].gap,1);const next=await send({action:'standard',code:'GAP',name:'实践能力新版',anchors});await send({action:'requirement',positionId:position.id,standardId:next.id,target:5});report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,1);assert.equal(report.items[0].standardVersion,2);assert.equal(report.items[0].gap,null);act('approver');report=await expect(await dev.GET(request('/api/development?report=gaps')));assert.equal(report.items.length,0);sqlite.close();
});
test('P3 项目化：盘点范围与期间、人才池隔离、培训报名及未结项保护',async()=>{
 const {sqlite,e,other,org}=await setup();const project=await send({action:'project',name:'年度人才盘点',orgId:org.id,period:'2026-H1',start:'2026-01-01',end:'2026-12-31'});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:null,evidence:'项目未启动不能录入盘点'},400);await send({action:'startProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:other.id,period:'2026-H1',potential:null,evidence:'跨项目组织人员不得纳入盘点'},400);const review=await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:2,evidence:'依据访谈和项目成果形成潜力评定'});await send({action:'closeProject',id:project.id},400);await send({action:'publishReview',id:review.id});await send({action:'closeProject',id:project.id});await send({action:'review',projectId:project.id,employeeId:e.id,period:'2026-H1',potential:3,evidence:'结束后不得继续加入记录'},400);
 const pool=await send({action:'pool',name:'技术后备池',orgId:org.id,criteria:'依据技术实践、发展意愿与目标岗位要求入池'});await send({action:'poolMember',poolId:pool.id,employeeId:other.id,evidence:'其他组织不能擅自加入人才池'},400);const membership=await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'具备专业基础并愿意承担复杂项目'});await send({action:'poolMember',poolId:pool.id,employeeId:e.id,evidence:'重复加入不能新增重复记录'},400);act('employee');assert.ok(!(await get()).records.some(r=>['project','review','pool','poolMember'].includes(r.kind)));act('owner');await send({action:'removePoolMember',id:membership.id,reason:'发展方向调整，经复核退出人才池'});
 const course=await send({action:'course',code:'TRAIN',title:'培训项目课程',description:'通过培训课程学习规范的实践方法',content:'阅读案例正文，完成培训项目规定的实际任务，并提交可供核实的学习成果。'});await send({action:'publishCourse',id:course.id});const training=await send({action:'training',name:'技术人才训练营',orgId:org.id,period:'2099',start:'2099-01-01',end:due,instructor:'企业内部讲师',courseIds:[course.id]});act('employee');assert.ok(!(await get()).records.some(r=>r.id===training.id));act('owner');await send({action:'publishTraining',id:training.id});act('employee');assert.ok((await get()).records.some(r=>r.id===training.id));const enrollment=await send({action:'enroll',trainingId:training.id,employeeId:e.id,courseId:course.id,due});act('manager');await send({action:'closeTraining',id:training.id},400);await send({action:'cancelEnrollment',id:enrollment.id,reason:'员工工作安排变化，经确认取消本次培训'});await send({action:'closeTraining',id:training.id});act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'取消后的任务不能再提交学习成果'},400);sqlite.close();
});
const performance=await import('../app/api/performance/route.ts');
async function perf(command,status=200){const d=await get();return expect(await performance.POST(request('/api/performance',{revision:d.revision,command})),status);}
test('P3 正式绩效：目标确认、自评、独立评价、发布、盘点使用与结项',async()=>{
 const {sqlite,e,other,org}=await setup();const cy=await perf({action:'cycle',name:'2026上半年绩效',orgId:org.id,period:'2026-H1',start:'2026-01-01',end:'2026-06-30',lowCut:60,highCut:80,lowLabel:'待改进',midLabel:'达成',highLabel:'优秀'});act('employee');assert.ok(!(await expect(await performance.GET())).records.some(r=>r.id===cy.id));act('owner');await perf({action:'startCycle',id:cy.id});const goals=[{title:'交付质量',metric:'按验收标准完成项目且无严重缺陷',weight:60},{title:'团队协作',metric:'完成评审与知识分享并留存记录',weight:40}];await perf({action:'goals',employeeId:other.id,cycleId:cy.id,goals},400);
 act('employee');await perf({action:'goals',employeeId:e.id,cycleId:cy.id,goals:[{...goals[0],weight:90}]},400);const plan=await perf({action:'goals',employeeId:e.id,cycleId:cy.id,goals});await perf({action:'confirmGoals',id:plan.id},403);await perf({action:'selfReview',id:plan.id,evidence:'目标尚未确认不能提交自评'},400);act('manager');await perf({action:'confirmGoals',id:plan.id});act('employee');await perf({action:'goals',id:plan.id,employeeId:e.id,cycleId:cy.id,goals},400);await perf({action:'selfReview',id:plan.id,evidence:'交付项目均已完成验收，同时组织三次分享'});act('manager');await perf({action:'evaluate',id:plan.id,scores:[90,70],evidence:'验收结果和评审记录支持相应目标评分'});let d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===plan.id).payload.score,82);
 act('employee');d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===plan.id).payload.score,undefined);assert.equal(d.records.find(r=>r.id===plan.id).payload.evaluation,undefined);const hist=await expect(await dev.GET(request('/api/development?id='+plan.id)));assert.ok(hist.items.every(x=>x.snapshot.payload.score===undefined));await perf({action:'publishPerformance',id:plan.id,evidence:'员工不能自行发布绩效'},403);
 act('owner');await perf({action:'closeCycle',id:cy.id},400);const result=await perf({action:'publishPerformance',id:plan.id,evidence:'已核对目标、自评及管理评价，确认发布'});await perf({action:'publishPerformance',id:plan.id,evidence:'重复发布不得生成第二份结果'},400);await perf({action:'returnPerformance',id:plan.id,evidence:'发布后不能通过退回改写原始评价'},400);let records=(await get()).records;const final=records.find(r=>r.id===result.id);assert.equal(final.payload.score,82);assert.equal(final.payload.originalRating,'优秀');assert.equal(final.payload.band,3);assert.equal(final.payload.performanceSnapshot.plan.goals[0].weight,60);
 const review=await send({action:'review',employeeId:e.id,period:'2026-H1',performanceId:result.id,potential:2,evidence:'使用本系统已发布绩效结果开展人才盘点'});assert.equal((await get()).records.find(r=>r.id===review.id).payload.performanceSnapshot.originalRating,'优秀');await perf({action:'closeCycle',id:cy.id});act('employee');d=await expect(await performance.GET());assert.equal(d.records.find(r=>r.id===result.id).payload.score,82);assert.ok(!d.records.some(r=>r.employeeId===other.id));sqlite.close();
});
const recruitment=await import('../app/api/recruitment/route.ts');
async function recruit(command,status=200){const d=await get();return expect(await recruitment.POST(request('/api/recruitment',{revision:d.revision,command})),status);}
test('P3 招聘入职：独立审批、录用依据、字段权限、人数上限与原子建档',async()=>{
 const {sqlite,e,position}=await setup();const req=await recruit({action:'requisition',positionId:position.id,title:'工程师增补',headcount:1,reason:'已确认项目需求，申请补充一名工程师'});await recruit({action:'approveRequisition',id:req.id},403);act('manager');await recruit({action:'approveRequisition',id:req.id});act('owner');const candidate=await recruit({action:'candidate',requisitionId:req.id,name:'合成候选人',email:'candidate-private@example.com',source:'候选人主动投递，来源编号 SYNTHETIC-001'});await recruit({action:'offer',id:candidate.id,joined:'2026-01-01',evidence:'没有面试依据不能直接录用'},400);act('manager');await recruit({action:'interview',candidateId:candidate.id,rating:4,recommendation:'advance',evidence:'岗位案例评估符合要求，建议推进录用'});let d=await expect(await recruitment.GET());assert.equal(d.records.find(r=>r.id===candidate.id).payload.email,undefined);const history=await expect(await dev.GET(request('/api/development?id='+candidate.id)));assert.ok(history.items.every(x=>x.snapshot.payload.email===undefined));act('owner');await recruit({action:'offer',id:candidate.id,joined:'2026-01-01',evidence:'岗位能力评估达标，按岗位条件发起录用'});await recruit({action:'approveOffer',id:candidate.id},403);await recruit({action:'hire',id:candidate.id,code:'NEW1'},400);act('manager');await recruit({action:'approveOffer',id:candidate.id});act('owner');await recruit({action:'acceptOffer',id:candidate.id,evidence:'已取得候选人书面接受确认，文档编号 ACCEPT-001'});await recruit({action:'closeRequisition',id:req.id,reason:'在途候选人未结束不能关闭需求'},400);
 const before=sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision;sqlite.exec("CREATE TRIGGER fail_hire_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await recruit({action:'hire',id:candidate.id,code:'NEW1'},503);assert.equal(sqlite.prepare('SELECT revision FROM hris_workspaces').get().revision,before);assert.equal(sqlite.prepare("SELECT count(*) n FROM hris_employees WHERE code='NEW1'").get().n,0);assert.equal((await expect(await recruitment.GET())).records.find(r=>r.id===candidate.id).status,'accepted');sqlite.exec('DROP TRIGGER fail_hire_audit');
 await recruit({action:'hire',id:candidate.id,code:'NEW1'});let state=(await expect(await hris.GET())).state;const hired=state.employees.find(x=>x.code==='NEW1');assert.ok(hired);assert.equal(hired.positionId,position.id);assert.equal(hired.email,'candidate-private@example.com');assert.equal(sqlite.prepare('SELECT count(*) n FROM hris_employment_history WHERE employee_id=?').get(hired.id).n,1);assert.equal((await expect(await recruitment.GET())).records.find(r=>r.id===candidate.id).payload.hiredEmployeeId,hired.id);await recruit({action:'hire',id:candidate.id,code:'NEW2'},400);assert.equal((await expect(await hris.GET())).state.employees.length,3);
 const extra=await recruit({action:'candidate',requisitionId:req.id,name:'另一合成候选人',email:'',source:'独立投递来源编号 SYNTHETIC-002'});act('manager');await recruit({action:'interview',candidateId:extra.id,rating:3,recommendation:'advance',evidence:'完成岗位案例评价并建议继续推进'});act('owner');await recruit({action:'offer',id:extra.id,joined:'2026-01-01',evidence:'申请录用，仍需检查需求剩余名额'});act('manager');await recruit({action:'approveOffer',id:extra.id});act('owner');await recruit({action:'acceptOffer',id:extra.id,evidence:'已记录第二名候选人的接受依据'});await recruit({action:'hire',id:extra.id,code:'EXTRA'},400);await recruit({action:'rejectCandidate',id:extra.id,reason:'招聘需求人数已满，经沟通结束流程'});await recruit({action:'closeRequisition',id:req.id,reason:'批准招聘人数已经全部完成入职'});act('employee');assert.equal((await expect(await recruitment.GET())).records.length,0);await expect(await dev.GET(request('/api/development?id='+candidate.id)),403);assert.ok(e.id!==hired.id);sqlite.close();
});
const attendance=await import('../app/api/attendance/route.ts');
async function attend(command,status=200){const d=await get();return expect(await attendance.POST(request('/api/attendance',{revision:d.revision,command})),status);}
test('P3 假勤：休息扣除、待批余额占用、撤回释放、独立审批及补卡保留原始记录',async()=>{
 const {sqlite,e,other}=await setup();const shift=await attend({action:'shift',employeeId:e.id,date:'2026-01-05',name:'标准白班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',breakStart:'2026-01-05T12:00:00+08:00',breakEnd:'2026-01-05T13:00:00+08:00'});await attend({action:'shift',employeeId:e.id,date:'2026-01-05',name:'重叠班次',startAt:'2026-01-05T10:00:00+08:00',endAt:'2026-01-05T19:00:00+08:00'},400);const type=await attend({action:'leaveType',code:'PAID2026',name:'企业批准带薪假',paid:true,requiresBalance:true});await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2026,minutes:480,source:'已审核假期台账来源编号 BALANCE-001'});act('employee');const leave=await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T14:00:00+08:00',reason:'已与团队协调安排个人事务请假'});let d=await expect(await attendance.GET());assert.ok((await expect(await selfService.GET())).requests.some(r=>r.id===leave.id&&r.status==='pending'));assert.equal(d.balances[0].reserved,240);assert.equal(d.balances[0].available,240);await attend({action:'decideLeave',id:leave.id,accepted:true,evidence:'本人不能审批自己的请假'},403);await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T13:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'重叠申请必须被拒绝避免重复占用'},400);await attend({action:'withdrawLeave',id:leave.id,reason:'工作安排调整，先撤回请假申请'});d=await expect(await attendance.GET());assert.equal(d.balances[0].available,480);const full=await attend({action:'leave',employeeId:e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'重新提交全天请假，工作已经交接'});act('owner');await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2026,minutes:-1,source:'待批额度已经占满，不能再扣减余额'},400);act('manager');await attend({action:'decideLeave',id:full.id,accepted:true,evidence:'已核实工作交接和可用假期，批准'});d=await expect(await attendance.GET());assert.equal(d.report[0].plannedMinutes,480);assert.equal(d.report[0].approvedLeaveMinutes,480);assert.equal(d.report[0].uncoveredMinutes,0);assert.equal(d.report[0].status,'请假覆盖');await attend({action:'decideLeave',id:full.id,accepted:true,evidence:'重复审批不得重复扣减余额'},400);await attend({action:'cancelApprovedLeave',id:full.id,reason:'员工最终未休假，依据出勤记录取消批准'});d=await expect(await attendance.GET());assert.equal(d.balances[0].available,480);
 act('employee');const correction=await attend({action:'correction',shiftId:shift.id,inAt:'2026-01-05T09:00:00+08:00',outAt:'2026-01-05T18:00:00+08:00',evidence:'门禁和项目记录证明当天按时出勤'});await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'本人不能自审补卡'},403);act('manager');await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'已核对门禁与项目记录，确认补卡'});d=await expect(await attendance.GET());assert.equal(d.report[0].uncoveredMinutes,0);assert.equal(d.report[0].corrected,true);assert.equal(d.records.filter(r=>r.kind==='clock').length,0);assert.equal(d.report[0].status,'记录完整');await attend({action:'shift',employeeId:other.id,date:'2026-01-05',name:'越权排班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00'},403);act('employee');assert.ok((await expect(await attendance.GET())).records.every(r=>!r.employeeId||r.employeeId===e.id));sqlite.close();
});
test('P3 打卡：只接受本人及服务端时间、先上班后下班、防重复',async()=>{
 const {sqlite,e}=await setup();const now=Date.now(),startAt=new Date(now-3600000).toISOString(),endAt=new Date(now+3600000).toISOString();const shift=await attend({action:'shift',employeeId:e.id,date:startAt.slice(0,10),name:'打卡验证班次',startAt,endAt});await attend({action:'clock',shiftId:shift.id,punchKind:'in'},403);act('employee');await attend({action:'clock',shiftId:shift.id,punchKind:'out'},400);const entered=await attend({action:'clock',shiftId:shift.id,punchKind:'in',punchAt:'1999-01-01T00:00:00Z'});let d=await expect(await attendance.GET());const punch=d.records.find(r=>r.id===entered.id);assert.ok(Date.parse(punch.payload.punchAt)>=now);await attend({action:'clock',shiftId:shift.id,punchKind:'in'},400);await attend({action:'clock',shiftId:shift.id,punchKind:'out'});d=await expect(await attendance.GET());assert.equal(d.records.filter(r=>r.kind==='clock').length,2);sqlite.close();
});

const payroll=await import('../app/api/payroll/route.ts');
async function pay(command,status=200,revision){revision??=(await get()).revision;return expect(await payroll.POST(request('/api/payroll',{revision,command})),status);}
test('P3 薪酬：分级保密、整数金额、编制复核分离、退回重审、发布锁定及历史隔离',async()=>{
 const {sqlite,e,other,org}=await setup();await grant('reviewer','admin',null);const b=await pay({action:'batch',name:'九月工资',orgId:org.id,period:'2026-09',currency:'CNY',policyReference:'测试用已核定工资明细表，不代表企业正式制度'});
 const items=[{name:'固定工资',category:'earning',amountCents:100001,source:'已核定测试工资标准编号001'},{name:'个人扣款',category:'deduction',amountCents:101,source:'已核定测试扣款明细编号002'},{name:'企业承担',category:'employer',amountCents:222,source:'已核定测试企业承担明细003'}];
 await pay({action:'slip',batchId:b.id,employeeId:other.id,items},400);await pay({action:'slip',batchId:b.id,employeeId:e.id,items:[{...items[0],amountCents:0.1}]},400);const r=await pay({action:'slip',batchId:b.id,employeeId:e.id,items});assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===r.id).payload.netCents,99900);
 for(const user of ['hr','manager','employee','approver']){act(user);assert.equal((await expect(await payroll.GET())).records.length,0);assert.ok(!(await get()).records.some(x=>['payBatch','paySlip'].includes(x.kind)));await expect(await dev.GET(request('/api/development?id='+r.id)),403);await pay({action:'approve',id:b.id,evidence:'没有薪酬权限不能批准'},403);}
 act('owner');await pay({action:'submit',id:b.id,evidence:'已检查本期工资明细与核定依据'});await pay({action:'approve',id:b.id,evidence:'编制人不能自行批准本批次'},403);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items},400);
 act('reviewer');await pay({action:'return',id:b.id,evidence:'退回重新核实应发工资金额'});act('owner');await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items:[{...items[0],amountCents:100000},...items.slice(1)]});await pay({action:'publish',id:b.id,evidence:'退回之后不能跳过重新审核'},400);await pay({action:'submit',id:b.id,evidence:'已重新核定并提交工资明细'});act('reviewer');await pay({action:'approve',id:b.id,evidence:'逐项复核金额与来源，确认一致'});
 act('employee');assert.equal((await expect(await payroll.GET())).records.length,0);act('owner');await pay({action:'publish',id:b.id,evidence:'批准后向员工发布本人工资条'});await pay({action:'publish',id:b.id,evidence:'不能重复发布同一工资批次'},400);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items},400);await pay({action:'cancel',id:b.id,evidence:'不能取消已经发布的工资批次'},400);
 act('employee');const d=await expect(await payroll.GET());assert.equal(d.records.length,1);assert.equal(d.records[0].payload.netCents,99899);assert.equal(d.records[0].payload.payItems.length,2);assert.ok(d.records[0].payload.payItems.every(x=>!x.source));assert.equal(d.records[0].payload.contributors,undefined);await expect(await dev.GET(request('/api/development?id='+r.id)),403);assert.equal((await get()).records.find(x=>x.id===r.id).payload.netCents,99899);
 act('manager');assert.equal((await expect(await payroll.GET())).records.length,0);act('owner');const history=await expect(await dev.GET(request('/api/development?id='+r.id)));assert.ok(history.items.some(x=>x.snapshot.payload.netCents===99900));sqlite.close();
});
test('P3 薪酬：同期间防重复、本人受益与参与编制不得复核、审计失败原子回滚',async()=>{
 const {sqlite,e,org}=await setup();await grant('reviewer','admin',null);const b=await pay({action:'batch',name:'八月工资',orgId:org.id,period:'2026-08',currency:'CNY',policyReference:'仅用于验证的工资政策参考记录'});const items=[{name:'基本工资',category:'earning',amountCents:10000,source:'测试工资核定来源编号001'}];const r=await pay({action:'slip',batchId:b.id,employeeId:e.id,items});await pay({action:'slip',batchId:b.id,employeeId:e.id,items},400);await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items:[...items,{name:'扣款',category:'deduction',amountCents:10001,source:'超过应发的测试扣款来源'}]},400);
 act('reviewer');await pay({action:'slip',id:r.id,batchId:b.id,employeeId:e.id,items});act('owner');await pay({action:'submit',id:b.id,evidence:'所有明细已编制完毕等待复核'});act('reviewer');await pay({action:'approve',id:b.id,evidence:'参与编制者不得充当复核人'},403);
 await grant('employee','admin',e.id,[],true);act('employee');await pay({action:'approve',id:b.id,evidence:'本人受益也不得充当复核人'},403);await grant('third','admin',null);act('third');const revision=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_pay_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await pay({action:'approve',id:b.id,evidence:'审计故障不能部分提交审核'},503);assert.equal((await get()).revision,revision);assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===b.id).status,'submitted');sqlite.exec('DROP TRIGGER fail_pay_audit');await pay({action:'approve',id:b.id,evidence:'审计恢复后正常提交审核'});await pay({action:'publish',id:b.id,evidence:'过期版本不能发布工资条'},409,revision);assert.equal((await expect(await payroll.GET())).records.find(x=>x.id===b.id).status,'approved');sqlite.close();
});

const reports=await import('../app/api/reports/route.ts'),selfService=await import('../app/api/self-service/route.ts');
test('P3 报表：人员范围、字段保密、分页、CSV公式防护及导出审计事务',async()=>{
 const {sqlite,e,org}=await setup();await core({action:'employee',...e,name:'=SUM(1,2)',email:'hidden@example.com'});
 act('hr');let d=await expect(await reports.GET(request('/api/reports?dataset=workforce')));assert.equal(d.total,1);assert.ok(!d.columns.includes('邮箱'));assert.ok(!d.columns.includes('职级'));assert.ok(!JSON.stringify(d).includes('hidden@example.com'));let csv=await reports.POST(request('/api/reports',{revision:d.revision,query:{dataset:'workforce'}}));assert.equal(csv.status,200);assert.ok((await csv.text()).includes("'=SUM(1,2)"));assert.equal(csv.headers.get('cache-control'),'no-store');assert.equal(sqlite.prepare("SELECT count(*) n FROM hris_audit_events WHERE action='报表导出'").get().n,1);
 act('employee');d=await expect(await reports.GET(request('/api/reports?dataset=workforce')));assert.equal(d.total,1);assert.equal(d.rows[0][0],e.code);act('approver');assert.equal((await expect(await reports.GET(request('/api/reports?dataset=workforce')))).total,0);
 act('owner');for(let i=0;i<51;i++)await core({action:'employee',code:'PAGE'+i,name:'分页测试'+i,orgId:org.id,job:'测试',level:'',email:'',joined:'2026-01-01'});d=await expect(await reports.GET(request('/api/reports?dataset=workforce')));assert.equal(d.total,53);assert.equal(d.rows.length,50);assert.equal(d.hasMore,true);let next=await expect(await reports.GET(request('/api/reports?dataset=workforce&page=2')));assert.equal(next.rows.length,3);assert.equal(next.hasMore,false);
 const revision=(await get()).revision;sqlite.exec("CREATE TRIGGER fail_export_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");await expect(await reports.POST(request('/api/reports',{revision,query:{dataset:'workforce'}})),503);assert.equal((await get()).revision,revision);sqlite.exec('DROP TRIGGER fail_export_audit');await core({action:'employee',code:'STALE',name:'版本更新测试',orgId:org.id,job:'测试',level:'',email:'',joined:'2026-01-01'});await expect(await reports.POST(request('/api/reports',{revision,query:{dataset:'workforce'}})),409);await expect(await reports.GET(request('/api/reports?dataset=payroll')),400);sqlite.close();
});
test('P3 员工自助：仅本人待办、未完成状态及缺少关联员工的空状态',async()=>{
 const {sqlite,e,other}=await setup();const standard=await send({action:'standard',code:'SELF',name:'实践能力',anchors});await send({action:'plan',employeeId:e.id,standardId:standard.id,target:3,title:'本人的发展任务',actionPlan:'执行任务并提交实践核验材料',due});await send({action:'plan',employeeId:other.id,standardId:standard.id,target:3,title:'其他员工的发展任务',actionPlan:'其他员工单独实施的实践计划',due});act('employee');let d=await expect(await selfService.GET());assert.equal(d.employee.id,e.id);assert.equal(d.tasks.length,1);assert.equal(d.tasks[0].title,'本人的发展任务');assert.ok(!JSON.stringify(d).includes('其他员工'));await send({action:'submitPlan',id:d.tasks[0].id,evidence:'已完成实践行动并提交核验材料'});assert.equal((await expect(await selfService.GET())).tasks.length,0);act('manager');d=await expect(await selfService.GET());assert.equal(d.employee,null);assert.equal(d.tasks.length,0);assert.equal(d.requests.length,0);sqlite.close();
});

const workforce=await import('../app/api/workforce/route.ts');
async function work(command,status=200){return expect(await workforce.POST(request('/api/workforce',{revision:(await get()).revision,command})),status);}
async function coreResult(command,status){return expect(await hris.POST(request('/api/hris',{revision:(await get()).revision,command})),status);}
test('P3 编制：独立审批、版本调整、直接新增和招聘入职共用容量约束',async()=>{
 const {sqlite,e,org,position}=await setup();await core({action:'employee',...e,positionId:position.id});const p=await work({action:'staffing',positionId:position.id,start:'2020-01-01',end:'2099-12-31',headcount:1,evidence:'测试批准岗位人数为一人'});await work({action:'approveStaffing',id:p.id,evidence:'申请者不能批准自己的编制'},403);act('manager');await work({action:'approveStaffing',id:p.id,evidence:'复核岗位计划并批准一人编制'});act('owner');const newEmp={action:'employee',code:'LIMIT',name:'超编测试',orgId:org.id,positionId:position.id,job:'工程师',level:'',email:'',joined:'2026-01-01'};await coreResult(newEmp,400);await coreResult({...newEmp,positionId:undefined},400);
 const q=await recruit({action:'requisition',positionId:position.id,title:'编制核验招聘需求',headcount:2,reason:'人数需求批准不代替编制检查'});act('manager');await recruit({action:'approveRequisition',id:q.id});act('owner');const candidate=await recruit({action:'candidate',requisitionId:q.id,name:'编制测试候选人',email:'',source:'测试招聘来源编号001'});await recruit({action:'interview',candidateId:candidate.id,rating:4,recommendation:'advance',evidence:'测试候选人符合岗位要求'});await recruit({action:'offer',id:candidate.id,joined:'2026-01-01',evidence:'核实岗位与计划后申请录用'});act('manager');await recruit({action:'approveOffer',id:candidate.id});act('owner');await recruit({action:'acceptOffer',id:candidate.id,evidence:'测试已接受录用凭据001'});await recruit({action:'hire',id:candidate.id,code:'HIRED-LIMIT'},400);
 const adjusted=await work({action:'staffing',positionId:position.id,start:'2020-01-01',end:'2099-12-31',headcount:2,supersedes:p.id,evidence:'业务增长申请将编制调整为两人'});await recruit({action:'hire',id:candidate.id,code:'HIRED-LIMIT'},400);act('manager');await work({action:'approveStaffing',id:adjusted.id,evidence:'独立核实扩编依据并批准'});act('owner');await recruit({action:'hire',id:candidate.id,code:'HIRED-LIMIT'});const usage=(await expect(await workforce.GET())).usage;assert.equal(usage.find(x=>x.id===p.id).effective,false);assert.equal(usage.find(x=>x.id===adjusted.id).occupied,2);await coreResult(newEmp,400);assert.equal((await get()).records.find(x=>x.id===p.id).payload.headcount,1);sqlite.close();
});
test('P3 合同：草稿保密、签署证明、续签关联、重叠拒绝、独立终止及档案状态不变',async()=>{
 const {sqlite,e,other}=await setup();const c=await work({action:'contract',employeeId:e.id,number:'CT-001',employerName:'合成测试主体',contractType:'fixed',start:'2026-01-01',end:'2026-12-31',evidence:'依据已提供合同资料建立台账'});act('employee');assert.ok(!(await get()).records.some(r=>r.id===c.id));await work({action:'signContract',id:c.id,signedOn:'2026-01-01',evidence:'员工不能代替HR登记签署'},403);act('owner');await work({action:'signContract',id:c.id,signedOn:'2099-01-01',evidence:'未来日期不能视为已签署'},400);await work({action:'signContract',id:c.id,signedOn:'2026-01-01',evidence:'已核实双方签署纸质材料编号001'});
 act('employee');const own=(await get()).records.find(r=>r.id===c.id);assert.equal(own.payload.contractNumber,'CT-001');assert.equal(own.payload.evidence,undefined);assert.equal(own.payload.signEvidence,undefined);await expect(await dev.GET(request('/api/development?id='+c.id)),403);act('manager');assert.ok(!(await get()).records.some(r=>r.id===c.id));act('hr');await work({action:'contract',employeeId:other.id,number:'OUT',employerName:'越权主体',contractType:'open',start:'2026-01-01',evidence:'跨组织合同不能读取和登记'},403);
 act('owner');const overlap=await work({action:'contract',employeeId:e.id,number:'CT-002',employerName:'合成测试主体',contractType:'fixed',start:'2026-06-01',end:'2027-01-01',evidence:'用于测试重叠签署拦截'});await work({action:'signContract',id:overlap.id,signedOn:'2026-06-01',evidence:'同主体重叠合同不应通过'},400);await work({action:'cancelContract',id:overlap.id,evidence:'重叠草稿录入错误现作废'});await work({action:'endContract',id:c.id,endedOn:'2026-06-30',evidence:'建档者不能自行办理终止复核'},403);act('hr');await work({action:'endContract',id:c.id,endedOn:'2026-06-30',evidence:'复核双方已经完成的终止资料'});act('owner');const renewed=await work({action:'contract',employeeId:e.id,number:'CT-003',employerName:'合成测试主体',contractType:'fixed',start:'2026-07-01',end:'2027-06-30',renewalOf:c.id,evidence:'根据新签协议登记合同续期'});await work({action:'signContract',id:renewed.id,signedOn:'2026-07-01',evidence:'核实本次续签双方签署凭据'});assert.equal((await get()).records.find(r=>r.id===renewed.id).referenceId,c.id);assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).status,e.status);sqlite.close();
});

const qualifications=await import('../app/api/qualifications/route.ts');
async function qual(command,status=200){return expect(await qualifications.POST(request('/api/qualifications',{revision:(await get()).revision,command})),status);}
test('P3 任职资格：标准版本严格匹配、未评定阻断、独立认证与证据快照不改任职',async()=>{
 const {sqlite,e}=await setup();const v1=await send({action:'standard',code:'QUAL',name:'质量实践能力',anchors});await send({action:'assessment',employeeId:e.id,standardId:v1.id,rating:5,evidence:'旧版能力标准的完整评估材料',assessedOn:'2026-01-01'});const v2=await send({action:'standard',code:'QUAL',name:'质量实践新版',anchors});const standard=await qual({action:'standard',code:'Q1',name:'质量工程内部资格',criteria:'依据质量实践新版能力标准达到三级',requirements:[{standardId:v2.id,target:3}]});act('employee');assert.ok(!(await get()).records.some(r=>r.id===standard.id));act('owner');await qual({action:'publishStandard',id:standard.id});act('employee');const app=await qual({action:'apply',standardId:standard.id,employeeId:e.id,evidence:'提交项目实践证明申请质量工程资格'});await qual({action:'review',id:app.id,accepted:true,evidence:'申请人不能自行评审资格'},403);act('manager');let d=await expect(await qualifications.GET());assert.equal(d.readiness.find(x=>x.id===app.id).items[0].rating,null);await qual({action:'review',id:app.id,accepted:true,evidence:'旧版本能力评分不能代替新版'},400);await send({action:'assessment',employeeId:e.id,standardId:v2.id,rating:3,evidence:'按新版标准核实案例与实践结果',assessedOn:'2026-02-01'});await qual({action:'review',id:app.id,accepted:true,evidence:'核对全部能力要求及评估证据通过',validUntil:'2099-12-31'});d=await get();const result=d.records.find(x=>x.id===app.id);assert.equal(result.status,'certified');assert.equal(result.payload.qualificationProof[0].rating,3);assert.ok(result.payload.certificateNumber.startsWith('IQ-'));
 await send({action:'assessment',employeeId:e.id,standardId:v2.id,rating:1,evidence:'后续新评估不应覆盖原认证证据',assessedOn:'2026-03-01'});assert.equal((await get()).records.find(x=>x.id===app.id).payload.qualificationProof[0].rating,3);act('employee');await qual({action:'apply',standardId:standard.id,employeeId:e.id,evidence:'有效期内不能重复申请同版本资格'},400);assert.equal((await expect(await hris.GET())).state.employees[0].job,e.job);act('hr');await qual({action:'revoke',id:app.id,evidence:'复核后撤销资格，原认证记录保留'});act('employee');assert.equal((await get()).records.find(x=>x.id===app.id).status,'revoked');sqlite.close();
});
test('P3 任职资格：HR代办不得自审、跨组织拒绝、停用阻止新申请与撤回',async()=>{
 const {sqlite,e,other}=await setup();const cap=await send({action:'standard',code:'Q-SCOPE',name:'资格范围能力',anchors});const standard=await qual({action:'standard',code:'Q2',name:'内部资格范围验证',criteria:'具备可复核的一级实践证据',requirements:[{standardId:cap.id,target:1}]});await qual({action:'publishStandard',id:standard.id});act('hr');await qual({action:'apply',standardId:standard.id,employeeId:other.id,evidence:'跨组织不能代办资格申请'},403);const app=await qual({action:'apply',standardId:standard.id,employeeId:e.id,evidence:'HR根据员工书面申请代为登记'});await qual({action:'review',id:app.id,accepted:false,evidence:'代办者不能同时承担独立评审'},403);act('employee');await qual({action:'withdraw',id:app.id,evidence:'非提交人不得撤回HR代办申请'},403);act('hr');await qual({action:'withdraw',id:app.id,evidence:'根据原申请人说明撤回代办申请'});await qual({action:'archiveStandard',id:standard.id});act('employee');await qual({action:'apply',standardId:standard.id,employeeId:e.id,evidence:'停用标准不得继续新申请'},400);act('approver');assert.ok(!(await get()).records.some(r=>r.id===app.id));sqlite.close();
});

const surveys=await import('../app/api/surveys/route.ts');
async function survey(command,status=200){return expect(await surveys.POST(request('/api/surveys',{revision:(await get()).revision,command})),status);}
test('P3 实名问卷：版本快照、名单冻结、本人填报、修改撤回及结项锁定',async()=>{
 const {sqlite,e,other,org}=await setup();const questions=[{type:'rating',prompt:'培训内容对工作的帮助程度',lowLabel:'帮助很小',highLabel:'帮助很大'},{type:'choice',prompt:'更适合的学习形式',options:['现场练习','在线案例']}];const template=await survey({action:'template',code:'S1',name:'培训反馈',description:'收集实名培训反馈用于改进后续课程',questions});act('employee');assert.ok(!(await get()).records.some(r=>r.id===template.id));act('owner');await survey({action:'publishTemplate',id:template.id});const round=await survey({action:'round',templateId:template.id,name:'本期培训反馈',orgId:org.id,start:'2020-01-01',end:'2099-12-31',purpose:'实名收集课程反馈，仅项目HR及管理员查看答卷'});await survey({action:'open',id:round.id});await survey({action:'template',code:'S1',name:'培训反馈新版',description:'新版模板不会更改已有问卷题目',questions:[{...questions[0],prompt:'新版问题'}]});assert.equal((await get()).records.find(r=>r.id===round.id).payload.surveyQuestions.length,2);
 await core({action:'employee',code:'LATE',name:'发布后新加入人员',orgId:org.id,job:'测试',level:'',email:'',joined:'2026-01-01'});const late=(await expect(await hris.GET())).state.employees.find(x=>x.code==='LATE');await grant('late','employee',late.id);act('late');await survey({action:'respond',roundId:round.id,answers:[5,1]},403);assert.ok(!(await get()).records.some(r=>r.id===round.id));act('owner');await grant('outside','employee',other.id);act('outside');await survey({action:'respond',roundId:round.id,answers:[5,1]},403);
 act('employee');let d=await expect(await surveys.GET());assert.equal(d.records.find(r=>r.id===round.id).payload.participantIds,undefined);assert.equal(d.summaries.length,0);const hist=await expect(await dev.GET(request('/api/development?id='+round.id)));assert.ok(hist.items.every(x=>x.snapshot.payload.participantIds===undefined));await survey({action:'respond',roundId:round.id,answers:[0,1]},400);await survey({action:'respond',roundId:round.id,answers:[5]},400);const response=await survey({action:'respond',roundId:round.id,answers:[5,1]});const changed=await survey({action:'respond',roundId:round.id,answers:[3,0]});assert.equal(changed.id,response.id);assert.equal((await expect(await selfService.GET())).tasks.filter(t=>t.kind==='surveyRound').length,0);
 act('hr');d=await expect(await surveys.GET());assert.equal(d.summaries[0].invited,1);assert.equal(d.summaries[0].responded,1);assert.equal(d.summaries[0].questions[0].average,3);await survey({action:'respond',roundId:round.id,answers:[1,0]},403);act('employee');await survey({action:'withdrawResponse',id:response.id,evidence:'核实填写内容后先撤回答卷'});assert.equal((await expect(await selfService.GET())).tasks.filter(t=>t.kind==='surveyRound').length,1);act('hr');d=await expect(await surveys.GET());assert.equal(d.summaries[0].questions[0].average,null);assert.equal(d.summaries[0].responded,0);act('employee');await survey({action:'respond',roundId:round.id,answers:[4,1]});act('hr');await survey({action:'close',id:round.id,evidence:'本期实名问卷回收完毕结项'});act('employee');await survey({action:'respond',roundId:round.id,answers:[1,0]},400);await survey({action:'withdrawResponse',id:response.id,evidence:'结项之后不允许撤回答卷'},400);act('manager');assert.ok(!(await get()).records.some(r=>r.id===response.id));sqlite.close();
});

const cadres=await import('../app/api/cadres/route.ts');
async function cadre(command,status=200){return expect(await cadres.POST(request('/api/cadres',{revision:(await get()).revision,command})),status);}
test('P3 干部：提名独立审议、真实调动前置、任用核对与本人述职独立核验',async()=>{
 const {sqlite,e,position}=await setup();await core({action:'workflow',kind:'transfer',steps:[{userId:'manager',name:'manager'}]});const n=await cadre({action:'nominate',employeeId:e.id,positionId:position.id,evidence:'根据岗位职责和实践情况发起提名'});await cadre({action:'decide',id:n.id,accepted:true,evidence:'不能审议自己发起的提名'},403);act('employee');assert.ok(!(await get()).records.some(r=>r.id===n.id));act('manager');await cadre({action:'decide',id:n.id,accepted:true,evidence:'独立核实岗位要求及候选依据后通过'});act('owner');await cadre({action:'recordAppointment',id:n.id,approvalId:'missing',evidence:'未完成岗位调动不能核对任用'},400);assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).positionId??null,null);
 await core({action:'request',employeeId:e.id,kind:'transfer',orgId:position.orgId,positionId:position.id,reason:'干部提名审议通过，申请正式岗位调动'});const approval=(await expect(await hris.GET())).state.approvals.find(a=>a.employeeId===e.id&&a.status==='pending');await cadre({action:'recordAppointment',id:n.id,approvalId:approval.id,evidence:'待审批调动不能当作任用完成'},400);act('manager');await core({action:'decide',id:approval.id,decision:'approved'});act('owner');await cadre({action:'recordAppointment',id:n.id,approvalId:approval.id,evidence:'核对终审调动及当前岗位一致'});await cadre({action:'recordAppointment',id:n.id,approvalId:approval.id,evidence:'同一任用不能重复核对'},400);const observation=await cadre({action:'observation',nominationId:n.id,due:'2099-12-31',objectives:'完成岗位工作目标，提供真实业务成果并接受核验'});await cadre({action:'submitReview',id:observation.id,evidence:'HR不能冒充员工提交述职'},403);act('employee');assert.ok((await expect(await selfService.GET())).tasks.some(t=>t.id===observation.id));await cadre({action:'submitReview',id:observation.id,evidence:'已完成约定工作目标并提供项目验收依据'});act('owner');await cadre({action:'completeReview',id:observation.id,accepted:true,evidence:'发起考察者不能自行独立核验'},403);act('manager');await cadre({action:'returnReview',id:observation.id,evidence:'请补充目标达成的数据记录'});act('employee');await cadre({action:'submitReview',id:observation.id,evidence:'补充完整项目记录及成果验证材料'});act('manager');await cadre({action:'completeReview',id:observation.id,accepted:true,evidence:'复核目标及材料，确认考察目标达成'});assert.equal((await get()).records.find(x=>x.id===observation.id).status,'completed');assert.equal((await expect(await hris.GET())).state.employees.find(x=>x.id===e.id).status,e.status);sqlite.close();
});

const trainingSessions=await import('../app/api/training-sessions/route.ts');
async function session(command,status=200){return expect(await trainingSessions.POST(request('/api/training-sessions',{revision:(await get()).revision,command})),status);}
test('P3 培训场次：排期冲突、必修出勤门槛、独立核验、补充记录与学习结项',async()=>{
 const {sqlite,e,org}=await setup();const course=await send({action:'course',code:'CLASS',title:'线下实践课程',description:'完成现场实践并提交成果进行核验',content:'依据现场演练任务完成案例分析，提交可以核实的工作成果。'});await send({action:'publishCourse',id:course.id});const training=await send({action:'training',name:'线下实践项目',orgId:org.id,period:'2026',start:'2020-01-01',end:'2099-12-31',instructor:'测试讲师',courseIds:[course.id]});await send({action:'publishTraining',id:training.id});const scheduled={action:'session',trainingId:training.id,courseId:course.id,title:'现场演练一',startAt:'2026-01-02T09:00:00+08:00',endAt:'2026-01-02T12:00:00+08:00',location:'测试教室A',instructor:'测试讲师A',mandatory:true};const s=await session(scheduled);await session({...scheduled,title:'冲突场次'},400);act('employee');assert.ok(!(await get()).records.some(x=>x.id===s.id));const enrolled=await send({action:'enroll',trainingId:training.id,employeeId:e.id,courseId:course.id,due:'2099-12-31'});assert.ok((await expect(await trainingSessions.GET())).records.some(x=>x.id===s.id));await send({action:'submitLearning',id:enrolled.id,evidence:'已完成线下案例并提交成果待核验'});act('manager');await send({action:'verifyLearning',id:enrolled.id,accepted:true,evidence:'必修出勤尚无记录不能完成课程'},400);
 act('owner');const attendance=await session({action:'recordAttendance',sessionId:s.id,employeeId:e.id,present:false,evidence:'初始点名记录显示未出席待复核'});await session({action:'verifyAttendance',id:attendance.id,accepted:true,evidence:'出勤登记人不能自己核验'},403);act('manager');await session({action:'verifyAttendance',id:attendance.id,accepted:true,evidence:'核验初次点名记录确认为未出席'});await send({action:'verifyLearning',id:enrolled.id,accepted:true,evidence:'未出席不能满足必修场次'},400);
 act('employee');const updated=await session({action:'declare',sessionId:s.id,evidence:'补充实际参加现场练习的签到与成果材料'});assert.equal(updated.id,attendance.id);await session({action:'verifyAttendance',id:attendance.id,accepted:true,evidence:'本人不能核验自己的出席依据'},403);act('owner');await session({action:'closeSession',id:s.id,evidence:'存在待核验出勤不能直接结项'},400);act('manager');await session({action:'verifyAttendance',id:attendance.id,accepted:true,evidence:'核验补充材料，确认参加现场演练'});await send({action:'verifyLearning',id:enrolled.id,accepted:true,evidence:'必修出席与学习成果均完成核验'});act('employee');await session({action:'declare',sessionId:s.id,evidence:'已完成学习后不得再重写出勤'},400);act('owner');await session({...scheduled,title:'追加必修场次',startAt:'2026-01-03T09:00:00+08:00',endAt:'2026-01-03T12:00:00+08:00'},400);await session({action:'cancelSession',id:s.id,evidence:'已有确认出席不能直接取消'},400);await send({action:'closeTraining',id:training.id},400);await session({action:'closeSession',id:s.id,evidence:'出勤核验与现场材料归档完成'});await send({action:'closeTraining',id:training.id});assert.equal((await get()).records.find(x=>x.id===training.id).status,'closed');sqlite.close();
});

const feedback=await import('../app/api/feedback/route.ts');
async function fb(command,status=200){return expect(await feedback.POST(request('/api/feedback',{revision:(await get()).revision,command})),status);}
test('P3 360：指定评估人、人数阈值、低样本隐藏、冻结后发布及被评人不读取原始答卷',async()=>{
 const {sqlite,e,org}=await setup();const people=[];for(let i=0;i<4;i++){await core({action:'employee',code:'FB'+i,name:'反馈参与者'+i,orgId:org.id,job:'测试',level:'',email:'',joined:'2026-01-01'});const person=(await expect(await hris.GET())).state.employees.find(x=>x.code==='FB'+i);people.push(person);await grant('fb'+i,'employee',person.id);}
 const template=await survey({action:'template',code:'360T',name:'领导行为量表',description:'按可观察的日常管理行为给予反馈',questions:[{type:'rating',prompt:'能否清晰说明工作目标',lowLabel:'很少做到',highLabel:'持续做到'}]});await survey({action:'publishTemplate',id:template.id});const p=await fb({action:'project',name:'领导行为360项目',orgId:org.id,templateId:template.id,start:'2020-01-01',end:'2099-12-31',purpose:'HR可审计实名答卷，被评人只查看符合人数要求的分组汇总',minRespondents:3});const invites=[[],[]];for(let i=0;i<3;i++)for(let j=0;j<2;j++)invites[j].push(await fb({action:'invite',projectId:p.id,subjectId:j?people[3].id:e.id,reviewerEmployeeId:people[i].id,relationship:'peer'}));await fb({action:'invite',projectId:p.id,subjectId:e.id,reviewerEmployeeId:e.id,relationship:'peer'},400);act('fb0');assert.ok(!(await get()).records.some(x=>x.id===p.id));act('owner');await fb({action:'open',id:p.id});await fb({action:'publishReport',projectId:p.id,subjectId:e.id,evidence:'未锁定答卷不能提前发布报告'},400);
 for(let i=0;i<3;i++){act('fb'+i);if(i<2)await fb({action:'respond',inviteId:invites[0][i].id,answers:[i+1]});await fb({action:'respond',inviteId:invites[1][i].id,answers:[i+2]});if(i===0){await fb({action:'respond',inviteId:invites[1][1].id,answers:[5]},403);assert.ok(!(await get()).records.some(x=>x.id===invites[1][1].id));}}
 act('employee');assert.ok(!(await get()).records.some(x=>x.kind==='feedbackReply'));act('owner');await fb({action:'close',id:p.id,evidence:'按计划结束收集并锁定全部已交答卷'});act('fb0');await fb({action:'respond',inviteId:invites[0][0].id,answers:[5]},400);act('owner');const r1=await fb({action:'publishReport',projectId:p.id,subjectId:e.id,evidence:'发布低样本隐藏后的分组反馈'});const r2=await fb({action:'publishReport',projectId:p.id,subjectId:people[3].id,evidence:'发布满足人数要求的分组反馈'});await fb({action:'publishReport',projectId:p.id,subjectId:e.id,evidence:'不能重复发布生成可差分的报告'},400);
 act('employee');let d=await expect(await feedback.GET()),report=d.records.find(x=>x.id===r1.id),peer=report.payload.feedbackGroups.find(g=>g.relationship==='peer');assert.equal(peer.responses,2);assert.equal(peer.suppressed,true);assert.equal(peer.averages,null);assert.ok(!d.records.some(x=>['feedbackInvite','feedbackReply'].includes(x.kind)));assert.ok(people.slice(0,3).every(person=>!JSON.stringify(report).includes(person.id)));const history=await expect(await dev.GET(request('/api/development?id='+r1.id)));assert.equal(history.items[0].snapshot.payload.feedbackGroups.find(g=>g.relationship==='peer').averages,null);act('fb3');report=(await expect(await feedback.GET())).records.find(x=>x.id===r2.id);peer=report.payload.feedbackGroups.find(g=>g.relationship==='peer');assert.equal(peer.responses,3);assert.equal(peer.suppressed,false);assert.deepEqual(peer.averages,[3]);act('manager');assert.ok(!(await get()).records.some(x=>['feedbackReport','feedbackReply'].includes(x.kind)));sqlite.close();
});
const employeeFields=await import('../app/api/employee-fields/route.ts');
async function field(command,status=200,revision){const d=await expect(await employeeFields.GET());return expect(await employeeFields.POST(request('/api/employee-fields',{revision:revision??d.revision,command})),status);}
test('P3 自定义档案：正式值和申请隔离、字段可见范围、独立复核、类型校验与停用',async()=>{
 const {sqlite,e,other,org}=await setup();const def=await field({action:'define',code:'preferred_city',name:'意向城市',description:'员工提供后由HR复核登记',fieldType:'choice',fieldOptions:['上海','北京'],employeeRead:true,managerRead:true,employeeEditable:true});const secret=await field({action:'define',code:'hr_note',name:'内部备注',description:'仅HR可见的业务记录字段',fieldType:'text'});
 const v=await field({action:'record',definitionId:def.id,employeeId:e.id,value:'上海',evidence:'经员工提供材料核实登记'});const hidden=await field({action:'record',definitionId:secret.id,employeeId:e.id,value:'合成保密记录',evidence:'仅作权限隔离验证的合成数据'});
 act('hr');await field({action:'record',definitionId:def.id,employeeId:other.id,value:'北京',evidence:'跨组织维护必须被拒绝'},403);
 act('employee');assert.ok(!(await get()).records.some(r=>r.id===secret.id||r.id===hidden.id));await expect(await dev.GET(request('/api/development?id='+hidden.id)),403);await field({action:'propose',definitionId:def.id,value:'深圳',evidence:'选项外的值不能写入'},400);await field({action:'propose',definitionId:secret.id,value:'尝试越权',evidence:'员工不能修改内部字段'},403);await field({action:'propose',definitionId:def.id,value:'北京',evidence:'员工提出意向城市变更'});let d=await expect(await employeeFields.GET());assert.equal(d.records.find(r=>r.id===v.id).payload.fieldValue,'上海');assert.equal(d.records.find(r=>r.id===v.id).payload.pendingValue,'北京');
 act('manager');d=await expect(await employeeFields.GET());const projected=d.records.find(r=>r.id===v.id);assert.equal(projected.status,'active');assert.equal(projected.payload.fieldValue,'上海');assert.ok(!('pendingValue'in projected.payload));assert.ok(!d.records.some(r=>r.id===hidden.id));await expect(await dev.GET(request('/api/development?id='+v.id)),403);await field({action:'review',id:v.id,accepted:true,evidence:'经理不具备字段复核权限'},403);
 act('owner');await grant('employee','hr',e.id,[org.id],true);act('employee');await field({action:'review',id:v.id,accepted:true,evidence:'本人即使成为HR也不能自审'},403);await field({action:'record',definitionId:def.id,employeeId:e.id,value:'北京',evidence:'本人不能直接改写正式值'},403);
 act('hr');const rev=(await expect(await employeeFields.GET())).revision;await field({action:'review',id:v.id,accepted:true,evidence:'独立核实员工提交材料后通过'});assert.equal((await get()).records.find(r=>r.id===v.id).payload.fieldValue,'北京');await field({action:'record',definitionId:def.id,employeeId:e.id,value:'上海',evidence:'旧版本不能覆盖刚完成的复核'},409,rev);await field({action:'review',id:v.id,accepted:true,evidence:'重复复核必须被拒绝'},400);
 act('employee');await field({action:'propose',definitionId:def.id,value:null,evidence:'员工申请清空意向城市'});act('owner');await field({action:'archive',id:def.id});act('hr');await field({action:'review',id:v.id,accepted:true,evidence:'停用后不能使申请生效'},400);await field({action:'review',id:v.id,accepted:false,evidence:'字段已经停用，保留原正式值'});assert.equal((await get()).records.find(r=>r.id===v.id).payload.fieldValue,'北京');await field({action:'define',code:'PREFERRED_CITY',name:'重复编码',description:'停用之后也不能重用编码',fieldType:'text'},400);
 const date=await field({action:'define',code:'review_date',name:'核验日期',description:'记录内部核验日期信息',fieldType:'date'});await field({action:'record',definitionId:date.id,employeeId:e.id,value:'2026-02-30',evidence:'不存在的日期不得保存'},400);sqlite.close();
});
test('P3 绩效申诉：独立复核、发布分离、原快照保留、最新结果报表和历史隔离',async()=>{
 const {sqlite,e,org,otherOrg}=await setup();const cy=await perf({action:'cycle',name:'申诉验证周期',orgId:org.id,period:'APPEAL-2026',start:'2026-01-01',end:'2026-12-31',lowCut:60,highCut:80,lowLabel:'待改进',midLabel:'达成',highLabel:'优秀'});await perf({action:'startCycle',id:cy.id});act('employee');const plan=await perf({action:'goals',employeeId:e.id,cycleId:cy.id,goals:[{title:'交付质量',metric:'按已确认验收标准核对项目成果',weight:60},{title:'团队协作',metric:'按已确认共享记录核对协作成果',weight:40}]});act('manager');await perf({action:'confirmGoals',id:plan.id});act('employee');await perf({action:'selfReview',id:plan.id,evidence:'已提交本周期实际项目和协作记录'});act('manager');await perf({action:'evaluate',id:plan.id,scores:[60,70],evidence:'按已收到材料完成目标评价'});act('owner');const result=await perf({action:'publishPerformance',id:plan.id,evidence:'完成原始评价核对并发布结果'});const review=await send({action:'review',employeeId:e.id,period:'APPEAL-2026',performanceId:result.id,potential:2,evidence:'使用原始正式结果开展人才盘点'});await send({action:'publishReview',id:review.id});await perf({action:'closeCycle',id:cy.id});
 act('employee');const withdrawn=await perf({action:'appeal',resultId:result.id,evidence:'申请核对遗漏的项目验收材料'});await perf({action:'withdrawAppeal',id:withdrawn.id,evidence:'先补充完整材料，再正式提交'});const appeal=await perf({action:'appeal',resultId:result.id,evidence:'申诉私密材料：补充遗漏验收证据'});await perf({action:'appeal',resultId:result.id,evidence:'重复申诉不得创建第二个待办'},400);await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90,80],evidence:'本人不能复核自己的申诉'},403);
 act('manager');assert.ok(!(await get()).records.some(r=>r.id===appeal.id));await expect(await dev.GET(request('/api/development?id='+appeal.id)),403);act('owner');await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90,80],evidence:'原发布人不得独立复核'},403);await grant('outsidehr','hr',null,[otherOrg.id]);act('outsidehr');await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90,80],evidence:'跨组织HR不得复核申诉'},403);await grant('manager','hr',null,[org.id],true);act('manager');await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90,80],evidence:'原评价人即使成为HR也不能复核'},403);
 act('hr');await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90],evidence:'评分必须与原目标数量一致'},400);await perf({action:'reviewAppeal',id:appeal.id,accepted:true,scores:[90,80],evidence:'已独立核实补充材料，按原权重更正'});assert.equal((await get()).records.find(r=>r.id===result.id).payload.score,64);await perf({action:'publishCorrection',id:appeal.id,evidence:'复核人与发布人须分别办理'},403);act('employee');await perf({action:'withdrawAppeal',id:appeal.id,evidence:'已审结申诉不能再次撤回'},400);act('owner');const corrected=await perf({action:'publishCorrection',id:appeal.id,evidence:'核对独立复核结论后发布更正版本'});await perf({action:'publishCorrection',id:appeal.id,evidence:'重复发布不得新增第二份结果'},400);let d=await get();assert.equal(d.records.find(r=>r.id===corrected.id).payload.score,86);assert.equal(d.records.find(r=>r.id===corrected.id).payload.supersedes,result.id);assert.equal(d.records.find(r=>r.id===result.id).payload.score,64);assert.equal(d.records.find(r=>r.id===review.id).payload.performanceSnapshot.score,64);assert.equal(d.records.find(r=>r.id===plan.id).payload.score,64);assert.equal(d.records.find(r=>r.id===corrected.id).payload.performanceSnapshot.plan.goals[0].weight,60);
 await send({action:'review',employeeId:e.id,period:'APPEAL-2026',performanceId:result.id,potential:2,evidence:'更正后新盘点不得使用旧版本'},400);const report=await expect(await reports.GET(request('/api/reports?dataset=performance')));assert.equal(report.rows.length,1);assert.ok(JSON.stringify(report.rows).includes('86'));act('employee');assert.equal((await expect(await selfService.GET())).requests.find(r=>r.id===appeal.id).status,'corrected');await perf({action:'appeal',resultId:result.id,evidence:'不得对旧版本再次发起申诉'},400);const again=await perf({action:'appeal',resultId:corrected.id,evidence:'对最新结果申请第二次独立核对'});act('manager');await perf({action:'reviewAppeal',id:again.id,accepted:false,evidence:'核实原目标及证据，维持本版本结果'});assert.equal((await get()).records.find(r=>r.id===again.id).status,'upheld');await grant('manager','manager',null,[org.id],true);act('manager');const visible=(await get()).records.find(r=>r.id===corrected.id);assert.ok(!JSON.stringify(visible).includes('申诉私密材料'));sqlite.close();
});
const payrollAdjustments=await import('../app/api/payroll-adjustments/route.ts');
async function adjust(command,status=200,revision){const d=await expect(await payrollAdjustments.GET());return expect(await payrollAdjustments.POST(request('/api/payroll-adjustments',{revision:revision??d.revision,command})),status);}
test('P3 工资异议与补差：正负差额、独立复核、发布保密、原工资不变及反向冲减',async()=>{
 const {sqlite,e,org}=await setup();await grant('reviewer','admin',null);const b=await pay({action:'batch',name:'补差验证工资',orgId:org.id,period:'2026-09',currency:'CNY',policyReference:'合成核定明细仅用于验证处理规则'});const s=await pay({action:'slip',batchId:b.id,employeeId:e.id,items:[{name:'基本工资',category:'earning',amountCents:100000,source:'合成核定工资明细来源001'},{name:'扣款',category:'deduction',amountCents:10000,source:'合成核定扣款明细来源002'}]});await adjust({action:'adjustment',slipId:s.id,name:'未发布不能补差',reason:'未发布批次必须直接调整草稿',items:[{name:'补差',category:'earning',amountCents:1000,source:'合成差额依据001'}]},400);await pay({action:'submit',id:b.id,evidence:'核实基础工资条，提交复核'});act('reviewer');await pay({action:'approve',id:b.id,evidence:'独立核实合成工资条的金额'});act('owner');await pay({action:'publish',id:b.id,evidence:'发布合成工资条用于补差验证'});
 act('employee');const q=await adjust({action:'query',slipId:s.id,evidence:'合成员工发现应发项目遗漏，申请核实'});await adjust({action:'query',slipId:s.id,evidence:'重复在途异议不得新增'},400);assert.ok((await expect(await selfService.GET())).requests.some(r=>r.id===q.id&&r.title.includes('工资条异议')));await adjust({action:'answerQuery',id:q.id,evidence:'本人不能答复本人异议'},403);
 for(const user of ['hr','manager','approver']){act(user);assert.equal((await expect(await payrollAdjustments.GET())).records.length,0);await expect(await dev.GET(request('/api/development?id='+q.id)),403);}
 act('owner');const delta=[{name:'应发补差',category:'earning',amountCents:2000,source:'合成应发核定差额依据001'},{name:'退还多扣金额',category:'deduction',amountCents:-500,source:'合成个人扣款更正依据002'},{name:'企业承担调整',category:'employer',amountCents:111,source:'内部企业承担核定依据'}];const a=await adjust({action:'adjustment',slipId:s.id,name:'九月核定补差',reason:'依据员工异议及核定材料登记差额',items:delta});await adjust({action:'approveAdjustment',id:a.id,evidence:'编制人不能自行批准'},403);await adjust({action:'adjustment',slipId:s.id,name:'重复在途',reason:'已有在途补差不能重复登记',items:delta},400);act('employee');let d=await expect(await payrollAdjustments.GET());assert.ok(!d.records.some(r=>r.id===a.id));assert.equal(d.totals[0].netCents,90000);await expect(await dev.GET(request('/api/development?id='+a.id)),403);
 act('reviewer');await adjust({action:'approveAdjustment',id:a.id,evidence:'核对正负方向及核定来源，批准差额'});act('owner');await adjust({action:'answerQuery',id:q.id,adjustmentId:a.id,evidence:'不能将未发布补差当作已经完成'},400);const stale=(await get()).revision;await adjust({action:'publishAdjustment',id:a.id,evidence:'发布已独立复核的差额台账'});await adjust({action:'publishAdjustment',id:a.id,evidence:'重复发布不能重复增加金额'},400);await adjust({action:'cancelAdjustment',id:a.id,evidence:'已发布补差不能取消或抹除'},400);await adjust({action:'answerQuery',id:q.id,adjustmentId:a.id,evidence:'已核实差额并发布关联补差记录'},409,stale);await adjust({action:'answerQuery',id:q.id,adjustmentId:a.id,evidence:'已核实差额并发布关联补差记录'});
 act('employee');d=await expect(await payrollAdjustments.GET());assert.equal(d.totals[0].netCents,92500);const own=d.records.find(r=>r.id===a.id);assert.equal(own.payload.payItems.length,2);assert.ok(!JSON.stringify(own).includes('内部企业承担核定依据'));assert.ok(own.payload.payItems.every(i=>!i.source));assert.equal((await expect(await payroll.GET())).records[0].payload.netCents,90000);assert.equal((await expect(await selfService.GET())).requests.find(r=>r.id===q.id).status,'answered');await expect(await dev.GET(request('/api/development?id='+a.id)),403);await adjust({action:'withdrawQuery',id:q.id,evidence:'已答复异议不能再次撤回'},400);
 act('owner');const reverse=await adjust({action:'adjustment',slipId:s.id,name:'反向冲减',reason:'依据复核材料登记反向差额更正',items:delta.map(i=>({...i,amountCents:-i.amountCents}))});act('reviewer');await adjust({action:'approveAdjustment',id:reverse.id,evidence:'独立核对反向差额和办理依据'});await adjust({action:'publishAdjustment',id:reverse.id,evidence:'发布经核定的反向差额台账'});assert.equal((await expect(await payrollAdjustments.GET())).totals[0].netCents,90000);await grant('employee','admin',e.id,[],true);act('employee');await adjust({action:'adjustment',slipId:s.id,name:'自利更正',reason:'本人不可编制本人的工资差额',items:delta},403);sqlite.close();
});
test('P3 薪酬专用角色：编制复核分离、组织范围、核心人事隔离与撤权即时生效',async()=>{
 const {sqlite,e,other,org,otherOrg}=await setup();await grant('paywriter','payroll_editor',null,[org.id]);await grant('paychecker','payroll_reviewer',null,[org.id]);await grant('outsidepay','payroll_reviewer',null,[otherOrg.id]);act('paywriter');let d=await expect(await payroll.GET());assert.deepEqual(d.roster.employees.map(x=>x.id),[e.id]);assert.deepEqual(Object.keys(d.roster.employees[0]).sort(),['code','id','name','orgId']);assert.equal((await expect(await hris.GET())).state.employees.length,0);await expect(await members.GET(),403);await send({action:'standard',code:'NO',name:'无人才配置权限',anchors},403);await expect(await hris.POST(request('/api/hris',{revision:(await get()).revision,command:{action:'request',employeeId:e.id,kind:'regularize',orgId:org.id,reason:'薪酬人员不得申请其他员工异动'}})),403);
 await pay({action:'batch',name:'越权工资',orgId:otherOrg.id,period:'2026-10',currency:'CNY',policyReference:'不能在未授权组织建工资批次'},403);const b=await pay({action:'batch',name:'授权组织工资',orgId:org.id,period:'2026-10',currency:'CNY',policyReference:'合成数据已核定工资标准'});const items=[{name:'工资',category:'earning',amountCents:10000,source:'仅薪酬管理可见的核定依据'},{name:'企业承担',category:'employer',amountCents:333,source:'薪酬内部企业成本依据'}];const s=await pay({action:'slip',batchId:b.id,employeeId:e.id,items});act('paychecker');await pay({action:'slip',id:s.id,batchId:b.id,employeeId:e.id,items},403);act('paywriter');await pay({action:'submit',id:b.id,evidence:'编制完成提交独立复核'});await pay({action:'approve',id:b.id,evidence:'编制角色不能批准任何批次'},403);act('outsidepay');assert.equal((await expect(await payroll.GET())).records.length,0);await pay({action:'approve',id:b.id,evidence:'其他组织复核人员不能访问'},403);await expect(await dev.GET(request('/api/development?id='+s.id)),403);act('paychecker');await pay({action:'approve',id:b.id,evidence:'授权组织内独立复核通过'});await pay({action:'publish',id:b.id,evidence:'复核角色不承担发布动作'},403);act('paywriter');await pay({action:'publish',id:b.id,evidence:'由编制人员核对批准后发布'});assert.ok((await expect(await dev.GET(request('/api/development?id='+s.id)))).items.length);
 const a=await adjust({action:'adjustment',slipId:s.id,name:'组织内补差',reason:'按核定材料登记工资差额',items:[{name:'差额',category:'earning',amountCents:100,source:'薪酬补差核定依据'}]});await adjust({action:'approveAdjustment',id:a.id,evidence:'编制角色不得批准补差'},403);act('paychecker');await adjust({action:'approveAdjustment',id:a.id,evidence:'独立复核薪酬差额及来源'});await adjust({action:'publishAdjustment',id:a.id,evidence:'复核角色不能发布补差'},403);act('paywriter');await adjust({action:'publishAdjustment',id:a.id,evidence:'批准之后发布薪酬差额'});
 await grant('employee','payroll_editor',e.id,[otherOrg.id],true);act('employee');d=await expect(await payroll.GET());const own=d.records.find(r=>r.id===s.id);assert.ok(own);assert.equal(own.payload.payItems.length,1);assert.ok(own.payload.payItems.every(i=>!i.source));assert.ok(!d.managedIds.includes(s.id));await expect(await dev.GET(request('/api/development?id='+s.id)),403);assert.deepEqual((await expect(await hris.GET())).state.employees.map(x=>x.id),[e.id]);const adjustments=await expect(await payrollAdjustments.GET());assert.ok(!JSON.stringify(adjustments.records.find(x=>x.id===a.id)).includes('薪酬补差核定依据'));assert.equal(adjustments.totals[0].employerCents,undefined);
 await grant('paywriter','hr',null,[org.id],true);act('paywriter');assert.equal((await expect(await payroll.GET())).records.length,0);await expect(await dev.GET(request('/api/development?id='+a.id)),403);await adjust({action:'adjustment',slipId:s.id,name:'撤权后的请求',reason:'撤销薪酬角色后不能继续写入',items:[{name:'差额',category:'earning',amountCents:1,source:'撤权验证的合成依据'}]},403);sqlite.close();
});
const learningCredits=await import('../app/api/learning-credits/route.ts');
async function credit(command,status=200,revision){const d=await expect(await learningCredits.GET());return expect(await learningCredits.POST(request('/api/learning-credits',{revision:revision??d.revision,command})),status);}
test('P3 学习学分：课程版本固定、成果核验前置、授予唯一、独立撤销及范围隔离',async()=>{
 const {sqlite,e,other}=await setup();const course=await send({action:'course',code:'CREDIT',title:'学分验证课程',description:'完成课程实践后核验学习成果',content:'阅读学习案例并完成实际练习，提交成果材料，由独立管理人员核验后登记学分。'});const policy=await credit({action:'policy',courseId:course.id,creditUnits:125,evidence:'依据合成课程学分标准配置'});await credit({action:'policy',courseId:course.id,creditUnits:200,evidence:'同课程版本不能重复配置学分'},400);act('employee');assert.ok(!(await get()).records.some(r=>r.id===policy.id));await expect(await dev.GET(request('/api/development?id='+policy.id)),403);act('owner');await send({action:'publishCourse',id:course.id});const enrollment=await send({action:'enroll',courseId:course.id,employeeId:e.id,due});const otherEnrollment=await send({action:'enroll',courseId:course.id,employeeId:other.id,due});await credit({action:'award',enrollmentId:enrollment.id,evidence:'未完成核验不能登记学分'},400);act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'已完成课程练习并提交实践证据'});act('manager');await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'独立核实实践成果，确认完成学习'});await credit({action:'award',enrollmentId:enrollment.id,evidence:'经理不具有学分台账写入权限'},403);act('hr');await credit({action:'award',enrollmentId:otherEnrollment.id,evidence:'不能为其他组织员工登记学分'},403);act('owner');const award=await credit({action:'award',enrollmentId:enrollment.id,evidence:'核对课程版本及学习完成记录'});await credit({action:'award',enrollmentId:enrollment.id,evidence:'不得重复授予同一学习记录'},400);await credit({action:'reverse',awardId:award.id,evidence:'授予人不得独立撤销自己的记录'},403);act('employee');let d=await expect(await learningCredits.GET());assert.equal(d.summary[0].netUnits,125);assert.ok(d.records.some(r=>r.id===award.id));await credit({action:'reverse',awardId:award.id,evidence:'员工不能撤销本人的学分'},403);act('hr');const stale=(await get()).revision;await credit({action:'reverse',awardId:award.id,evidence:'独立核实登记依据有误，撤销学分'});await credit({action:'reverse',awardId:award.id,evidence:'重复撤销不能产生负学分'},400);d=await expect(await learningCredits.GET());assert.equal(d.summary[0].netUnits,0);assert.equal(d.summary[0].awardedUnits,125);assert.equal(d.summary[0].reversedUnits,125);assert.equal((await get()).records.find(r=>r.id===enrollment.id).status,'completed');await credit({action:'award',enrollmentId:enrollment.id,evidence:'已撤销的原学习记录也不能重复授予'},400);const next=await send({action:'course',code:'CREDIT',title:'学分验证课程新版',description:'新版本采用独立的课程要求',content:'新版本课程使用独立要求，完成案例实践并提交成果，由管理人员独立核验学习效果。'});await credit({action:'policy',courseId:next.id,creditUnits:200,evidence:'旧版本快照不得覆盖并发更新'},409,stale);await credit({action:'policy',courseId:next.id,creditUnits:200,evidence:'新课程版本独立配置学分标准'});assert.equal((await get()).records.find(r=>r.id===policy.id).payload.creditUnits,125);sqlite.close();
});
const instructors=await import('../app/api/instructors/route.ts');
async function instructor(command,status=200,revision){return expect(await instructors.POST(request('/api/instructors',{revision:revision??(await get()).revision,command})),status);}
test('P3：讲师认证独立复核、组织隔离、课程版本和期限约束、排期快照及撤销',async()=>{
 const {sqlite,e,other,org}=await setup();const course=await send({action:'course',code:'TEACH',title:'讲师实践课程',description:'通过课程试讲与独立核验取得内部认证',content:'准备完整试讲案例，提交可核实的授课实践材料，由其他HR复核。'});await send({action:'publishCourse',id:course.id});const t=await send({action:'training',name:'讲师排期测试项目',orgId:org.id,period:'2099',start:'2099-01-01',end:due,instructor:'尚未排期',courseIds:[course.id]});await send({action:'publishTraining',id:t.id});
 const input={action:'submit',employeeId:e.id,courseId:course.id,start:'2099-01-01',end:'2099-06-30',evidence:'试讲材料编号 TEST-INSTRUCTOR-001'};act('employee');await instructor({...input,employeeId:other.id},403);await instructor({...input,start:'2099-02-30'},400);const cert=await instructor(input);await instructor(input,400);await instructor({action:'review',id:cert.id,accepted:true,evidence:'本人不能审批自己提交的认证'},403);
 act('manager');assert.ok(!(await expect(await instructors.GET())).records.some(r=>r.id===cert.id));await expect(await dev.GET(request('/api/development?id='+cert.id)),403);act('hr');const approved=await instructor({action:'review',id:cert.id,accepted:true,evidence:'独立核实试讲材料与授课实践'});await instructor({action:'review',id:cert.id,accepted:true,evidence:'重复审批不得再次办理'},400);
 const base={action:'session',trainingId:t.id,courseId:course.id,title:'认证讲师第一场',startAt:'2099-02-01T09:00:00+08:00',endAt:'2099-02-01T12:00:00+08:00',location:'培训室一',instructor:'客户端伪造讲师姓名',instructorCertificationId:cert.id,mandatory:false};const s=await session(base);let d=await expect(await trainingSessions.GET());assert.equal(d.records.find(r=>r.id===s.id).payload.instructor,e.name);assert.equal(d.records.find(r=>r.id===s.id).payload.instructorCertificationId,cert.id);assert.ok(!d.records.find(r=>r.id===s.id).payload.evidence);await session({...base,title:'冲突排期',location:'不同场地'},400);await session({...base,startAt:'2099-06-30T23:00:00+08:00',endAt:'2099-07-01T01:00:00+08:00'},400);
 const later=await instructor({...input,start:'2099-07-01',end:due});await instructor({action:'review',id:later.id,accepted:true,evidence:'提交人不能复核自己的申请'},403);act('owner');await instructor({action:'review',id:later.id,accepted:true,evidence:'另一HR核实后批准续期认证'});act('employee');await instructor({action:'withdraw',id:cert.id,evidence:'已通过的认证不能撤回'},400);act('owner');await instructor({action:'revoke',id:cert.id,evidence:'课程安排调整，撤销认证并人工复核后续排期'});await session({...base,startAt:'2099-03-01T09:00:00+08:00',endAt:'2099-03-01T12:00:00+08:00'},400);d=await expect(await trainingSessions.GET());assert.equal(d.records.find(r=>r.id===s.id).payload.instructorCertifiedEnd,'2099-06-30');assert.equal(d.records.find(r=>r.id===s.id).status,'active');
 const revision=(await get()).revision;const fresh=await instructor({...input,start:'2099-01-01',end:'2099-06-30'});await instructor({action:'withdraw',id:fresh.id,evidence:'验证过期版本不能写入'},409,revision);await instructor({action:'withdraw',id:fresh.id,evidence:'课程准备计划调整，撤回重新安排'});act('employee');const history=await expect(await dev.GET(request('/api/development?id='+cert.id)));assert.equal(history.items.length,3);act('approver');assert.ok(!(await expect(await instructors.GET())).records.some(r=>r.id===cert.id));
 act('owner');const version=await send({action:'course',code:'TEACH',title:'讲师课程第二版',description:'升级内容后须重新认证课程版本',content:'本次升级增加案例与教学标准，原课程版本认证不自动迁移。'});await send({action:'publishCourse',id:version.id});const t2=await send({action:'training',name:'新版课程培训',orgId:org.id,period:'2099',start:'2099-01-01',end:due,instructor:'测试讲师',courseIds:[version.id]});await send({action:'publishTraining',id:t2.id});await session({...base,trainingId:t2.id,courseId:version.id,instructorCertificationId:later.id,startAt:'2099-08-01T09:00:00+08:00',endAt:'2099-08-01T12:00:00+08:00'},400);act('hr');await instructor({...input,employeeId:other.id},403);sqlite.close();
});
test('P3 假勤联调：等价时区使用同一业务日与余额年度，取消请假后释放班次',async()=>{
 const {sqlite,e}=await setup();await attend({action:'shift',employeeId:e.id,date:'2098-12-31',name:'错误时区日期',startAt:'2098-12-31T16:00:00Z',endAt:'2098-12-31T18:00:00Z'},400);const s=await attend({action:'shift',employeeId:e.id,date:'2099-01-01',name:'跨时区同一时刻',startAt:'2098-12-31T16:00:00Z',endAt:'2098-12-31T18:00:00Z'});const type=await attend({action:'leaveType',code:'TZ-LEAVE',name:'合成年度假',paid:true,requiresBalance:true});await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2098,minutes:120,source:'旧年度测试余额不能被错误使用'});act('employee');const leave={action:'leave',employeeId:e.id,shiftId:s.id,leaveTypeId:type.id,startAt:'2099-01-01T00:00:00+08:00',endAt:'2099-01-01T02:00:00+08:00',reason:'验证业务年度统一使用北京时间'};await attend(leave,400);act('owner');await attend({action:'leaveCredit',employeeId:e.id,leaveTypeId:type.id,year:2099,minutes:120,source:'新年度测试余额提供正确归属'});act('employee');const l=await attend(leave);act('hr');await attend({action:'decideLeave',id:l.id,accepted:true,evidence:'独立核实此次测试请假申请'});await attend({action:'cancelShift',id:s.id,reason:'有效请假存在时不允许取消班次'},400);await attend({action:'cancelApprovedLeave',id:l.id,reason:'行程变更取消全部已批准请假'});await attend({action:'cancelShift',id:s.id,reason:'请假已取消且无打卡补卡，可撤销班次'});assert.equal((await get()).records.find(r=>r.id===s.id).status,'cancelled');sqlite.close();
});
const onboarding=await import('../app/api/onboarding/route.ts');
async function onboard(command,status=200,revision){return expect(await onboarding.POST(request('/api/onboarding',{revision:revision??(await get()).revision,command})),status);}
test('P3 入职融入：模板版本快照、本人办理、独立核验、结项及自助待办',async()=>{
 const {sqlite,e,other}=await setup();const t=await onboard({action:'template',code:'JOIN',title:'新员工融入',items:['阅读岗位职责','完成安全培训']});act('employee');assert.ok(!(await expect(await onboarding.GET())).records.some(r=>r.id===t.id));await onboard({action:'publish',id:t.id},403);act('owner');await onboard({action:'assign',templateId:t.id,employeeId:e.id,due,evidence:'尚未发布模板不可指派'},400);await onboard({action:'publish',id:t.id});const p=await onboard({action:'assign',templateId:t.id,employeeId:e.id,due,evidence:'按岗位安排本次入职融入计划'});await onboard({action:'assign',templateId:t.id,employeeId:e.id,due,evidence:'同员工不可重复指派活跃计划'},400);let d=await get(),items=d.records.find(r=>r.id===p.id).payload.onboardingItems;await onboard({action:'submit',id:p.id,itemId:items[0].id,evidence:'他人不得代替员工本人确认办理'},403);await onboard({action:'close',id:p.id,evidence:'未完成核验不得结项'},400);
 act('employee');assert.ok((await expect(await (await import('../app/api/self-service/route.ts')).GET())).tasks.some(r=>r.id===p.id));await onboard({action:'submit',id:p.id,itemId:items[0].id,evidence:'已阅读岗位职责并完成问题清单'});await onboard({action:'verify',id:p.id,itemId:items[0].id,accepted:true,evidence:'本人不能自审自己的办理事项'},403);act('manager');await onboard({action:'verify',id:p.id,itemId:items[0].id,accepted:false,evidence:'请补充职责边界和协同对象说明'});act('employee');await onboard({action:'submit',id:p.id,itemId:items[0].id,evidence:'已补充职责边界和协同对象说明'});act('manager');await onboard({action:'verify',id:p.id,itemId:items[0].id,accepted:true,evidence:'独立核实补充说明，符合要求'});act('owner');const t2=await onboard({action:'template',code:'JOIN',title:'新版融入模板',items:['新增事项']});await onboard({action:'publish',id:t2.id});await onboard({action:'archive',id:t.id});assert.equal((await get()).records.find(r=>r.id===p.id).payload.onboardingItems.length,2);
 act('employee');await onboard({action:'submit',id:p.id,itemId:items[1].id,evidence:'已经完成安全培训并提交结果依据'});act('manager');await onboard({action:'verify',id:p.id,itemId:items[1].id,accepted:true,evidence:'已独立核对培训完成结果'});await onboard({action:'close',id:p.id,evidence:'普通经理不能代替HR结项'},403);act('hr');await onboard({action:'assign',templateId:t2.id,employeeId:other.id,due,evidence:'不得跨组织指派其他员工'},403);const rev=(await get()).revision;await onboard({action:'close',id:p.id,evidence:'全部事项独立核验完成，确认结项'});await onboard({action:'cancel',id:p.id,evidence:'过期版本不得覆盖结项结果'},400);act('employee');await onboard({action:'submit',id:p.id,itemId:items[0].id,evidence:'结项后不能改写办理记录'},400);assert.ok(!(await expect(await (await import('../app/api/self-service/route.ts')).GET())).tasks.some(r=>r.id===p.id));const h=await expect(await dev.GET(request('/api/development?id='+p.id)));assert.ok(h.items.some(x=>x.snapshot.payload.onboardingItems.some(i=>i.status==='returned')));act('approver');await expect(await dev.GET(request('/api/development?id='+p.id)),403);act('owner');await onboard({action:'assign',templateId:t2.id,employeeId:other.id,due,evidence:'旧版本请求应被拒绝'},409,rev);sqlite.close();
});
const inbox=await import('../app/api/work-inbox/route.ts');
async function queue(params='',status=200){return expect(await inbox.GET(request('/api/work-inbox'+params)),status);}
test('P3 待办工作台：顺序审批轮次、本人隔离、跨组织筛选、分页和办理后消退',async()=>{
 const {sqlite,e,other,org}=await setup();await core({action:'workflow',kind:'regularize',steps:[{userId:'approver',name:'第一审批人'},{userId:'manager',name:'第二审批人'}]});const t=await onboard({action:'template',code:'QUEUE',title:'待办分页计划',items:Array.from({length:21},(_,i)=>'办理事项'+(i+1))});await onboard({action:'publish',id:t.id});const p=await onboard({action:'assign',templateId:t.id,employeeId:e.id,due,evidence:'用于验证真实多事项待办分页'});const items=(await get()).records.find(r=>r.id===p.id).payload.onboardingItems;act('employee');await core({action:'request',employeeId:e.id,kind:'regularize',orgId:org.id,reason:'试用期申请测试'});for(const item of items)await onboard({action:'submit',id:p.id,itemId:item.id,evidence:'已经办理并提供合成验收依据'});assert.equal((await queue()).total,0);act('manager');let d=await queue();assert.equal(d.total,21);assert.equal(d.items.length,20);assert.equal(d.hasMore,true);assert.equal(d.counts.personnel,undefined);assert.equal((await queue('?page=2')).items.length,1);assert.equal((await queue('?q='+encodeURIComponent('办理事项21'))).total,1);await queue('?page=0',400);await queue('?domain=invalid',400);assert.ok(!JSON.stringify(d).includes('已经办理并提供合成验收依据'));
 act('approver');d=await queue();assert.equal(d.total,1);assert.equal(d.items[0].domain,'personnel');const a=d.items[0].recordId;await core({action:'decide',id:a,decision:'approved'});assert.equal((await queue()).total,0);act('manager');assert.equal((await queue('?domain=personnel')).total,1);await core({action:'decide',id:a,decision:'approved'});assert.equal((await queue('?domain=personnel')).total,0);await onboard({action:'verify',id:p.id,itemId:items[0].id,accepted:false,evidence:'请补充办理事项所需的依据'});assert.equal((await queue()).total,20);
 act('owner');const out=await onboard({action:'assign',templateId:t.id,employeeId:other.id,due,evidence:'其他组织计划应当隔离'});await grant('otheremployee','employee',other.id);act('otheremployee');const outItems=(await get()).records.find(r=>r.id===out.id).payload.onboardingItems;await onboard({action:'submit',id:out.id,itemId:outItems[0].id,evidence:'其他组织的保密办理依据'});act('manager');assert.ok(!(await queue()).items.some(r=>r.recordId===out.id));act('hr');assert.equal((await queue()).total,20);await grant('manager','approver',null,[org.id],true);act('manager');assert.equal((await queue()).total,0);sqlite.close();
});
test('P3 扩展待办：薪酬角色保密、绩效环节和招聘独立审批流转',async()=>{
 const {sqlite,e,org,otherOrg,position}=await setup();await grant('writer','payroll_editor',null,[org.id]);await grant('checker','payroll_reviewer',null,[org.id]);await grant('outside','payroll_reviewer',null,[otherOrg.id]);act('writer');const b=await pay({action:'batch',name:'保密批次',orgId:org.id,period:'2026-11',currency:'CNY',policyReference:'内部工资标准不得进入待办摘要'});const s=await pay({action:'slip',batchId:b.id,employeeId:e.id,items:[{name:'核定工资',category:'earning',amountCents:987654,source:'保密工资核算来源'}]});await pay({action:'submit',id:b.id,evidence:'已核对明细，提交独立复核'});assert.equal((await queue('?domain=payroll')).total,0);act('hr');assert.equal((await queue('?domain=payroll')).total,0);act('outside');assert.equal((await queue('?domain=payroll')).total,0);act('checker');let d=await queue('?domain=payroll');assert.equal(d.total,1);assert.equal(d.items[0].action,'工资批次复核');assert.ok(!JSON.stringify(d).includes('987654'));assert.ok(!JSON.stringify(d).includes('保密工资核算来源'));await pay({action:'approve',id:b.id,evidence:'独立核实薪酬明细通过'});assert.equal((await queue('?domain=payroll')).total,0);act('writer');assert.equal((await queue('?domain=payroll')).items[0].action,'工资批次发布');await pay({action:'publish',id:b.id,evidence:'批准后向员工发布工资条'});act('employee');await adjust({action:'query',slipId:s.id,evidence:'请核实本期工资项目依据'});assert.equal((await queue()).total,0);act('writer');assert.equal((await queue('?domain=payroll')).items[0].action,'工资异议答复');
 act('owner');const cycle=await perf({action:'cycle',name:'待办考核周期',orgId:org.id,period:'2026-WORK',start:'2026-01-01',end:'2099-12-31',lowCut:60,highCut:80,lowLabel:'待提升',midLabel:'达标',highLabel:'优秀'});await perf({action:'startCycle',id:cycle.id});const plan=await perf({action:'goals',employeeId:e.id,cycleId:cycle.id,goals:[{title:'岗位任务',metric:'完成指定任务并提供完整结果依据',weight:100}]});act('manager');assert.equal((await queue('?domain=performance')).items[0].action,'绩效目标确认');await perf({action:'confirmGoals',id:plan.id});assert.equal((await queue('?domain=performance')).total,0);act('employee');await perf({action:'selfReview',id:plan.id,evidence:'已完成任务并提供本人自评依据'});act('manager');assert.equal((await queue('?domain=performance')).items[0].action,'绩效评价');await perf({action:'evaluate',id:plan.id,scores:[80],evidence:'独立核实任务结果并完成评分'});assert.equal((await queue('?domain=performance')).total,0);act('hr');assert.equal((await queue('?domain=performance')).items[0].action,'绩效结果发布');await perf({action:'publishPerformance',id:plan.id,evidence:'HR核对完成发布正式结果'});assert.equal((await queue('?domain=performance')).total,0);
 const req=await recruit({action:'requisition',positionId:position.id,title:'待审批岗位需求',headcount:1,reason:'合成业务用于验证需求审批待办'});assert.equal((await queue('?domain=recruitment')).total,0);act('manager');assert.equal((await queue('?domain=recruitment')).items[0].recordId,req.id);await recruit({action:'approveRequisition',id:req.id});act('hr');const candidate=await recruit({action:'candidate',requisitionId:req.id,name:'合成候选人',email:'',source:'内部合成候选人来源'});await recruit({action:'interview',candidateId:candidate.id,rating:4,recommendation:'advance',evidence:'面试通过，建议进入录用流程'});await recruit({action:'offer',id:candidate.id,joined:'2026-09-01',evidence:'按岗位要求发起录用审批'});assert.equal((await queue('?domain=recruitment')).total,0);act('manager');assert.equal((await queue('?domain=recruitment')).items[0].action,'录用审批');await recruit({action:'approveOffer',id:candidate.id});act('hr');assert.equal((await queue('?domain=recruitment')).items[0].action,'录用接受确认');await recruit({action:'acceptOffer',id:candidate.id,evidence:'候选人书面确认接受录用安排'});assert.equal((await queue('?domain=recruitment')).total,0);sqlite.close();
});
