import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,grant,dev} from './support/foundation-scenario.mjs';
const payroll=await import('../app/api/payroll/route.ts'),attendance=await import('../app/api/attendance/route.ts'),periods=await import('../app/api/attendance-periods/route.ts');
async function post(api,command,status=200,revision){return expect(await api.POST(request('/api/test',{revision:revision??(await get()).revision,command})),status);}
const pay=(c,s,r)=>post(payroll,c,s,r),period=(c,s)=>post(periods,c,s);
async function fixture(){const f=await setup();await grant('payWriter','payroll_editor',null,[f.org.id]);await grant('payReviewer','payroll_reviewer',null,[f.org.id]);const shift=await post(attendance,{action:'shift',employeeId:f.e.id,date:'2026-01-05',name:'合成核薪来源班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00'}),type=await post(attendance,{action:'leaveType',code:'PAY-REF',name:'合成已核验假',paid:true,requiresBalance:false});act('employee');const leave=await post(attendance,{action:'leave',employeeId:f.e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'合成已核定假勤依据用于工资引用'});act('manager');await post(attendance,{action:'decideLeave',id:leave.id,accepted:true,evidence:'独立核实合成休假来源'});act('owner');const p=await period({action:'freeze',employeeId:f.e.id,start:'2026-01-05',end:'2026-01-06',evidence:'冻结合成核薪参考期间，来源完整'});act('payWriter');const b=await pay({action:'batch',name:'合成引用核薪',orgId:f.org.id,period:'2026-01',currency:'CNY',policyReference:'仅核定金额测试，不计算税费或付款'});return {...f,p,b};}
const slip=f=>({action:'slip',batchId:f.b.id,employeeId:f.e.id,attendancePeriodIds:[f.p.id],items:[{name:'合成已核定工资',category:'earning',amountCents:123456,source:'按合成核定单录入，不根据请假分钟自动扣薪'}]});
test('payroll references only permitted frozen aggregates; amounts and employee masking remain independent',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());const d=await expect(await payroll.GET());assert.equal(d.attendanceSources.length,1);assert.equal(d.attendanceSources[0].approvedLeaveMinutes,540);assert.equal(d.attendanceSources[0].rows,undefined);assert.equal(d.attendanceSources[0].sources,undefined);const s=await pay(slip(f));assert.equal((await expect(await payroll.GET())).records.find(r=>r.id===s.id).payload.netCents,123456);await pay({action:'submit',id:f.b.id,evidence:'提交已核对金额及考勤引用'});act('payReviewer');await pay({action:'approve',id:f.b.id,evidence:'独立核对金额与来源快照'});act('payWriter');await pay({action:'publish',id:f.b.id,evidence:'仅内部工资条发布，不触发付款'});act('employee');const mine=await expect(await payroll.GET());assert.deepEqual(mine.attendanceSources,[]);assert.deepEqual(mine.attendanceIssues,{});assert.equal(mine.records.find(r=>r.id===s.id).payload.payrollAttendance,undefined);assert.equal(mine.records.find(r=>r.id===s.id).payload.netCents,123456);});
test('reopening or refreezing a source blocks submission and approval until an explicit draft refresh',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());const s=await pay(slip(f));act('owner');await period({action:'reopen',id:f.p.id,reason:'考勤出现新依据，需要重新核实'});act('payWriter');await pay({action:'submit',id:f.b.id,evidence:'旧来源不可继续提交复核'},409);act('owner');await period({action:'refreeze',id:f.p.id,evidence:'再次核对来源后生成新版冻结'});act('payWriter');await pay({action:'submit',id:f.b.id,evidence:'同ID新版不得冒充原冻结依据'},409);await pay({...slip(f),id:s.id});await pay({action:'submit',id:f.b.id,evidence:'重新引用最新冻结版本后提交'});act('owner');await period({action:'reopen',id:f.p.id,reason:'复核前出现新证据需要开放'});act('payReviewer');await pay({action:'approve',id:f.b.id,evidence:'不能批准旧考勤来源的工资批次'},409);await pay({action:'return',id:f.b.id,evidence:'退回编制核对新来源，保留原证据'});const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+s.id)));assert.ok(history.items.some(e=>e.snapshot.payload.payrollAttendance?.[0]?.version===1));assert.ok(history.items.some(e=>e.snapshot.payload.payrollAttendance?.[0]?.version===2));});
test('changed sources block approved publication; changes after publishing flag follow-up without rewriting money',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());const s=await pay(slip(f));await pay({action:'submit',id:f.b.id,evidence:'合成金额和来源提交独立复核'});act('payReviewer');await pay({action:'approve',id:f.b.id,evidence:'独立核验来源与核定金额'});act('owner');await period({action:'reopen',id:f.p.id,reason:'发布前核实考勤新情况'});act('payWriter');await pay({action:'publish',id:f.b.id,evidence:'已批准也不能忽略来源变化'},409);act('payReviewer');await pay({action:'return',id:f.b.id,evidence:'退回更正原始依据再重新复核'});act('owner');await period({action:'refreeze',id:f.p.id,evidence:'重新核实来源冻结为下一版本'});act('payWriter');await pay({...slip(f),id:s.id});await pay({action:'submit',id:f.b.id,evidence:'更正后重新提交独立复核'});act('payReviewer');await pay({action:'approve',id:f.b.id,evidence:'再次独立确认更新后的依据'});act('payWriter');await pay({action:'publish',id:f.b.id,evidence:'更新后的来源确认后发布工资条'});act('owner');await period({action:'reopen',id:f.p.id,reason:'发布后新证据须另行补差核对'});act('payWriter');const d=await expect(await payroll.GET());assert.equal(d.records.find(r=>r.id===s.id).payload.netCents,123456);assert.equal(d.records.find(r=>r.id===f.b.id).status,'published');assert.equal(d.attendanceIssues[s.id].length,1);});
test('duplicate, foreign employee and wrong-month references reject; audit failure rolls back the entire slip',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());await pay({...slip(f),attendancePeriodIds:[f.p.id,f.p.id]},400);await pay({...slip(f),attendancePeriodIds:['missing-source']},403);await pay({...slip(f),employeeId:f.other.id},400);const b=await pay({action:'batch',name:'合成二月',orgId:f.org.id,period:'2026-02',currency:'CNY',policyReference:'核验来源必须位于同一计薪月份'});await pay({...slip(f),batchId:b.id},400);const revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER fail_pay_ref BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await pay(slip(f),503);f.sqlite.exec('DROP TRIGGER fail_pay_ref');assert.equal((await get()).revision,revision);assert.equal((await expect(await payroll.GET())).records.filter(r=>r.kind==='paySlip').length,0);act('hr');assert.deepEqual((await expect(await payroll.GET())).attendanceSources,[]);act('employee');assert.deepEqual((await expect(await payroll.GET())).attendanceSources,[]);});
