import './support/runtime.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const cryptoTools=await import('../lib/hris/r1-recovery-crypto.ts'),{digest}=await import('../lib/hris/r1-command.ts'),{byteDigest}=await import('../lib/hris/r1-migration-attachments.ts'),{migrationFiles,schemaObjects}=await import('../lib/hris/r1-schema-manifest.ts');
async function vault(id='synthetic-independent-vault'){const wrapping=await crypto.subtle.generateKey({name:'AES-KW',length:256},false,['wrapKey','unwrapKey']),signing=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},false,['sign','verify']);return new cryptoTools.WebCryptoRecoveryVault(id,wrapping,signing.privateKey,signing.publicKey);}
function store(){const values=new Map();return {values,async putIfAbsent(key,bytes){if(values.has(key)){if(await byteDigest(values.get(key))!==await byteDigest(bytes))throw Error('IMMUTABLE_CONFLICT');return;}values.set(key,new Uint8Array(bytes));},async get(key){return values.has(key)?new Uint8Array(values.get(key)):null;}};}
async function base(v,s,pieces){const data=await v.createDataKey(),id=crypto.randomUUID(),chunks=await cryptoTools.writeRecoveryChunks(id,data.key,(async function*(){for(const bytes of pieces)yield {kind:'baseline',sourceId:'synthetic-table',bytes};})(),s);return {manifestVersion:1,checkpointId:id,sourceSha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),lockDigest:await byteDigest(readFileSync('package-lock.json')),schemaDigest:await digest(schemaObjects),ddlFiles:migrationFiles,kind:'baseline',parentCheckpoint:null,parentDigest:null,fromSeq:0,toSeq:0,takenAt:new Date().toISOString(),tenantRevisions:{synthetic:1},securityLedger:{revision:1,digest:await digest({synthetic:true}),verifiedAt:new Date().toISOString()},keyId:v.keyId,wrappedKey:data.wrappedKey,chunks,tableCounts:{'synthetic-table':pieces.length},objects:[],excludedTables:[],retainedUntil:new Date(Date.now()+31*86400000).toISOString()};}
test('P3-REC-01/04: bounded AES-256-GCM chunks roundtrip with separate wrapped key and independent signature, preserving exact byte boundaries',async()=>{const v=await vault(),s=store(),input=[new Uint8Array(4*1024*1024).fill(7),new TextEncoder().encode('隔离合成：null与0不同')],m=await base(v,s,input),signed=await cryptoTools.sealRecoveryManifest(m,v,s),verified=await cryptoTools.verifyRecoveryManifest(signed,v,s),key=await v.unwrapDataKey(m.wrappedKey);assert.equal(verified.digest,signed.digest);assert.equal(m.chunks[0].plaintextBytes,4*1024*1024);assert.notEqual(m.chunks[0].nonce,m.chunks[1].nonce);for(let i=0;i<input.length;i++)assert.deepEqual(await cryptoTools.decryptRecoveryChunk(m.checkpointId,key,m.chunks[i],await s.get(m.chunks[i].key)),input[i]);assert.equal(JSON.stringify(signed).includes('privateKey'),false);await assert.rejects(cryptoTools.encryptRecoveryChunk('too-big',key,0,'baseline','table',new Uint8Array(4*1024*1024+1),null),e=>e.machineCode==='RECOVERY_CHUNK_BUDGET');});
test('P3-REC-01/04: corruption, missing chunk, bad signature, wrong key and cross-checkpoint AAD fail before publication or restore',async()=>{const v=await vault(),s=store(),m=await base(v,s,[new Uint8Array([1,2,3]),new Uint8Array([4])]),signed=await cryptoTools.sealRecoveryManifest(m,v,s),key=await v.unwrapDataKey(m.wrappedKey);const bad=structuredClone(signed);bad.manifest.tenantRevisions.synthetic=2;await assert.rejects(cryptoTools.verifyRecoveryManifest(bad,v,s),e=>e.machineCode==='RECOVERY_MANIFEST_UNTRUSTED');await assert.rejects(cryptoTools.verifyRecoveryManifest(signed,await vault(),s),e=>e.machineCode==='RECOVERY_MANIFEST_UNTRUSTED');await assert.rejects(cryptoTools.decryptRecoveryChunk('another-checkpoint',key,m.chunks[0],await s.get(m.chunks[0].key)),e=>e.machineCode==='RECOVERY_AUTHENTICATION_FAILED');const bytes=s.values.get(m.chunks[0].key);bytes[0]^=1;await assert.rejects(cryptoTools.verifyRecoveryManifest(signed,v,s),e=>e.machineCode==='RECOVERY_CHUNK_CORRUPT');s.values.delete(m.chunks[0].key);await assert.rejects(cryptoTools.verifyRecoveryManifest(signed,v,s),e=>e.machineCode==='RECOVERY_OBJECT_MISSING');const missing=await base(v,store(),[new Uint8Array([3])]);await assert.rejects(cryptoTools.sealRecoveryManifest(missing,v,s),e=>e.machineCode==='RECOVERY_OBJECT_MISSING');assert.equal(s.values.has(missing.checkpointId+'/manifest'),false);});
test('P3-REC-01/05: tombstoned multi-chunk object requires complete ordered references and whole-object SHA before verified manifest',async()=>{const v=await vault(),s=store(),m=await base(v,s,[]),data=await v.createDataKey(),bytes=[new Uint8Array([1,2]),new Uint8Array([3,4])];m.wrappedKey=data.wrappedKey;m.chunks=await cryptoTools.writeRecoveryChunks(m.checkpointId,data.key,(async function*(){for(const b of bytes)yield {kind:'object',sourceId:'synthetic/tombstone',bytes:b};})(),s);m.objects=[{key:'synthetic/tombstone',versionId:'immutable-v1',byteCount:4,digest:await byteDigest(new Uint8Array([1,2,3,4])),mime:'application/octet-stream',owner:'synthetic-tenant',tombstone:true,chunks:[0,1]}];const bad=structuredClone(m);bad.objects[0].digest='0'.repeat(64);await assert.rejects(cryptoTools.sealRecoveryManifest(bad,v,s),e=>e.machineCode==='RECOVERY_OBJECT_HASH_MISMATCH');assert.equal(s.values.has(m.checkpointId+'/manifest'),false);const partial=structuredClone(m);partial.objects[0].chunks=[0];await assert.rejects(cryptoTools.sealRecoveryManifest(partial,v,s),e=>e.machineCode==='RECOVERY_OBJECT_MANIFEST_INVALID');const verified=await cryptoTools.sealRecoveryManifest(m,v,s);assert.equal(verified.manifest.objects[0].tombstone,true);assert.equal(s.values.has(m.checkpointId+'/0'),true);});
