'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Data={title:string;columns:string[];rows:(string|number|null)[][];total:number;revision:number;asOf:string;page:number;hasMore:boolean;error?:string};
const datasets={successionCoverage:'可见范围继任覆盖',talentReview:'最新人才盘点',workforce:'员工名册',attendance:'出勤核验',learning:'学习任务',performance:'正式绩效'};
export default function Reports(){
 const [query,setQuery]=useState({dataset:'workforce',search:'',from:'',to:''}),[applied,setApplied]=useState(query),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const params=(q:typeof query)=>({dataset:q.dataset,search:q.search,...(q.dataset==='attendance'&&q.from?{from:q.from}:{}),...(q.dataset==='attendance'&&q.to?{to:q.to}:{})});
 async function load(){try{const r=await fetch('/api/reports?'+new URLSearchParams({...params(applied),page:String(page)}),{cache:'no-store'}),d=await r.json() as Data;if(!r.ok)throw Error(d.error);setData(d);}catch(e){setData(null);setError((e as Error).message);}}
 useEffect(()=>{let cancelled=false;async function read(){try{const r=await fetch('/api/reports?'+new URLSearchParams({...params(applied),page:String(page)}),{cache:'no-store'}),d=await r.json() as Data;if(!r.ok)throw Error(d.error);if(!cancelled){setData(d);setError('');}}catch(e){if(!cancelled){setData(null);setError((e as Error).message);}}}read();return()=>{cancelled=true;};},[applied,page]);
 function search(e:FormEvent){e.preventDefault();setPage(1);setData(null);setApplied({...query});}
 async function download(){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,query:params(applied)})});if(!r.ok){const d=await r.json() as {error:string};throw Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`hris-${applied.dataset}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已导出查询范围内的数据，并记录导出操作。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><Link href="/" className="text-link text-sm">返回导航台</Link><div className="page-head mt-5"><div><div className="eyebrow">REPORTS</div><h1>人事报表</h1><p className="mt-2 text-sm text-slate-500">仅统计当前账号可访问的数据。员工名册反映当前状态；出勤未覆盖时段须结合业务核验。</p></div><Button disabled={!data||busy} onClick={download}>{busy?'导出中…':'导出查询结果 CSV'}</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><form onSubmit={search} className="grid gap-4 md:grid-cols-5 items-end"><label className="text-sm">报表类型<Select value={query.dataset} onValueChange={v=>setQuery({...query,dataset:v})}><SelectTrigger aria-label="报表类型"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(datasets).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><label className="text-sm">关键词<Input value={query.search} onChange={e=>setQuery({...query,search:e.target.value})} placeholder="姓名、工号或期间"/></label>{query.dataset==='attendance'&&<><label className="text-sm">起始业务日期<Input type="date" value={query.from} onChange={e=>setQuery({...query,from:e.target.value})}/></label><label className="text-sm">结束业务日期<Input type="date" value={query.to} onChange={e=>setQuery({...query,to:e.target.value})}/></label></>}<Button type="submit">查询</Button></form></section><section className="panel">{applied.dataset==='successionCoverage'&&<p className="mb-4 text-sm text-slate-500">仅统计当前可见的启用岗位及在职后备；关闭记录、离职人员不计入。零表示可见范围内没有相应后备，不代表全企业无人选。现任人数按正式岗位关联统计，不按岗位名称推断；准备度不替代任用决策。</p>}<div className="section-head"><h2>{data?.title??'查询结果'}</h2><span className="text-sm text-slate-500">{data?`${data.total} 条 · 查询时间 ${new Date(data.asOf).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}`:'读取中…'}</span></div>{data&&<Table><TableHeader><TableRow>{data.columns.map(c=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.map((row,i)=><TableRow key={i}>{row.map((c,j)=><TableCell key={j}>{c??'—'}</TableCell>)}</TableRow>)}</TableBody></Table>}{data&&!data.rows.length&&<p className="empty">没有符合查询条件的记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><Button variant="outline" disabled={page<=1} onClick={()=>{setData(null);setPage(page-1);}}>上一页</Button><span className="text-sm">第 {page} 页 · 每页 50 条</span><Button variant="outline" disabled={!data?.hasMore} onClick={()=>{setData(null);setPage(page+1);}}>下一页</Button></div></section></main>;
}
