#!/usr/bin/env python3
"""Generate guarded compatibility dual writes; new domain commands own their version writes."""
import sqlite3,pathlib
root=pathlib.Path(__file__).resolve().parents[1];db=sqlite3.connect(':memory:')
for f in sorted((root/'drizzle').glob('*.sql')):
 if f.name<'0027_':db.executescript(f.read_text())
lines=['-- Compatibility changes invalidate reconciliation; no destructive rollback.','ALTER TABLE r1_schema_state ADD COLUMN migration_source_revision INTEGER NOT NULL DEFAULT 0;','ALTER TABLE r1_migration_runs ADD COLUMN scan_generation INTEGER NOT NULL DEFAULT 0;']
for (table,) in db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'hris_%'"):
 if table=='hris_workspaces':continue
 cols=db.execute('PRAGMA table_info('+table+')').fetchall();keys=[r[1] for r in sorted(cols,key=lambda r:r[5]) if r[5]]
 for op in ['INSERT','UPDATE','DELETE']:
  row='OLD' if op=='DELETE' else 'NEW';key='json_array('+','.join(row+'.'+k for k in keys)+')';tenant=row+'.tenant_id'
  active=f"EXISTS(SELECT 1 FROM hris_workspaces w JOIN r1_commands c ON c.tenant_id=w.owner AND c.token=w.last_mutation WHERE w.owner={tenant} AND c.status='processing' AND c.action NOT LIKE 'BASE.migration.%')"
  if table=='hris_audit_events':active+=' AND '+row+".action NOT LIKE 'BASE.migration.%'"
  lines+=[f'CREATE TRIGGER r1_migration_dirty_{table}_{op.lower()} AFTER {op} ON {table} WHEN {active} BEGIN',f' UPDATE r1_schema_state SET migration_source_revision=migration_source_revision+1 WHERE tenant_id={tenant};',f" UPDATE r1_migration_map SET source_digest='',confidence='source_changed' WHERE tenant_id={tenant} AND source_table='{table}' AND source_key={key};",'END;']
# Domain updates create an immutable observation version in the same original command transaction.
updates={
 'hris_employees':("kind='person' AND id=NEW.id","org_id=NEW.org_id,code=NEW.code,status=CASE WHEN NEW.status='离职' THEN 'ended' ELSE 'active' END,payload=json_set(payload,'$.name',NEW.name,'$.fields.email',NULLIF(NEW.email,''),'$.fields.level',NULLIF(NEW.level,''),'$.legacyStatus',NEW.status)"),
 'hris_orgs':("kind='org' AND id=NEW.id","status=CASE WHEN NEW.status='启用' THEN 'active' ELSE 'inactive' END,payload=json_set(payload,'$.name',NEW.name,'$.parentId',COALESCE(NEW.parent_id,''),'$.attributes.city',NEW.city,'$.attributes.legacyLeader',NEW.leader)"),
 'hris_positions':("kind='position' AND id=NEW.id","org_id=NEW.org_id,status=CASE WHEN NEW.status='启用' THEN 'active' ELSE 'inactive' END,payload=json_set(payload,'$.name',NEW.name,'$.attributes.legacyFamilyLabel',NEW.family,'$.attributes.responsibilities',NEW.responsibilities)"),
 'hris_grades':("kind='grade' AND id=NEW.id","status=CASE WHEN NEW.status='启用' THEN 'active' ELSE 'inactive' END,payload=json_set(payload,'$.name',NEW.name,'$.attributes.sequence',NEW.sequence)"),
 'hris_employee_positions':("kind='assignment' AND person_id=NEW.employee_id AND json_extract(payload,'$.type')='primary'","payload=json_set(payload,'$.positionId',NEW.position_id,'$.gradeId',NEW.grade_id)")}
for table,(target,setter) in updates.items():
 active="EXISTS(SELECT 1 FROM hris_workspaces w JOIN r1_commands c ON c.tenant_id=w.owner AND c.token=w.last_mutation WHERE w.owner=NEW.tenant_id AND c.status='processing' AND c.action NOT LIKE 'BASE.migration.%' AND c.action NOT LIKE 'M01.%' AND c.action NOT LIKE 'M19.%')"
 # Unmapped objects cannot be represented safely by the SQL bridge: block only this object.
 lines += [f"CREATE TRIGGER r1_migration_require_map_{table} BEFORE UPDATE ON {table} WHEN {active} AND EXISTS(SELECT 1 FROM r1_migration_runs WHERE tenant_id=NEW.tenant_id AND phase IN ('backfilling','reconciling')) AND NOT EXISTS(SELECT 1 FROM r1_m01_entities WHERE tenant_id=NEW.tenant_id AND {target}) BEGIN SELECT RAISE(ABORT,'MIGRATION_OBJECT_NOT_BACKFILLED'); END;"]
 if table=='hris_employees':
  lines += [f"CREATE TRIGGER r1_migration_protect_multi_assignment BEFORE UPDATE ON hris_employees WHEN {active} AND EXISTS(SELECT 1 FROM r1_m01_entities WHERE tenant_id=NEW.tenant_id AND kind='assignment' AND person_id=NEW.id AND (COALESCE(json_extract(payload,'$.migrationObservation'),0)<>1 OR json_extract(payload,'$.type')<>'primary')) BEGIN SELECT RAISE(ABORT,'MIGRATION_NEW_FACTS_REQUIRE_NEW_CLIENT'); END;"]
 # Do not overwrite newer facts or unknown multi-assignment histories through an old client.
 lines += [f'CREATE TRIGGER r1_migration_bridge_{table} AFTER UPDATE ON {table} WHEN {active} BEGIN',f" SELECT CASE WHEN EXISTS(SELECT 1 FROM r1_m01_entities WHERE tenant_id=NEW.tenant_id AND {target} AND COALESCE(json_extract(payload,'$.migrationObservation'),0)<>1) THEN RAISE(ABORT,'MIGRATION_NEW_FACTS_REQUIRE_NEW_CLIENT') END;",f" UPDATE r1_m01_entities SET revision=revision+1,{setter} WHERE tenant_id=NEW.tenant_id AND {target} AND json_extract(payload,'$.migrationObservation')=1;",f" INSERT INTO r1_m01_versions SELECT e.tenant_id,e.id,e.revision,w.revision,c.command_id,c.created_at,json_extract(e.payload,'$.validFrom'),json_extract(e.payload,'$.validTo'),'migration_bridge_observation',json_object('id',e.id,'kind',e.kind,'personId',e.person_id,'orgId',e.org_id,'code',e.code,'revision',e.revision,'status',e.status,'payload',json(e.payload)) FROM r1_m01_entities e JOIN hris_workspaces w ON w.owner=e.tenant_id JOIN r1_commands c ON c.tenant_id=w.owner AND c.token=w.last_mutation WHERE e.tenant_id=NEW.tenant_id AND {target} AND json_extract(e.payload,'$.migrationObservation')=1;",'END;']
 # Employee-position insert/upsert update is supported; deletions require explicit new-domain lifecycle semantics.
 lines += [f"CREATE TRIGGER r1_migration_protect_delete_{table} BEFORE DELETE ON {table} WHEN EXISTS(SELECT 1 FROM r1_migration_map WHERE tenant_id=OLD.tenant_id AND source_table='{table}') BEGIN SELECT RAISE(ABORT,'MIGRATION_FACT_DELETE_REQUIRES_LIFECYCLE'); END;"]
lines += ["""CREATE TRIGGER r1_migration_employee_companions AFTER UPDATE ON hris_employees WHEN EXISTS(SELECT 1 FROM hris_workspaces w JOIN r1_commands c ON c.tenant_id=w.owner AND c.token=w.last_mutation WHERE w.owner=NEW.tenant_id AND c.status='processing' AND c.action NOT LIKE 'BASE.migration.%' AND c.action NOT LIKE 'M01.%' AND c.action NOT LIKE 'M19.%') BEGIN
 UPDATE r1_m01_entities SET revision=revision+1,org_id=NEW.org_id,status=CASE WHEN NEW.status='离职' THEN 'ended' ELSE 'active' END,payload=CASE WHEN kind='employment' THEN json_set(payload,'$.legacyJoined',NEW.joined,'$.startOn',CASE WHEN date(NEW.joined)=NEW.joined THEN NEW.joined ELSE NULL END) ELSE json_set(payload,'$.legacyJobLabel',NEW.job,'$.legacyLevelLabel',NEW.level,'$.occupancy',CASE WHEN NEW.status='离职' THEN 0 ELSE 1 END) END WHERE tenant_id=NEW.tenant_id AND person_id=NEW.id AND kind IN ('employment','assignment') AND json_extract(payload,'$.migrationObservation')=1;
 INSERT INTO r1_m01_versions SELECT e.tenant_id,e.id,e.revision,w.revision,c.command_id,c.created_at,json_extract(e.payload,'$.validFrom'),json_extract(e.payload,'$.validTo'),'migration_bridge_observation',json_object('id',e.id,'kind',e.kind,'personId',e.person_id,'orgId',e.org_id,'code',e.code,'revision',e.revision,'status',e.status,'payload',json(e.payload)) FROM r1_m01_entities e JOIN hris_workspaces w ON w.owner=e.tenant_id JOIN r1_commands c ON c.tenant_id=w.owner AND c.token=w.last_mutation WHERE e.tenant_id=NEW.tenant_id AND e.person_id=NEW.id AND e.kind IN ('employment','assignment') AND json_extract(e.payload,'$.migrationObservation')=1;
END;"""]
(root/'drizzle/0027_r1_migration_bridge.sql').write_text('\n'.join(lines)+'\n')
