import {z} from 'zod';
import type {State} from './model';
import {scopedOrgs,type Member} from './authorization';
import {HttpError} from './http';
import {businessDate} from './workforce';
import {visibleRecord,type DevelopmentRecord as R} from './development';
const id=z.string().min(1).max(100),text=z.string().trim().min(1).max(200),evidence=z.string().trim().min(5).max(4000),stamp=z.string().datetime({offset:true});
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const attendanceCommand=z.discriminatedUnion('action',[
 z.object({action:z.literal('shift'),employeeId:id,date,name:text,startAt:stamp,endAt:stamp,breakStart:stamp.optional(),breakEnd:stamp.optional()}),
 z.object({action:z.literal('cancelShift'),id,reason:evidence}),
 z.object({action:z.literal('clock'),shiftId:id,punchKind:z.enum(['in','out'])}),
 z.object({action:z.literal('correction'),shiftId:id,inAt:stamp,outAt:stamp,evidence}),
 z.object({action:z.literal('decideCorrection'),id,accepted:z.boolean(),evidence}),
 z.object({action:z.literal('leaveType'),code:text,name:text,paid:z.boolean(),requiresBalance:z.boolean()}),
 z.object({action:z.literal('leaveCredit'),employeeId:id,leaveTypeId:id,year:z.number().int().min(2000).max(2200),minutes:z.number().int().min(-525600).max(525600).refine(v=>v!==0),source:evidence}),
 z.object({action:z.literal('leave'),employeeId:id,shiftId:id,leaveTypeId:id,startAt:stamp,endAt:stamp,reason:evidence}),
 z.object({action:z.literal('decideLeave'),id,accepted:z.boolean(),evidence}),
 z.object({action:z.literal('withdrawLeave'),id,reason:evidence}),
 z.object({action:z.literal('cancelApprovedLeave'),id,reason:evidence}),
]);
const time=(s:string)=>Date.parse(s),overlap=(a:number,b:number,c:number,d:number)=>Math.max(0,Math.min(b,d)-Math.max(a,c));
function minutes(shift:R,startAt:string,endAt:string){const start=time(startAt),end=time(endAt);const rest=shift.payload.breakStart&&shift.payload.breakEnd?overlap(start,end,time(shift.payload.breakStart),time(shift.payload.breakEnd)):0;return Math.ceil((end-start-rest)/60000);}
export function leaveBalance(records:R[],employeeId:string,typeId:string,year:number){const credited=records.filter(r=>r.kind==='leaveCredit'&&r.employeeId===employeeId&&r.referenceId===typeId&&r.payload.year===year).reduce((s,r)=>s+r.payload.minutes!,0);const leaves=records.filter(r=>r.kind==='leave'&&r.employeeId===employeeId&&r.payload.leaveTypeId===typeId&&r.payload.year===year);const used=leaves.filter(r=>r.status==='approved').reduce((s,r)=>s+r.payload.minutes!,0),reserved=leaves.filter(r=>r.status==='pending').reduce((s,r)=>s+r.payload.minutes!,0);return {credited,used,reserved,available:credited-used-reserved};}
export function applyAttendance(records:R[],state:State,member:Member,input:unknown,at=new Date().toISOString()){
 const c=attendanceCommand.parse(input),scope=scopedOrgs(state,member);
 const invalid=(message:string):never=>{throw new HttpError(400,message);},deny=(message:string):never=>{throw new HttpError(403,message);};
 const manager=()=>{if(!['admin','hr','manager'].includes(member.role))deny('没有假勤管理权限');};const hr=()=>{if(!['admin','hr'].includes(member.role))deny('仅管理员或HR可维护假期余额');};
 const employee=(id:string,active=true)=>{const e=state.employees.find(e=>e.id===id);if(!e||!(['admin','hr','manager'].includes(member.role)?scope.has(e.orgId):e.id===member.employeeId))deny('没有此员工的数据权限');if(active&&e!.status==='离职')invalid('离职员工不能发起新的假勤业务');return e!;};
 const get=(id:string,kind:R['kind'])=>{const r=records.find(r=>r.id===id&&r.kind===kind);if(!r||!visibleRecord(r,records,state,member))deny('记录不存在或没有访问权限');return r!;};
 const shift=(id:string)=>{const r=get(id,'shift');if(r.status!=='active')invalid('班次已取消');return r;};
 const independent=(r:R)=>{manager();employee(r.employeeId!,false);if(r.employeeId===member.employeeId||r.createdBy===member.userId)deny('本人或申请人不能审批自己的假勤申请');};
 const within=(s:R,startAt:string,endAt:string)=>{if(time(startAt)<time(s.payload.startAt!)||time(endAt)>time(s.payload.endAt!)||time(startAt)>=time(endAt))invalid('申请时段须完整位于本班次内且结束晚于开始');};
 const make=(kind:R['kind'],payload:R['payload'],extra:Partial<R>={})=>({id:crypto.randomUUID(),kind,payload,employeeId:null,positionId:null,referenceId:null,status:'active',createdBy:member.userId,createdAt:at,updatedAt:at,...extra} as R);
 const change=(r:R,status:string,payload:R['payload'])=>({...r,status,payload:{...r.payload,...payload},updatedAt:at});
 switch(c.action){
 case 'shift':{manager();employee(c.employeeId);const start=time(c.startAt),end=time(c.endAt);if(end<=start||end-start>24*60*60000)invalid('班次时长须大于0且不超过24小时');if(businessDate(c.startAt)!==c.date)invalid('业务日期须等于开始时间的北京时间日期');if(!!c.breakStart!==!!c.breakEnd)invalid('休息开始和结束须同时填写');if(c.breakStart&&(time(c.breakStart)<start||time(c.breakEnd!)>end||time(c.breakEnd!)<=time(c.breakStart)))invalid('休息时间须位于班次内');if(records.some(r=>r.kind==='shift'&&r.employeeId===c.employeeId&&r.status==='active'&&(r.payload.date===c.date||overlap(start,end,time(r.payload.startAt!),time(r.payload.endAt!))>0)))invalid('该员工已有当日班次或时间重叠');const r=make('shift',{name:c.name,date:c.date,startAt:c.startAt,endAt:c.endAt,breakStart:c.breakStart,breakEnd:c.breakEnd},{employeeId:c.employeeId});if(minutes(r,c.startAt,c.endAt)<=0)invalid('班次须包含有效工作时间');return r;}
 case 'cancelShift':{manager();const r=shift(c.id);if(records.some(x=>x.referenceId===r.id&&['clock','correction','leave'].includes(x.kind)&&!['rejected','withdrawn','cancelled'].includes(x.status)))invalid('已有打卡或有效申请的班次不能取消');return change(r,'cancelled',{closedReason:c.reason});}
 case 'clock':{const r=shift(c.shiftId);if(r.employeeId!==member.employeeId)deny('仅员工本人可打卡');employee(r.employeeId!);const now=time(at);if(now<time(r.payload.startAt!)-12*60*60000||now>time(r.payload.endAt!)+12*60*60000)invalid('当前时间不在该班次允许打卡的范围内');const punches=records.filter(x=>x.kind==='clock'&&x.referenceId===r.id);if(punches.some(x=>x.payload.punchKind===c.punchKind))invalid('该班次已有此类打卡');if(c.punchKind==='out'&&!punches.some(x=>x.payload.punchKind==='in'))invalid('请先完成上班打卡');return make('clock',{punchKind:c.punchKind,punchAt:at},{employeeId:r.employeeId,referenceId:r.id});}
 case 'correction':{const r=shift(c.shiftId);employee(r.employeeId!);if(member.employeeId!==r.employeeId&&!['admin','hr'].includes(member.role))deny('仅本人或HR可发起补卡');if(time(c.outAt)<=time(c.inAt)||time(c.inAt)<time(r.payload.startAt!)-12*60*60000||time(c.outAt)>time(r.payload.endAt!)+12*60*60000||time(c.outAt)>time(at))invalid('补卡时间范围无效或在未来');if(records.some(x=>x.kind==='correction'&&x.referenceId===r.id&&x.status==='pending'))invalid('该班次已有待处理补卡');return make('correction',{inAt:c.inAt,outAt:c.outAt,evidence:c.evidence},{employeeId:r.employeeId,referenceId:r.id,status:'pending'});}
 case 'decideCorrection':{const r=get(c.id,'correction');independent(r);shift(r.referenceId!);if(r.status!=='pending')invalid('补卡申请已经处理');return change(r,c.accepted?'approved':'rejected',{verification:c.evidence,verifiedBy:member.userId,verifiedAt:at});}
 case 'leaveType':{hr();if(records.some(r=>r.kind==='leaveType'&&r.payload.code===c.code))invalid('假期类型编码已存在；现有规则不可覆盖');return make('leaveType',{code:c.code,name:c.name,paid:c.paid,requiresBalance:c.requiresBalance});}
 case 'leaveCredit':{hr();employee(c.employeeId);const t=get(c.leaveTypeId,'leaveType');if(leaveBalance(records,c.employeeId,t.id,c.year).available+c.minutes<0)invalid('余额调整后不能小于已用及待审批占用');if(records.some(r=>r.kind==='leaveCredit'&&r.employeeId===c.employeeId&&r.referenceId===t.id&&r.payload.year===c.year&&r.payload.source===c.source))invalid('此余额来源已经登记');return make('leaveCredit',{year:c.year,minutes:c.minutes,source:c.source},{employeeId:c.employeeId,referenceId:t.id});}
 case 'leave':{employee(c.employeeId);if(c.employeeId!==member.employeeId&&!['admin','hr'].includes(member.role))deny('仅本人或HR可发起请假');const s=shift(c.shiftId),t=get(c.leaveTypeId,'leaveType');if(s.employeeId!==c.employeeId)invalid('员工与班次不一致');within(s,c.startAt,c.endAt);const charged=minutes(s,c.startAt,c.endAt);if(charged<=0)invalid('请假时段未包含工作时间');if(records.some(r=>r.kind==='leave'&&r.employeeId===c.employeeId&&['pending','approved'].includes(r.status)&&overlap(time(c.startAt),time(c.endAt),time(r.payload.startAt!),time(r.payload.endAt!))>0))invalid('存在重叠的待审批或已批准请假');const year=Number(s.payload.date!.slice(0,4));if(t.payload.requiresBalance&&leaveBalance(records,c.employeeId,t.id,year).available<charged)invalid('可用假期余额不足（已扣除待审批占用）');return make('leave',{leaveTypeId:t.id,year,startAt:c.startAt,endAt:c.endAt,minutes:charged,paid:t.payload.paid,reason:c.reason},{employeeId:c.employeeId,referenceId:s.id,status:'pending'});}
 case 'decideLeave':{const r=get(c.id,'leave');independent(r);shift(r.referenceId!);if(r.status!=='pending')invalid('请假申请已经处理');return change(r,c.accepted?'approved':'rejected',{verification:c.evidence,verifiedBy:member.userId,verifiedAt:at});}
 case 'cancelApprovedLeave':{const r=get(c.id,'leave');independent(r);if(r.status!=='approved')invalid('仅已批准请假可取消');return change(r,'cancelled',{closedReason:c.reason,verifiedBy:member.userId,verifiedAt:at});}
 case 'withdrawLeave':{const r=get(c.id,'leave');employee(r.employeeId!,false);if(r.createdBy!==member.userId&&!['admin','hr'].includes(member.role))deny('仅申请人或HR可撤回');if(r.status!=='pending')invalid('仅待审批请假可以撤回');return change(r,'withdrawn',{closedReason:c.reason});}
 }
}
export function attendanceReport(records:R[],at=new Date().toISOString()){
 return records.filter(r=>r.kind==='shift'&&r.status==='active').map(s=>{
 const corrections=records.filter(r=>r.kind==='correction'&&r.referenceId===s.id&&r.status==='approved').sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const rawIn=records.find(r=>r.kind==='clock'&&r.referenceId===s.id&&r.payload.punchKind==='in')?.payload.punchAt,rawOut=records.find(r=>r.kind==='clock'&&r.referenceId===s.id&&r.payload.punchKind==='out')?.payload.punchAt;const inAt=corrections[0]?.payload.inAt??rawIn,outAt=corrections[0]?.payload.outAt??rawOut;const start=time(s.payload.startAt!),end=time(s.payload.endAt!);const rest=s.payload.breakStart&&s.payload.breakEnd?[[time(s.payload.breakStart),time(s.payload.breakEnd)]]:[];
 const leave=records.filter(r=>r.kind==='leave'&&r.referenceId===s.id&&r.status==='approved');const intervals=[...rest,...leave.map(r=>[time(r.payload.startAt!),time(r.payload.endAt!)]),...(inAt&&outAt?[[Math.max(start,time(inAt)),Math.min(end,time(outAt))]]:[])].filter(([a,b])=>a<b).sort((a,b)=>a[0]-b[0]);let cursor=start,uncovered=0;for(const [a,b]of intervals){if(a>cursor)uncovered+=a-cursor;cursor=Math.max(cursor,b);}if(cursor<end)uncovered+=end-cursor;
 const missing=Math.max(0,Math.ceil(uncovered/60000)),planned=minutes(s,s.payload.startAt!,s.payload.endAt!);return {shiftId:s.id,employeeId:s.employeeId,date:s.payload.date,name:s.payload.name,startAt:s.payload.startAt,endAt:s.payload.endAt,inAt:inAt??null,outAt:outAt??null,corrected:!!corrections.length,plannedMinutes:planned,approvedLeaveMinutes:leave.reduce((n,r)=>n+r.payload.minutes!,0),uncoveredMinutes:missing,status:time(at)<start?'未开始':time(at)<end?'进行中':!inAt||!outAt?(missing===0?'请假覆盖':'缺卡待核验'):missing>0?'时段未完整覆盖':'记录完整'};
 });
}
