import {HttpError} from './http';
import {validateReportDefinition} from './r1-report-definition';
import {readReport,type AuthorizedReportPlan} from './r1-report-query';
import {ratio,decimalParts,decimalString,type ReportCell} from './r1-report-values';
import type {ReportContext} from './r1-report-context';
const nullCell=(reasonCode:string):ReportCell=>({value:null,state:'null',reasonCode});
/** Database aggregates process only the current authorized subquery; no hidden raw rows reach the client. */
export async function aggregateDefinition(ctx:ReportContext,query:URLSearchParams,input:unknown,scopeOrg?:string){
 const validated=validateReportDefinition(input),d=validated.definition;if(!d.metrics.length)throw new HttpError(400,'汇总定义必须声明指标','METRIC_REQUIRED');if(d.joins.length)throw new HttpError(409,'关联执行必须有固定的目标数据版本及先聚合计划','JOIN_GENERATION_REQUIRED');
 const fields=[...new Set([...d.columns,...validated.usedFields])],definition={...d,columns:fields};
 return readReport(ctx,query,{action:'aggregate',definition,scopeOrg,async execute(plan:AuthorizedReportPlan){
  const column=(id:string)=>{const index=plan.fields.indexOf(id);if(index<0)throw new HttpError(400,'指标字段未进入授权计划','FIELD_NOT_ALLOWED');return 'f'+index;},value=(id:string)=>`json_extract(${column(id)},'$.value')`,state=(id:string)=>`json_extract(${column(id)},'$.state')`,group=d.groupBy.map(column),partition=group.length?'PARTITION BY '+group.join(',')+' ':'';
  const atoms:any[]=[],windows:string[]=[],selects:string[]=[],atomId=new Map<any,number>();
  const register=(n:any)=>{if(['add','subtract','ratio'].includes(n.op)){register(n.left);register(n.right);return;}if(n.op==='field'){if(!d.groupBy.includes(n.field))throw new HttpError(400,'汇总中裸字段必须属于分组','UNGROUPED_FIELD');return;}const index=atoms.length;atoms.push(n);atomId.set(n,index);const x=n.field?value(n.field):'*',known=n.field?`COUNT(CASE WHEN ${state(n.field)}='value' THEN 1 END)`:'COUNT(*)';selects.push(known+' AS k'+index,'COUNT(*) AS n'+index);
   if(n.op==='count'||n.op==='countDistinct'){selects.push((n.op==='countDistinct'?`COUNT(DISTINCT ${x})`:n.field?`COUNT(${x})`:'COUNT(*)')+' AS a'+index);return;}
   const f=plan.dataset.fields.find(f=>f.fieldId===n.field)!;
   if(f.type==='decimal'&&['min','max'].includes(n.op)){const fractional=`CASE WHEN instr(${x},'.')>0 THEN CAST(substr(${x}||'000000',instr(${x},'.')+1,6) AS INTEGER)*CASE WHEN substr(${x},1,1)='-' THEN -1 ELSE 1 END ELSE 0 END`,direction=n.op==='min'?'ASC':'DESC';windows.push(`FIRST_VALUE(${x}) OVER (${partition}ORDER BY CASE WHEN ${x} IS NULL THEN 1 ELSE 0 END,CAST(${x} AS INTEGER) ${direction},${fractional} ${direction}) AS w${index}`);selects.push(`MAX(w${index}) AS a${index}`);}
   else if(n.op==='avg'){selects.push(`SUM(${x}) AS a${index}`);}
   else selects.push(n.op.toUpperCase()+'('+x+') AS a'+index);
   if(f.type==='money_cents')selects.push('COUNT(DISTINCT currency) AS currencies'+index,'COUNT(currency) AS currencyKnown'+index);
  };d.metrics.forEach(m=>register(m.expression));
  const sql='WITH permitted AS ('+plan.sql+'), values_with_windows AS (SELECT *'+(windows.length?','+windows.join(','):'')+' FROM permitted) SELECT '+[...group,...selects].join(',')+' FROM values_with_windows'+(group.length?' GROUP BY '+group.join(','):'')+(group.length?' ORDER BY '+group.join(','):'')+' LIMIT 101';let records:any[];
  try{records=(await ctx.db.prepare(sql).bind(...plan.args).all<any>()).results;}catch(e){if(/overflow|out of range/i.test((e as Error).message))throw new HttpError(400,'聚合整数溢出','UNSAFE_INTEGER');throw e;}if(records.length>100)throw new HttpError(413,'分组超过同步预算，需要分组任务','AGGREGATE_GROUP_BUDGET');
  const evaluate=(n:any,row:any):ReportCell&{knownCount?:number;missingCount?:number}=>{if(n.op==='field')return JSON.parse(row[column(n.field)]);if(['add','subtract','ratio'].includes(n.op)){const a=evaluate(n.left,row),b=evaluate(n.right,row);if(n.op==='ratio')return ratio(a,b,!!n.percent);if(a.state!=='value'||b.state!=='value')return nullCell('unknown_operand');const x=decimalParts(a.value as string|number),y=decimalParts(b.value as string|number),scale=Math.max(x.scale,y.scale),result=x.n*BigInt(10)**BigInt(scale-x.scale)+(n.op==='add'?BigInt(1):-BigInt(1))*y.n*BigInt(10)**BigInt(scale-y.scale);if(typeof a.value==='number'&&typeof b.value==='number'){if(result>BigInt(Number.MAX_SAFE_INTEGER)||result<BigInt(Number.MIN_SAFE_INTEGER))throw new HttpError(400,'公式整数溢出','UNSAFE_INTEGER');return {value:Number(result),state:'value',reasonCode:null};}return {value:decimalString(result,scale),state:'value',reasonCode:null};}
   const i=atomId.get(n)!,knownCount=row['k'+i],missingCount=row['n'+i]-knownCount,raw=row['a'+i],f=n.field?plan.dataset.fields.find(f=>f.fieldId===n.field):null;if(f?.type==='money_cents'&&knownCount&&(row['currencies'+i]!==1||row['currencyKnown'+i]!==row['n'+i]))throw new HttpError(400,'币种缺失或混合，不能聚合','CURRENCY_MISMATCH');if(raw===null)return {...nullCell('unknown_values'),knownCount,missingCount};if(typeof raw==='number'&&!Number.isSafeInteger(raw))throw new HttpError(400,'整数聚合超出安全范围','UNSAFE_INTEGER');const cell={value:raw,state:'value' as const,reasonCode:null};return {...(n.op==='avg'?ratio(cell,{value:knownCount,state:'value',reasonCode:null}):cell),knownCount,missingCount};};
  return {availability:records.length?'available':'no_data',groups:records.map(row=>({cells:Object.fromEntries(d.groupBy.map(id=>[id,JSON.parse(row[column(id)])])),metrics:Object.fromEntries(d.metrics.map(m=>[m.id,evaluate(m.expression,row)]))})),rowGrain:plan.dataset.grain,groupTotal:records.length,sourceRowTotal:null,visibleScope:'current authorized aggregate scope',drillAllowed:false};
 }});
}
