import {z} from 'zod';
import {HttpError} from './http';
import {digest} from './r1-command';
import {datasetDefinition,reportSchemaVersion} from './r1-report-catalog';
import {validateReportDefinition,compileReportFilter,cellSql} from './r1-report-definition';
import {reportPolicy} from './r1-report-permissions';
import {reportFence,type ReportContext} from './r1-report-context';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v),query=z.object({dataset:z.string().min(1).max(100),generation:z.string().max(100).optional(),snapshot:z.string().max(100).optional(),mode:z.enum(['current','event_range','snapshot']).optional(),from:date.optional(),to:date.optional(),columns:z.string().max(4000).optional(),filter:z.string().max(12000).optional(),cursor:z.string().uuid().optional(),limit:z.coerce.number().int().min(1).max(200).default(50)}).strict();
export async function readReport(ctx:ReportContext,input:URLSearchParams){
 const p=query.parse(Object.fromEntries(input)),dataset=datasetDefinition(p.dataset);if(!dataset)throw new HttpError(400,'未注册数据集','DATASET_NOT_FOUND');const mode=p.mode??(p.snapshot?'snapshot':dataset.timeMode);if(mode==='current'&&(p.from||p.to)||mode==='event_range'&&dataset.timeMode!=='event_range'||mode==='snapshot'&&(!p.snapshot||p.from||p.to)||mode!=='snapshot'&&p.snapshot||p.generation&&p.snapshot||p.from&&p.to&&p.from>p.to)throw new HttpError(400,'时间模式或业务日期不受支持','TIME_MODE_INVALID');
 const t=ctx.member.tenantId,db=ctx.db,stamp=ctx.member.securityStamp!,policy=await reportPolicy(ctx,p.dataset,'read',mode==='snapshot');let saved:any=null;
 if(p.snapshot){saved=await db.prepare("SELECT * FROM r1_report_snapshots WHERE tenant_id=? AND id=? AND dataset_id=? AND status='ready'").bind(t,p.snapshot,p.dataset).first<any>();if(!saved)throw new HttpError(404,'不存在可核验的历史快照','SNAPSHOT_NOT_FOUND');}
 const generationId=p.generation??saved?.generation_id,g=await (generationId?db.prepare("SELECT * FROM r1_report_generations WHERE tenant_id=? AND id=? AND dataset_id=? AND status='ready'").bind(t,generationId,p.dataset):db.prepare("SELECT * FROM r1_report_generations WHERE tenant_id=? AND dataset_id=? AND status='ready' ORDER BY completed_at DESC,id DESC LIMIT 1").bind(t,p.dataset)).first<any>();
 if(!g){if(generationId)throw new HttpError(404,'报表数据版本尚不可用','GENERATION_NOT_FOUND');return {dataset:p.dataset,availability:dataset.producer==='M01'?'unavailable':'not_configured',reasonCode:dataset.producer==='M01'?'PROJECTION_REQUIRED':'PRODUCER_NOT_CONFIGURED',owner:dataset.producer+' implementation owner',recoveryCondition:'build versioned source projection',rows:[],total:null,totalState:'unknown',nextCursor:null,hasMore:false,realIntegration:'not_executed'};}
 if(g.definition_version!==reportSchemaVersion)throw new HttpError(409,'报表定义版本不兼容','DATASET_VERSION_UNSUPPORTED');if(saved&&saved.content_digest!==g.content_digest)throw new HttpError(409,'快照来源摘要不一致','SNAPSHOT_DIGEST_CONFLICT');
 let columns:string[],filter:unknown;try{columns=p.columns?JSON.parse(p.columns):dataset.fields.filter(f=>policy.fields.has(f.fieldId)).map(f=>f.fieldId);filter=p.filter?JSON.parse(p.filter):undefined;}catch{throw new HttpError(400,'查询格式无效','INVALID_INPUT');}
 if(!Array.isArray(columns)||!columns.length)throw new HttpError(403,'没有可读取的报表字段','FIELD_NOT_ALLOWED');
 const def={datasetId:p.dataset,schemaVersion:reportSchemaVersion,columns,...(filter?{filter}:{})},compiled=compileReportFilter(def,policy.fields),wanted=compiled.definition.columns,definitionDigest=await digest(def),queryDigest=await digest({definitionDigest,mode,from:p.from??null,to:p.to??null,generation:g.id,snapshot:p.snapshot??null,limit:p.limit});let after='';
 if(p.cursor){const c=await db.prepare('SELECT * FROM r1_report_query_cursors WHERE tenant_id=? AND id=? AND actor_id=?').bind(t,p.cursor,ctx.member.userId).first<any>();if(!c||c.query_digest!==queryDigest||c.generation_id!==g.id||c.authorization_revision!==stamp.authorizationRevision||c.writer_epoch!==stamp.writerEpoch||c.recovery_epoch!==stamp.recoveryEpoch||c.expires_at<=Date.now())throw new HttpError(409,'分页查询或当前权限已变化','CURSOR_STALE');after=c.last_key;}
 const selected=wanted.map((id,i)=>'CASE WHEN '+policy.predicate(id)+' THEN '+cellSql(policy.fieldDefinition(id)).replace(/\.value'\)/,"')")+' ELSE NULL END AS f'+i),selectArgs=[...policy.args];policy.args.length=0;
 const rowPolicy=policy.predicate('record'),filterFields=new Set<string>();const collect=(n:any)=>{if(!n)return;if(n.field)filterFields.add(n.field);if(n.args)n.args.forEach(collect);};collect(compiled.definition.filter);const filterPolicies=[...filterFields].map(f=>policy.predicate(f));
 const clauses=['r.tenant_id=?','r.dataset_id=?','r.generation_id=?','r.row_key>?',rowPolicy,...filterPolicies,compiled.sql],whereArgs:unknown[]=[t,p.dataset,g.id,after,...policy.args,...compiled.args];if(p.from){clauses.push('r.event_date>=?');whereArgs.push(p.from);}if(p.to){clauses.push('r.event_date<=?');whereArgs.push(p.to);}const sql='SELECT r.row_key,r.person_id,r.source_version'+(selected.length?','+selected.join(','):'')+' FROM r1_report_rows r WHERE '+clauses.join(' AND ')+' ORDER BY r.row_key LIMIT ?';const args=[...selectArgs,...whereArgs,p.limit+1];if(args.length>95)throw new HttpError(413,'查询参数超过有界预算，请缩小字段/授权范围','QUERY_BINDING_BUDGET');
 const result=(await db.prepare(sql).bind(...args).all<any>()).results;if(new TextEncoder().encode(JSON.stringify(result)).byteLength>4*1024*1024)throw new HttpError(413,'返回块过大，请缩小列或页长','REPORT_CHUNK_TOO_LARGE');const selectedRows=result.slice(0,p.limit),rows=selectedRows.map(r=>({rowKey:r.row_key,personId:r.person_id,sourceVersion:r.source_version,cells:Object.fromEntries(wanted.flatMap((id,i)=>r['f'+i]===null?[]:[[id,JSON.parse(r['f'+i])]]))}));await reportFence(ctx);
 const next=result.length>p.limit?crypto.randomUUID():null;if(next)await db.prepare('INSERT INTO r1_report_query_cursors VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(t,next,ctx.member.userId,queryDigest,g.id,stamp.authorizationRevision,stamp.writerEpoch,stamp.recoveryEpoch,selectedRows.at(-1)!.row_key,'[]',Date.now()+300000).run();
 return {dataset:p.dataset,definitionVersion:reportSchemaVersion,availability:rows.length?'available':'no_data',rows,columns:dataset.fields.filter(f=>wanted.includes(f.fieldId)),generation:g.id,snapshotId:saved?.id??null,generatedAt:g.generated_at,asOf:g.generated_at,asOfMeaning:'generatedAt, not a requested historical cutoff',businessCutoff:g.source_cutoff,sourceManifest:JSON.parse(g.source_manifest),contentDigest:g.content_digest,mode,total:null,totalState:'unknown',hasMore:!!next,nextCursor:next,visibleScope:'current authorized rows and fields; totals not disclosed',recomputedForAuthorization:true,authorizationRevision:stamp.authorizationRevision,securityStamp:stamp,revision:ctx.row.revision,realIntegration:'not_executed'};
}
