'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
import ProcessHistory from '../development/process-history';
type Data={records:R[];revision:number;error?:string};
export default function Assignments({core}:{core:State|null}){
 const [data,setData]=useState<Data|null>(null),[definitionId,setDefinitionId]=useState('none'),[employeeId,setEmployeeId]=useState('none'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<string|null>(null),[evidence,setEvidence]=useState('');
 async function load(){try{const r=await fetch('/api/learning-assignments',{cache:'no-store'}),d=await r.json() as Data;if(!r.ok)throw Error(d.error);setData(d);}catch(e){setData(null);setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function send(command:unknown){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/learning-assignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const selected=data?.records.find(r=>r.id===definitionId);
 return <section className="panel mt-6 space-y-4"><div className="flex justify-between"><h2>首轮独立学习派发</h2><Button variant="outline" onClick={load}>刷新配置与实例</Button></div><p className="text-sm text-slate-500">支持周期及起止时间模式，一次为一名员工生成全部课程任务。已有同课程版本的学习记录会整单拒绝；历史同步与循环轮次尚未开放。</p>{error&&<p role="alert">{error}</p>}<div className="flex flex-wrap gap-3"><Select value={definitionId} onValueChange={v=>{setDefinitionId(v);setEmployeeId('none');}}><SelectTrigger className="min-w-60" aria-label="派发计划版本"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">选择已定版独立学习配置</SelectItem>{data?.records.filter(r=>r.kind==='learningDefinition'&&r.status==='sealed'&&!r.payload.learningMode?.progressSync&&r.payload.learningMode?.mode!=='recurring').map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title} · v{r.payload.version}</SelectItem>)}</SelectContent></Select><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger aria-label="派发学员" className="min-w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">选择同组织在职员工</SelectItem>{core?.employees.filter(e=>e.status!=='离职'&&e.orgId===selected?.payload.orgId).map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.code}</SelectItem>)}</SelectContent></Select><Button disabled={busy||definitionId==='none'||employeeId==='none'} onClick={()=>send({action:'assign',definitionId,employeeId})}>派发首轮任务</Button></div><Link href="/learning">前往课程学习与独立核验</Link><label className="block">整体取消/恢复依据<Input minLength={5} maxLength={3000} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="办理前填写原因，至少5字"/></label>{data?.records.filter(r=>r.kind==='learningAssignment').map(r=>{const tasks=data.records.filter(t=>t.kind==='enrollment'&&t.payload.learningAssignmentId===r.id),completed=tasks.filter(t=>t.status==='completed').length;return <article key={r.id} className="border-t pt-4"><h3>{r.payload.title} · {core?.employees.find(e=>e.id===r.employeeId)?.name} · 第{r.payload.round}轮</h3><p>{r.payload.start} 至 {r.payload.due} · 已核验 {completed}/{r.payload.courseIds?.length} · {r.status==='completed'?'已结项':r.status==='cancelled'?'已取消':'进行中'}</p><div className="flex gap-3 mt-2">{r.status==='active'&&<Button variant="outline" disabled={busy||completed!==r.payload.courseIds?.length} onClick={()=>send({action:'closeAssignment',id:r.id})}>核对并结项</Button>}{['active','cancelled'].includes(r.status)&&<Button variant="outline" disabled={busy||evidence.trim().length<5} onClick={()=>send({action:r.status==='active'?'cancelAssignment':'restoreAssignment',id:r.id,evidence})}>{r.status==='active'?'整体取消':'整体恢复'}</Button>}<Button variant="ghost" onClick={()=>setHistory(history===r.id?null:r.id)}>历史</Button></div>{history===r.id&&<ProcessHistory id={r.id} updatedAt={r.updatedAt}/>}</article>;})}</section>;
}
