'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {LearningGradeRule} from '@/lib/hris/learning-grades';
export const gradeModes={none:'不设置计划成绩',allHighest:'全部考试最高分',allAttemptsAverage:'全部作答成绩平均',eachExamHighestAverage:'各考试最高分的平均',specifiedExamHighest:'指定一场考试最高分'};
export default function Grading({definition,records,busy,send}:{definition:R;records:R[];busy:boolean;send:(command:Record<string,unknown>)=>unknown}){
 const initial=definition.payload.gradeRule??{mode:'none'},[mode,setMode]=useState<LearningGradeRule['mode']>(initial.mode),[attempts,setAttempts]=useState(initial.mode==='none'?'all':initial.attempts),[decimals,setDecimals]=useState(initial.mode==='none'?2:initial.decimals),[examId,setExam]=useState(initial.mode==='specifiedExamHighest'?initial.examId:'none');
 return <form className="border rounded p-4 mt-4 space-y-3" onSubmit={e=>{e.preventDefault();send({action:'grading',id:definition.id,rule:mode==='none'?{mode}:{mode,attempts,decimals,...(mode==='specifiedExamHighest'?{examId}:{})}});}}><h3>计划成绩规则</h3><p className="text-sm text-slate-500">以下为本系统显式配置，尚未确认与企业原站细则完全一致。仅计算本实例独立考试，缺少任何所选考试的有效成绩时保持待定；课程完成、学分不换算成成绩。定版后规则冻结。</p><Select value={mode} onValueChange={v=>setMode(v as LearningGradeRule['mode'])}><SelectTrigger aria-label="计划成绩算法"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(gradeModes).map(([value,label])=><SelectItem key={value} value={value} disabled={value!=='none'&&!definition.payload.examIds?.length}>{label}</SelectItem>)}</SelectContent></Select>{mode!=='none'&&<><Select value={attempts} onValueChange={v=>{if(v==='all'||v==='passed')setAttempts(v);}}><SelectTrigger aria-label="计入哪些作答"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">计入全部有效作答（含未通过）</SelectItem><SelectItem value="passed">仅计入已通过作答</SelectItem></SelectContent></Select><Select value={String(decimals)} onValueChange={v=>setDecimals(Number(v))}><SelectTrigger aria-label="四舍五入小数位"><SelectValue/></SelectTrigger><SelectContent>{[0,1,2].map(n=><SelectItem key={n} value={String(n)}>四舍五入保留 {n} 位小数</SelectItem>)}</SelectContent></Select>{mode==='specifiedExamHighest'&&<Select value={examId} onValueChange={setExam}><SelectTrigger aria-label="指定考试"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择本计划考试</SelectItem>{records.filter(r=>definition.payload.examIds?.includes(r.id)).map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title}</SelectItem>)}</SelectContent></Select>}</>}<Button disabled={busy||mode==='specifiedExamHighest'&&examId==='none'}>保存成绩规则</Button></form>;
}
