import {businessDate} from '@/lib/hris/workforce';
import {developmentContext,visibleDevelopment} from '@/lib/hris/development-repository';
import {visibleState} from '@/lib/hris/authorization';
import {json,failure} from '@/lib/hris/http';
export async function GET(){try{const ctx=await developmentContext(),state=visibleState(ctx.state,ctx.member),all=visibleDevelopment(ctx),records=all.filter(r=>r.employeeId===ctx.member.employeeId),employee=state.employees.find(e=>e.id===ctx.member.employeeId)??null;
 const tasks=records.filter(r=>(['cadreObservation','plan','enrollment'].includes(r.kind)&&['active','returned'].includes(r.status))||(r.kind==='performancePlan'&&r.status==='confirmed')).map(r=>({id:r.id,title:r.payload.title??(r.kind==='performancePlan'?`${r.payload.period} 绩效自评`:r.kind==='cadreObservation'?'任职考察述职':'发展行动'),due:r.payload.due??'',kind:r.kind,href:r.kind==='cadreObservation'?'/cadres':r.kind==='enrollment'?'/learning':r.kind==='performancePlan'?'/performance':'/development'}));
 for(const r of all.filter(r=>r.kind==='surveyRound'&&r.status==='open'&&r.payload.start!<=businessDate()&&r.payload.end!>=businessDate()&&ctx.records.find(x=>x.id===r.id)?.payload.participantIds?.includes(ctx.member.employeeId??'')&&!records.some(x=>x.kind==='surveyResponse'&&x.referenceId===r.id&&x.status==='submitted')))tasks.push({id:r.id,title:r.payload.name??'实名问卷',due:r.payload.end??'',kind:r.kind,href:'/surveys'});
 const requests=records.filter(r=>['leave','correction'].includes(r.kind)).map(r=>({id:r.id,kind:r.kind,title:r.kind==='leave'?'请假申请':'补卡申请',status:r.status,at:r.updatedAt,href:'/attendance'}));
 return json({employee,tasks,requests,payslipCount:records.filter(r=>r.kind==='paySlip'&&r.status!=='cancelled'&&ctx.records.some(b=>b.id===r.referenceId&&b.status==='published')).length,revision:ctx.row.revision});}catch(e){return failure(e);}}
