'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string;userId:string;permissions:{viewEmail:boolean;viewLevel:boolean}};
const statuses:Record<string,string>={draft:'待审批',returned:'需求待修订',active:'招聘中',closed:'已关闭',screening:'筛选与面试',interviewed:'已面试',recorded:'已记录',offered:'录用待审批',approved:'录用已批准',accepted:'已登记接受录用',hired:'已入职',rejected:'已结束'};
type Field={key:string;label:string;type?:string;optional?:boolean};const fields:Record<string,Field[]>={returnRequisition:[{key:'reason',label:'退回原因及修改要求',type:'long'}],reviseRequisition:[{key:'title',label:'需求名称'},{key:'headcount',label:'招聘人数',type:'number'},{key:'reason',label:'修订后的完整招聘依据',type:'long'}],returnOffer:[{key:'reason',label:'退回原因及需修改的事项',type:'long'}],requisition:[{key:'positionId',label:'招聘岗位',type:'position'},{key:'title',label:'需求名称'},{key:'headcount',label:'招聘人数',type:'number'},{key:'reason',label:'招聘依据',type:'long'}],candidate:[{key:'requisitionId',label:'已批准招聘需求',type:'requisition'},{key:'name',label:'候选人姓名'},{key:'email',label:'联系邮箱',type:'email',optional:true},{key:'source',label:'来源渠道及资料获取依据',type:'long'}],interview:[{key:'rating',label:'面试评价等级（1–5）',type:'number'},{key:'recommendation',label:'是否建议推进',type:'recommendation'},{key:'evidence',label:'岗位相关事实与评价依据',type:'long'}],offer:[{key:'joined',label:'计划入职日期',type:'date'},{key:'gradeId',label:'目标职级',type:'grade',optional:true},{key:'evidence',label:'录用依据与条件说明',type:'long'}],acceptOffer:[{key:'evidence',label:'候选人接受录用的书面依据',type:'long'}],hire:[{key:'code',label:'新员工编号'}],rejectCandidate:[{key:'reason',label:'结束原因',type:'long'}],closeRequisition:[{key:'reason',label:'关闭需求的原因',type:'long'}]};
export default function Recruitment(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[tab,setTab]=useState('requisition'),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/recruitment',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([r.json() as Promise<Data&{error?:string}>,h.json() as Promise<{state:State;error?:string}>]);if(!r.ok)throw Error(d.error);if(!h.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=['admin','manager'].includes(data?.role??''),interviewer=hr||manager;const record=(id?:string|null)=>data?.records.find(r=>r.id===id),name=(r:R)=>r.payload.title??r.payload.name??record(r.referenceId)?.payload.name??'—',position=(id:string|null)=>core?.positions?.find(p=>p.id===id)?.name??'—',detail=record(selected);
 function open(action:string,r?:R){setError('');setForm({action,id:r?.id??'',candidateId:r?.id??'',requisitionId:r?.kind==='requisition'?r.id:'none',title:r?.payload.title??'',reason:action==='reviseRequisition'?r?.payload.reason??'':'',headcount:String(r?.payload.headcount??1),rating:'3',recommendation:'advance',gradeId:'none'});}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/recruitment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice(command.action==='hire'?'入职成功，员工档案和任职历史已同步建立':'招聘记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const c:Record<string,unknown>={...form};if(!c.id)delete c.id;for(const f of fields[form.action]??[]){if(f.type==='number')c[f.key]=Number(form[f.key]);if(f.optional&&(form[f.key]==='none'||!form[f.key]))delete c[f.key];}if(form.action==='candidate')c.email=form.email??'';send(c);}
 function options(f:Field){if(f.type==='position')return (core?.positions??[]).filter(p=>p.status==='启用').map(p=>[p.id,p.code+' · '+p.name]);if(f.type==='grade')return (core?.grades??[]).filter(g=>g.status==='启用').map(g=>[g.id,g.name]);if(f.type==='recommendation')return [['advance','建议推进'],['reject','不建议推进']];return (data?.records??[]).filter(r=>r.kind==='requisition'&&r.status==='active').map(r=>[r.id,r.payload.title!]);}
 function actions(r:R){return <div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={()=>setSelected(r.id)}>详情</Button>{r.kind==='requisition'&&<>{r.status==='draft'&&manager&&r.createdBy!==data?.userId&&!r.payload.contributors?.includes(data?.userId??'')&&<Button size="sm" disabled={busy} onClick={()=>send({action:'approveRequisition',id:r.id})}>批准需求</Button>}{r.status==='draft'&&manager&&r.createdBy!==data?.userId&&!r.payload.contributors?.includes(data?.userId??'')&&<Button size="sm" variant="outline" onClick={()=>open('returnRequisition',r)}>退回需求</Button>}{['draft','returned'].includes(r.status)&&hr&&<Button size="sm" variant="outline" onClick={()=>open('reviseRequisition',r)}>修订并提交</Button>}{r.status==='active'&&hr&&<Button size="sm" onClick={()=>open('candidate',r)}>添加候选人</Button>}{r.status!=='closed'&&hr&&<Button size="sm" variant="outline" onClick={()=>open('closeRequisition',r)}>关闭</Button>}</>}{r.kind==='candidate'&&<>{['screening','interviewed'].includes(r.status)&&interviewer&&<Button size="sm" variant="outline" onClick={()=>open('interview',r)}>记录面试</Button>}{['screening','interviewed'].includes(r.status)&&hr&&<Button size="sm" onClick={()=>open('offer',r)}>发起录用</Button>}{r.status==='offered'&&manager&&r.payload.offeredBy!==data?.userId&&<Button size="sm" disabled={busy} onClick={()=>send({action:'approveOffer',id:r.id})}>批准录用</Button>}{r.status==='offered'&&manager&&r.payload.offeredBy!==data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('returnOffer',r)}>退回修改</Button>}{r.status==='approved'&&hr&&<Button size="sm" onClick={()=>open('acceptOffer',r)}>登记接受录用</Button>}{r.status==='accepted'&&hr&&<Button size="sm" onClick={()=>open('hire',r)}>办理入职</Button>}{!['hired','rejected'].includes(r.status)&&hr&&<Button size="sm" variant="ghost" onClick={()=>open('rejectCandidate',r)}>结束流程</Button>}</>}</div>;}
 const rows=(data?.records??[]).filter(r=>r.kind===tab&&(name(r)+' '+position(r.positionId)).toLowerCase().includes(search.toLowerCase())).reverse();
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link className="text-link" href="/reports?dataset=recruitmentOperations">需求进度</Link><Link className="text-link" href="/">导航台</Link><Link className="text-link" href="/employees">员工档案</Link><Link className="text-link" href="/performance">绩效管理</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">RECRUITMENT & ONBOARDING</div><h1>招聘与入职</h1><p className="mt-2 text-sm text-slate-500">从批准招聘需求到录用审批与入职，按岗位保留评价、接受依据和办理记录。</p></div><Button variant="outline" onClick={()=>{setError('');load();}}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}<section className="panel"><div className="section-head flex-wrap gap-3"><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList><TabsTrigger value="requisition">招聘需求</TabsTrigger><TabsTrigger value="candidate">候选人</TabsTrigger><TabsTrigger value="interview">面试记录</TabsTrigger></TabsList></Tabs>{hr&&tab!=='interview'&&<Button onClick={()=>open(tab)}>新增{tab==='requisition'?'需求':'候选人'}</Button>}</div><div className="filters"><Input value={search} aria-label="搜索招聘记录" placeholder="搜索名称或岗位" className="max-w-md" onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Table><TableHeader><TableRow>{['名称','招聘岗位','进度','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell><b>{name(r)}</b>{r.payload.email&&<p className="text-xs text-slate-500">{r.payload.email}</p>}</TableCell><TableCell>{position(r.positionId)}</TableCell><TableCell><Badge variant="outline">{statuses[r.status]??r.status}</Badge>{r.kind==='candidate'&&r.payload.offerReturnReason&&<p className="mt-2 text-xs text-amber-700">录用已退回，待重新发起</p>}{r.kind==='requisition'&&<p className="mt-2 text-xs">已入职 {data?.records.filter(c=>c.kind==='candidate'&&c.referenceId===r.id&&c.status==='hired').length} / {r.payload.headcount}</p>}</TableCell><TableCell>{actions(r)}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="p-8 text-center text-slate-500">暂无可见招聘记录</p>}<div className="flex justify-end items-center gap-3 p-4 text-sm"><span>{rows.length} 条</span><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</Button><Button size="sm" variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>招聘业务办理</DialogTitle><DialogDescription>{form?.action==='acceptOffer'?'由HR登记已取得的候选人接受依据。':form?.action==='hire'?'入职按北京时间判断计划入职日，并同时建立员工档案、岗位关联和任职历史。':'请依据实际岗位需求和评价事实填写，审批由其他有权限的管理人员完成。'}</DialogDescription></DialogHeader>{form&&<form className="edit-form" onSubmit={submit}>{error&&<p role="alert" className="text-red-700">{error}</p>}{(fields[form.action]??[]).filter(f=>(f.key!=='email'||data?.permissions.viewEmail)&&(f.key!=='gradeId'||data?.permissions.viewLevel)).map(f=><label className="field" key={f.key}><span>{f.label}</span>{['position','requisition','grade','recommendation'].includes(f.type??'')?<Select value={form[f.key]||'none'} onValueChange={v=>setForm({...form,[f.key]:v})}><SelectTrigger aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{f.optional?'未指定':'请选择'}</SelectItem>{options(f).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>:f.type==='long'?<textarea required minLength={5} maxLength={4000} rows={4} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<Input type={f.type??'text'} required={!f.optional} maxLength={200} min={f.type==='number'?1:undefined} max={f.key==='rating'?5:f.key==='headcount'?10000:undefined} step={f.type==='number'?1:undefined} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>取消</Button><Button disabled={busy}>{busy?'保存中…':'保存'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{detail?name(detail):'详情'}</DialogTitle><DialogDescription>{detail?position(detail.positionId)+' · '+statuses[detail.status]:''}</DialogDescription></DialogHeader>{detail&&<div className="space-y-4 text-sm">{Object.entries({业务版本:detail.payload.version,需求退回意见:detail.kind==='requisition'?detail.payload.verification:undefined,录用关联面试版本:detail.payload.offerInterviewVersion,录用退回原因:detail.payload.offerReturnReason,来源依据:detail.payload.source,需求依据:detail.payload.reason,评价或录用依据:detail.payload.evidence,面试等级:detail.payload.rating,建议:detail.payload.recommendation==='advance'?'推进':detail.payload.recommendation==='reject'?'不推进':undefined,计划入职日期:detail.payload.joined,职级:core?.grades?.find(g=>g.id===detail.payload.gradeId)?.name,接受录用依据:detail.payload.acceptanceEvidence,结束原因:detail.payload.closedReason}).filter(([,v])=>v!==undefined).map(([k,v])=><div key={k}><p className="text-slate-500">{k}</p><p className="mt-1 whitespace-pre-wrap">{String(v)}</p></div>)}{detail.kind==='candidate'&&<div><h3 className="font-semibold">面试评价</h3>{data?.records.filter(r=>r.kind==='interview'&&r.referenceId===detail.id).map(r=><div className="mt-2 rounded border p-3" key={r.id}>第 {r.payload.version??'历史'} 次 · {r.payload.rating} 级 · {r.payload.recommendation==='advance'?'建议推进':'不建议推进'}<p className="mt-1 whitespace-pre-wrap">{r.payload.evidence}</p></div>)}</div>}{detail.payload.hiredEmployeeId&&<Link className="text-link" href="/employees">查看已建立的员工档案</Link>}<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/></div>}</DialogContent></Dialog>
 </main>;
}
